// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/confidenceBanner.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    heavy_outreach: {
      title: "Take a moment for yourself",
      text: "You've reached out to a lot of people lately without a match yet. That's genuinely hard, and it says nothing about your worth. No pressure to keep going right now.",
    },
    analysis_paralysis: {
      title: "You have enough information",
      text: "You've been browsing for a while without reaching out to anyone yet. Sometimes more looking doesn't lead to a better decision — it might be worth just sending a Notice to someone who caught your eye.",
    },
    heavy_browsing: {
      title: "Take a moment for yourself",
      text: "You've been active here for several days without a match yet. That's genuinely hard. No pressure to keep going right now.",
    },
    dismissA11y: "Dismiss",
  },
  es: {
    heavy_outreach: {
      title: "Tómate un momento para ti",
      text: "Últimamente has escrito a mucha gente sin conseguir un match todavía. Es de verdad difícil, y no dice nada de tu valor. No hay prisa por seguir ahora.",
    },
    analysis_paralysis: {
      title: "Ya tienes suficiente información",
      text: "Llevas un rato explorando sin escribir a nadie. A veces mirar más no lleva a una mejor decisión: quizá valga la pena enviar un aviso a alguien que te llamó la atención.",
    },
    heavy_browsing: {
      title: "Tómate un momento para ti",
      text: "Llevas varios días activo aquí sin conseguir un match todavía. Es de verdad difícil. No hay prisa por seguir ahora.",
    },
    dismissA11y: "Cerrar",
  },
  de: {
    heavy_outreach: {
      title: "Nimm dir einen Moment für dich",
      text: "Du hast in letzter Zeit viele Leute angeschrieben, ohne dass es schon ein Match gab. Das ist wirklich schwer und sagt nichts über deinen Wert. Kein Druck, jetzt weiterzumachen.",
    },
    analysis_paralysis: {
      title: "Du weißt genug",
      text: "Du schaust dich schon eine Weile um, ohne jemanden anzuschreiben. Mehr Schauen führt nicht immer zu einer besseren Entscheidung. Vielleicht sendest du einfach jemandem, der dir aufgefallen ist, einen Hinweis.",
    },
    heavy_browsing: {
      title: "Nimm dir einen Moment für dich",
      text: "Du bist seit einigen Tagen aktiv, ohne dass es schon ein Match gab. Das ist wirklich schwer. Kein Druck, jetzt weiterzumachen.",
    },
    dismissA11y: "Schließen",
  },
  fr: {
    heavy_outreach: {
      title: "Prenez un moment pour vous",
      text: "Vous avez contacté beaucoup de personnes ces derniers temps sans match pour l'instant. C'est vraiment difficile, et cela ne dit rien de votre valeur. Aucune pression pour continuer maintenant.",
    },
    analysis_paralysis: {
      title: "Vous en savez assez",
      text: "Vous parcourez les profils depuis un moment sans contacter personne. Regarder davantage ne mène pas toujours à une meilleure décision : envoyer un avis à quelqu'un qui vous a plu pourrait valoir le coup.",
    },
    heavy_browsing: {
      title: "Prenez un moment pour vous",
      text: "Vous êtes actif ici depuis plusieurs jours sans match pour l'instant. C'est vraiment difficile. Aucune pression pour continuer maintenant.",
    },
    dismissA11y: "Fermer",
  },
  pt: {
    heavy_outreach: {
      title: "Tire um momento para você",
      text: "Você falou com muita gente ultimamente e ainda não teve um match. Isso é difícil de verdade, e não diz nada sobre o seu valor. Sem pressão para continuar agora.",
    },
    analysis_paralysis: {
      title: "Você já tem informação suficiente",
      text: "Você está olhando há um tempo sem falar com ninguém. Às vezes olhar mais não leva a uma decisão melhor: talvez valha mandar um aviso para alguém que chamou sua atenção.",
    },
    heavy_browsing: {
      title: "Tire um momento para você",
      text: "Você está ativo aqui há vários dias e ainda não teve um match. Isso é difícil de verdade. Sem pressão para continuar agora.",
    },
    dismissA11y: "Fechar",
  },
  ht: {
    heavy_outreach: {
      title: "Pran yon ti moman pou ou",
      text: "Ou kontakte anpil moun dènye tan sa yo san ou pa gen match toujou. Sa difisil tout bon, epi li pa di anyen sou valè w. Pa gen presyon pou kontinye kounye a.",
    },
    analysis_paralysis: {
      title: "Ou gen ase enfòmasyon",
      text: "Sa fè yon ti tan w ap gade san ou pa kontakte pèsonn. Pafwa gade plis pa mennen nan pi bon desizyon: li ka vo lapenn voye yon avi bay yon moun ki te atire w.",
    },
    heavy_browsing: {
      title: "Pran yon ti moman pou ou",
      text: "Sa fè plizyè jou ou aktif isit la san ou pa gen match toujou. Sa difisil tout bon. Pa gen presyon pou kontinye kounye a.",
    },
    dismissA11y: "Fèmen",
  },
  zh: {
    heavy_outreach: {
      title: "给自己一点时间",
      text: "你最近联系了很多人，但还没有配对成功。这确实不容易，也完全不代表你的价值。现在不必勉强继续。",
    },
    analysis_paralysis: {
      title: "你已经了解得够多了",
      text: "你已经浏览了一段时间，但还没有联系任何人。有时看得更多并不会带来更好的决定，不妨给吸引你的人发一个提醒。",
    },
    heavy_browsing: {
      title: "给自己一点时间",
      text: "你在这里活跃了好几天，但还没有配对成功。这确实不容易。现在不必勉强继续。",
    },
    dismissA11y: "关闭",
  },
  vi: {
    heavy_outreach: {
      title: "Dành chút thời gian cho bản thân",
      text: "Gần đây bạn đã nhắn cho nhiều người mà chưa có match nào. Điều đó thật sự khó khăn, và không nói lên gì về giá trị của bạn. Không cần áp lực phải tiếp tục ngay.",
    },
    analysis_paralysis: {
      title: "Bạn đã có đủ thông tin",
      text: "Bạn đã xem một lúc mà chưa nhắn cho ai. Đôi khi xem thêm không giúp quyết định tốt hơn: có lẽ nên gửi một thông báo cho người đã thu hút bạn.",
    },
    heavy_browsing: {
      title: "Dành chút thời gian cho bản thân",
      text: "Bạn đã hoạt động ở đây vài ngày mà chưa có match nào. Điều đó thật sự khó khăn. Không cần áp lực phải tiếp tục ngay.",
    },
    dismissA11y: "Đóng",
  },
  tl: {
    heavy_outreach: {
      title: "Maglaan ng sandali para sa sarili mo",
      text: "Marami kang nilapitan nitong mga nakaraan pero wala pang match. Talagang mahirap iyon, at wala itong sinasabi tungkol sa halaga mo. Walang pressure na magpatuloy ngayon.",
    },
    analysis_paralysis: {
      title: "Sapat na ang alam mo",
      text: "Matagal ka nang nagba-browse nang hindi pa lumalapit sa kahit sino. Minsan hindi humahantong sa mas magandang desisyon ang mas maraming pagtingin: baka sulit nang magpadala ng abiso sa taong pumukaw sa atensyon mo.",
    },
    heavy_browsing: {
      title: "Maglaan ng sandali para sa sarili mo",
      text: "Ilang araw ka nang aktibo dito pero wala pang match. Talagang mahirap iyon. Walang pressure na magpatuloy ngayon.",
    },
    dismissA11y: "Isara",
  },
  ru: {
    heavy_outreach: {
      title: "Найдите минутку для себя",
      text: "В последнее время вы написали многим, но совпадений пока нет. Это действительно тяжело, и это ничего не говорит о вашей ценности. Не нужно заставлять себя продолжать прямо сейчас.",
    },
    analysis_paralysis: {
      title: "Информации уже достаточно",
      text: "Вы уже какое-то время смотрите профили, никому не написав. Иногда больше просмотров не помогает принять лучшее решение: возможно, стоит просто отправить уведомление тому, кто вам понравился.",
    },
    heavy_browsing: {
      title: "Найдите минутку для себя",
      text: "Вы активны здесь уже несколько дней, но совпадений пока нет. Это действительно тяжело. Не нужно заставлять себя продолжать прямо сейчас.",
    },
    dismissA11y: "Закрыть",
  },
  ko: {
    heavy_outreach: {
      title: "잠시 자신을 위한 시간을 가져요",
      text: "최근 많은 사람에게 연락했지만 아직 매칭이 없네요. 정말 힘든 일이고, 당신의 가치와는 아무 상관이 없어요. 지금 계속해야 한다는 부담은 갖지 마세요.",
    },
    analysis_paralysis: {
      title: "이미 충분히 알고 있어요",
      text: "한동안 둘러보기만 하고 아직 아무에게도 연락하지 않았어요. 더 본다고 더 나은 결정이 나오지는 않을 때도 있어요. 눈에 띈 사람에게 알림을 보내 보는 건 어떨까요?",
    },
    heavy_browsing: {
      title: "잠시 자신을 위한 시간을 가져요",
      text: "며칠째 활동 중이지만 아직 매칭이 없네요. 정말 힘든 일이에요. 지금 계속해야 한다는 부담은 갖지 마세요.",
    },
    dismissA11y: "닫기",
  },
};
