// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/features.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    cat: {
      meeting: "Meeting People",
      together: "Building Something Real",
      growth: "For You",
      safety: "Safety & Trust",
      extras: "Extras",
    },
    f: {
      crossedPaths: {
        name: "Crossed Paths",
        desc: "The main way you find people — shows you who you've actually been near recently (about 35 feet, a few minutes ago), not just anyone in the city.",
      },
      noticesWaves: {
        name: "Notices & Waves",
        desc: "A Notice is silent — the other person only finds out if they notice you back too. A Wave tells them right away. Both live in the \"Interested\" tab.",
      },
      browse: {
        name: "Browse",
        desc: "An optional second way to discover people — not limited to proximity, shows a wider pool matching your filters. Switch to it from Discover's People mode.",
      },
      gatherings: {
        name: "Gatherings",
        desc: "Real things happening nearby — coffee meetups, hikes, game nights — hosted by people near you. A great way to meet people even before matching.",
      },
      gatheringsMap: {
        name: "Gatherings Map",
        desc: "See gatherings on an actual map instead of a list. Locations are shown approximately, never your exact address.",
      },
      ourConstitution: {
        name: "Our Constitution",
        desc: "A living agreement with a match — how you handle conflict, make big decisions, and support each other, written together.",
      },
      timelineThoughts: {
        name: "Timeline Thoughts",
        desc: "A space to share expectations about pacing and timing, before mismatches turn into friction.",
      },
      memoryVault: {
        name: "Memory Vault",
        desc: "A shared place to save the small stuff worth remembering — milestones, inside jokes, funny moments.",
      },
      whatIf: {
        name: "What If...",
        desc: "Hypothetical scenarios to surface real conversations worth having before they actually come up.",
      },
      sharedPlaylist: {
        name: "Shared Playlist",
        desc: "Build a music playlist together with a match.",
      },
      planATrip: {
        name: "Plan a Trip",
        desc: "Brainstorm destinations, activities, and budget ideas together.",
      },
      bigPicture: {
        name: "Big Picture",
        desc: "A space for the bigger conversations — living situations, finances, family, long-term plans.",
      },
      relationshipWisdom: {
        name: "Relationship Wisdom",
        desc: "Read anonymous reflections other couples chose to share, or leave your own.",
      },
      rehearsalRoom: {
        name: "Rehearsal Room",
        desc: "Practice a hard conversation with an AI role-play partner before having it for real. Nothing here is saved permanently or about a real person.",
      },
      toolkit: {
        name: "Toolkit",
        desc: "General guidance on hard conversations, apologizing, rebuilding trust, and reconnecting after distance.",
      },
      chemistryDiary: {
        name: "Chemistry Diary",
        desc: "A private log of how time with someone actually felt. Over time, builds an honest picture of what genuinely feels good to you.",
      },
      privateReflections: {
        name: "Private Reflections",
        desc: "A private space to write down what you learned from a connection, however it ended. Only you can see it.",
      },
      helpMeSayIt: {
        name: "Help Me Say It",
        desc: "Stuck on how to say something hard? Get help finding the words, right from a chat.",
      },
      idVerification: {
        name: "ID Verification",
        desc: "Verify your identity to get a badge on your profile and appear when others filter for verified profiles.",
      },
      blockedUsers: {
        name: "Blocked Users",
        desc: "Manage who you’ve blocked. You can unblock anyone at any time.",
      },
      dateSafetyCheckIn: {
        name: "Date Safety Check-In",
        desc: "Share your live location snapshot with a trusted contact before a date, from within a chat.",
      },
      disappearingMessages: {
        name: "Disappearing Messages",
        desc: "Turn on a 24-hour auto-delete for a specific conversation, from the chat options menu.",
      },
      inviteFriends: {
        name: "Invite Friends",
        desc: "Share your referral code — when a friend joins with it, you both get 3 bonus Notices.",
      },
      offersPerks: {
        name: "Offers & Perks",
        desc: "Deals from local businesses and brands partnering with Nearby.",
      },
      languages: {
        name: "11 Languages",
        desc: "Switch the app’s language anytime in Settings.",
      },
    },
    title: "Everything In Nearby",
    subtitle: "A quick reference for everything the app can do — tap a category to see what's inside.",
    collapseA11y: "{title}, tap to collapse",
    expandA11y: "{title}, tap to expand",
  },
  es: {
    cat: {
      meeting: "Conocer gente",
      together: "Construir algo real",
      growth: "Para ti",
      safety: "Seguridad y confianza",
      extras: "Extras",
    },
    f: {
      crossedPaths: {
        name: "Caminos Cruzados",
        desc: "La forma principal de encontrar gente: te muestra con quién has coincidido de verdad hace poco (a unos 10 metros, hace unos minutos), no a cualquiera de la ciudad.",
      },
      noticesWaves: {
        name: "Avisos y saludos",
        desc: "Un aviso es silencioso: la otra persona solo se entera si también se fija en ti. Un saludo se lo dice enseguida. Ambos están en la pestaña «Interesados».",
      },
      browse: {
        name: "Explorar",
        desc: "Una segunda forma opcional de descubrir gente: sin limitarse a la cercanía, muestra más personas que encajan con tus filtros. Actívala desde el modo Personas de Descubrir.",
      },
      gatherings: {
        name: "Encuentros",
        desc: "Cosas reales que pasan cerca, como quedadas para un café, caminatas o noches de juegos, organizadas por gente de tu zona. Una gran forma de conocer gente incluso antes de hacer match.",
      },
      gatheringsMap: {
        name: "Mapa de encuentros",
        desc: "Mira los encuentros en un mapa en lugar de una lista. Las ubicaciones son aproximadas, nunca tu dirección exacta.",
      },
      ourConstitution: {
        name: "Nuestra constitución",
        desc: "Un acuerdo vivo con un match: cómo manejan los conflictos, toman decisiones importantes y se apoyan, escrito juntos.",
      },
      timelineThoughts: {
        name: "Ideas sobre los tiempos",
        desc: "Un espacio para compartir expectativas sobre el ritmo y los tiempos, antes de que las diferencias se conviertan en roces.",
      },
      memoryVault: {
        name: "Baúl de recuerdos",
        desc: "Un lugar compartido para guardar las pequeñas cosas que vale la pena recordar: hitos, bromas internas, momentos divertidos.",
      },
      whatIf: {
        name: "¿Y si...?",
        desc: "Situaciones hipotéticas para abrir conversaciones que vale la pena tener antes de que ocurran de verdad.",
      },
      sharedPlaylist: {
        name: "Playlist compartida",
        desc: "Crea una playlist junto con un match.",
      },
      planATrip: {
        name: "Planear un viaje",
        desc: "Piensen juntos en destinos, actividades e ideas de presupuesto.",
      },
      bigPicture: {
        name: "Visión de conjunto",
        desc: "Un espacio para las conversaciones más grandes: dónde vivir, finanzas, familia, planes a largo plazo.",
      },
      relationshipWisdom: {
        name: "Sabiduría de pareja",
        desc: "Lee reflexiones anónimas que otras parejas decidieron compartir, o deja la tuya.",
      },
      rehearsalRoom: {
        name: "Sala de ensayo",
        desc: "Practica una conversación difícil con un compañero de rol con IA antes de tenerla de verdad. Nada se guarda de forma permanente ni trata de una persona real.",
      },
      toolkit: {
        name: "Caja de herramientas",
        desc: "Consejos generales sobre conversaciones difíciles, pedir perdón, recuperar la confianza y reconectar tras la distancia.",
      },
      chemistryDiary: {
        name: "Diario de química",
        desc: "Un registro privado de cómo te sentiste de verdad al pasar tiempo con alguien. Con el tiempo, crea una imagen honesta de lo que de verdad te sienta bien.",
      },
      privateReflections: {
        name: "Reflexiones privadas",
        desc: "Un espacio privado para escribir lo que aprendiste de una conexión, termine como termine. Solo tú puedes verlo.",
      },
      helpMeSayIt: {
        name: "Ayúdame a decirlo",
        desc: "¿Te cuesta decir algo difícil? Encuentra las palabras con ayuda, desde el propio chat.",
      },
      idVerification: {
        name: "Verificación de identidad",
        desc: "Verifica tu identidad para tener una insignia en tu perfil y aparecer cuando otros filtren por perfiles verificados.",
      },
      blockedUsers: {
        name: "Usuarios bloqueados",
        desc: "Gestiona a quién has bloqueado. Puedes desbloquear a cualquiera cuando quieras.",
      },
      dateSafetyCheckIn: {
        name: "Control de seguridad para citas",
        desc: "Comparte una instantánea de tu ubicación con un contacto de confianza antes de una cita, desde el chat.",
      },
      disappearingMessages: {
        name: "Mensajes temporales",
        desc: "Activa el borrado automático a las 24 horas en una conversación, desde el menú de opciones del chat.",
      },
      inviteFriends: {
        name: "Invitar amigos",
        desc: "Comparte tu código de invitación: cuando un amigo se una con él, ambos reciben 3 avisos extra.",
      },
      offersPerks: {
        name: "Ofertas y ventajas",
        desc: "Ofertas de negocios y marcas locales que colaboran con Nearby.",
      },
      languages: {
        name: "11 idiomas",
        desc: "Cambia el idioma de la app cuando quieras en Ajustes.",
      },
    },
    title: "Todo lo que hay en Nearby",
    subtitle: "Una guía rápida de todo lo que puede hacer la app: toca una categoría para ver qué incluye.",
    collapseA11y: "{title}, toca para contraer",
    expandA11y: "{title}, toca para desplegar",
  },
  de: {
    cat: {
      meeting: "Leute kennenlernen",
      together: "Etwas Echtes aufbauen",
      growth: "Für dich",
      safety: "Sicherheit & Vertrauen",
      extras: "Extras",
    },
    f: {
      crossedPaths: {
        name: "Gekreuzte Wege",
        desc: "Der wichtigste Weg, Menschen zu finden: Er zeigt, wem du kürzlich wirklich nahe warst (etwa 10 Meter, vor ein paar Minuten), nicht irgendwen in der Stadt.",
      },
      noticesWaves: {
        name: "Hinweise & Winken",
        desc: "Ein Hinweis ist still: Die andere Person erfährt es nur, wenn sie dich auch bemerkt. Beim Winken erfährt sie es sofort. Beides findest du im Tab „Interessiert“.",
      },
      browse: {
        name: "Stöbern",
        desc: "Ein optionaler zweiter Weg, Menschen zu entdecken: nicht auf Nähe beschränkt, zeigt mehr Leute, die zu deinen Filtern passen. Umschalten im Personen-Modus von Entdecken.",
      },
      gatherings: {
        name: "Treffen",
        desc: "Echte Treffen in der Nähe, etwa Kaffee, Wanderungen oder Spieleabende, organisiert von Leuten aus deiner Gegend. Ein toller Weg, Menschen kennenzulernen, schon vor einem Match.",
      },
      gatheringsMap: {
        name: "Treffen-Karte",
        desc: "Sieh Treffen auf einer Karte statt in einer Liste. Orte werden nur ungefähr gezeigt, nie deine genaue Adresse.",
      },
      ourConstitution: {
        name: "Unsere Verfassung",
        desc: "Eine lebendige Vereinbarung mit einem Match: wie ihr mit Konflikten umgeht, große Entscheidungen trefft und euch unterstützt, gemeinsam geschrieben.",
      },
      timelineThoughts: {
        name: "Gedanken zum Tempo",
        desc: "Ein Raum, um Erwartungen an Tempo und Timing zu teilen, bevor Unterschiede zu Reibung werden.",
      },
      memoryVault: {
        name: "Erinnerungstresor",
        desc: "Ein gemeinsamer Ort für die kleinen Dinge, die man nicht vergessen will: Meilensteine, Insider-Witze, lustige Momente.",
      },
      whatIf: {
        name: "Was wäre, wenn...",
        desc: "Hypothetische Szenarien, um echte Gespräche anzustoßen, bevor die Situation tatsächlich eintritt.",
      },
      sharedPlaylist: {
        name: "Gemeinsame Playlist",
        desc: "Stellt zusammen mit einem Match eine Playlist zusammen.",
      },
      planATrip: {
        name: "Eine Reise planen",
        desc: "Sammelt gemeinsam Ziele, Aktivitäten und Budgetideen.",
      },
      bigPicture: {
        name: "Das große Ganze",
        desc: "Ein Raum für die großen Gespräche: Wohnen, Finanzen, Familie, langfristige Pläne.",
      },
      relationshipWisdom: {
        name: "Beziehungsweisheit",
        desc: "Lies anonyme Gedanken, die andere Paare geteilt haben, oder hinterlass deine eigenen.",
      },
      rehearsalRoom: {
        name: "Proberaum",
        desc: "Übe ein schwieriges Gespräch mit einem KI-Rollenspielpartner, bevor du es wirklich führst. Nichts wird dauerhaft gespeichert, und es geht um keine echte Person.",
      },
      toolkit: {
        name: "Werkzeugkasten",
        desc: "Allgemeine Tipps zu schwierigen Gesprächen, Entschuldigungen, dem Wiederaufbau von Vertrauen und dem Wiederannähern nach Distanz.",
      },
      chemistryDiary: {
        name: "Chemie-Tagebuch",
        desc: "Ein privates Protokoll, wie sich die Zeit mit jemandem wirklich angefühlt hat. Mit der Zeit entsteht ein ehrliches Bild davon, was dir wirklich guttut.",
      },
      privateReflections: {
        name: "Private Gedanken",
        desc: "Ein privater Ort, um festzuhalten, was du aus einer Verbindung gelernt hast, wie auch immer sie endete. Nur du kannst es sehen.",
      },
      helpMeSayIt: {
        name: "Hilf mir, es zu sagen",
        desc: "Fällt dir etwas Schwieriges schwer zu sagen? Hol dir direkt im Chat Hilfe bei den Worten.",
      },
      idVerification: {
        name: "Identitätsprüfung",
        desc: "Bestätige deine Identität, um ein Abzeichen im Profil zu bekommen und angezeigt zu werden, wenn andere nach verifizierten Profilen filtern.",
      },
      blockedUsers: {
        name: "Blockierte Personen",
        desc: "Verwalte, wen du blockiert hast. Du kannst jederzeit wieder entsperren.",
      },
      dateSafetyCheckIn: {
        name: "Sicherheits-Check-in fürs Date",
        desc: "Teile vor einem Date einen Schnappschuss deines Standorts mit einer Vertrauensperson, direkt aus dem Chat.",
      },
      disappearingMessages: {
        name: "Selbstlöschende Nachrichten",
        desc: "Schalte für einen Chat das automatische Löschen nach 24 Stunden ein, über das Chat-Menü.",
      },
      inviteFriends: {
        name: "Freunde einladen",
        desc: "Teile deinen Einladungscode: Wenn sich jemand damit anmeldet, bekommt ihr beide 3 zusätzliche Hinweise.",
      },
      offersPerks: {
        name: "Angebote & Vorteile",
        desc: "Angebote von Unternehmen und Marken vor Ort, die mit Nearby zusammenarbeiten.",
      },
      languages: {
        name: "11 Sprachen",
        desc: "Wechsle die App-Sprache jederzeit in den Einstellungen.",
      },
    },
    title: "Alles in Nearby",
    subtitle: "Ein schneller Überblick über alles, was die App kann. Tippe auf eine Kategorie, um zu sehen, was drin ist.",
    collapseA11y: "{title}, zum Einklappen tippen",
    expandA11y: "{title}, zum Aufklappen tippen",
  },
  fr: {
    cat: {
      meeting: "Rencontrer des gens",
      together: "Construire quelque chose de vrai",
      growth: "Pour vous",
      safety: "Sécurité et confiance",
      extras: "Extras",
    },
    f: {
      crossedPaths: {
        name: "Chemins Croisés",
        desc: "Le moyen principal de trouver des gens : il vous montre qui vous avez vraiment croisé récemment (à environ 10 mètres, il y a quelques minutes), pas n'importe qui en ville.",
      },
      noticesWaves: {
        name: "Avis et signes",
        desc: "Un avis est discret : l'autre personne ne le sait que si elle vous remarque aussi. Un signe le lui dit tout de suite. Les deux se trouvent dans l'onglet « Intéressés ».",
      },
      browse: {
        name: "Parcourir",
        desc: "Une seconde façon facultative de découvrir des gens : sans limite de proximité, elle montre un plus large choix correspondant à vos filtres. Activez-la depuis le mode Personnes de Découvrir.",
      },
      gatherings: {
        name: "Rencontres",
        desc: "De vraies activités près de chez vous, comme des cafés, des randonnées ou des soirées jeux, organisées par des gens du coin. Un excellent moyen de rencontrer du monde, même avant un match.",
      },
      gatheringsMap: {
        name: "Carte des rencontres",
        desc: "Voyez les rencontres sur une vraie carte plutôt qu'une liste. Les lieux sont approximatifs, jamais votre adresse exacte.",
      },
      ourConstitution: {
        name: "Notre constitution",
        desc: "Un accord vivant avec un match : comment vous gérez les conflits, prenez les grandes décisions et vous soutenez, écrit ensemble.",
      },
      timelineThoughts: {
        name: "Réflexions sur le rythme",
        desc: "Un espace pour partager vos attentes sur le rythme et le calendrier, avant que les décalages ne deviennent des frictions.",
      },
      memoryVault: {
        name: "Coffre à souvenirs",
        desc: "Un lieu partagé pour garder les petites choses qui comptent : étapes, blagues entre vous, moments drôles.",
      },
      whatIf: {
        name: "Et si...",
        desc: "Des scénarios hypothétiques pour ouvrir de vraies conversations avant que la situation ne se présente.",
      },
      sharedPlaylist: {
        name: "Playlist partagée",
        desc: "Créez une playlist à deux avec un match.",
      },
      planATrip: {
        name: "Planifier un voyage",
        desc: "Réfléchissez ensemble aux destinations, activités et idées de budget.",
      },
      bigPicture: {
        name: "Vue d'ensemble",
        desc: "Un espace pour les grandes conversations : logement, finances, famille, projets à long terme.",
      },
      relationshipWisdom: {
        name: "Sagesse amoureuse",
        desc: "Lisez des réflexions anonymes que d'autres couples ont choisi de partager, ou laissez la vôtre.",
      },
      rehearsalRoom: {
        name: "Salle de répétition",
        desc: "Entraînez-vous à une conversation difficile avec un partenaire de jeu de rôle IA avant de l'avoir pour de vrai. Rien n'est conservé définitivement ni ne concerne une vraie personne.",
      },
      toolkit: {
        name: "Boîte à outils",
        desc: "Des conseils généraux sur les conversations difficiles, les excuses, la confiance à rebâtir et le rapprochement après la distance.",
      },
      chemistryDiary: {
        name: "Journal d'alchimie",
        desc: "Un journal privé de ce que vous avez vraiment ressenti avec quelqu'un. Avec le temps, il dresse un portrait honnête de ce qui vous fait vraiment du bien.",
      },
      privateReflections: {
        name: "Réflexions privées",
        desc: "Un espace privé pour écrire ce que vous avez appris d'une relation, quelle qu'en soit la fin. Vous seul pouvez le voir.",
      },
      helpMeSayIt: {
        name: "Aide-moi à le dire",
        desc: "Du mal à dire quelque chose de difficile ? Trouvez les mots avec de l'aide, directement depuis un chat.",
      },
      idVerification: {
        name: "Vérification d'identité",
        desc: "Vérifiez votre identité pour obtenir un badge sur votre profil et apparaître quand d'autres filtrent les profils vérifiés.",
      },
      blockedUsers: {
        name: "Utilisateurs bloqués",
        desc: "Gérez les personnes que vous avez bloquées. Vous pouvez débloquer n'importe qui à tout moment.",
      },
      dateSafetyCheckIn: {
        name: "Suivi de sécurité pour les rendez-vous",
        desc: "Partagez un instantané de votre position avec un contact de confiance avant un rendez-vous, depuis un chat.",
      },
      disappearingMessages: {
        name: "Messages éphémères",
        desc: "Activez la suppression automatique après 24 heures pour une conversation, depuis le menu d'options du chat.",
      },
      inviteFriends: {
        name: "Inviter des amis",
        desc: "Partagez votre code de parrainage : quand un ami s'inscrit avec, vous recevez tous les deux 3 avis bonus.",
      },
      offersPerks: {
        name: "Offres et avantages",
        desc: "Des offres de commerces et de marques locales partenaires de Nearby.",
      },
      languages: {
        name: "11 langues",
        desc: "Changez la langue de l'app à tout moment dans les Réglages.",
      },
    },
    title: "Tout Nearby",
    subtitle: "Un aperçu rapide de tout ce que l'app peut faire : touchez une catégorie pour voir son contenu.",
    collapseA11y: "{title}, touchez pour réduire",
    expandA11y: "{title}, touchez pour développer",
  },
  pt: {
    cat: {
      meeting: "Conhecer pessoas",
      together: "Construir algo de verdade",
      growth: "Para você",
      safety: "Segurança e confiança",
      extras: "Extras",
    },
    f: {
      crossedPaths: {
        name: "Caminhos Cruzados",
        desc: "O principal jeito de encontrar pessoas: mostra quem esteve mesmo perto de você recentemente (cerca de 10 metros, há poucos minutos), não qualquer pessoa da cidade.",
      },
      noticesWaves: {
        name: "Avisos e acenos",
        desc: "Um aviso é silencioso: a outra pessoa só fica sabendo se também notar você. Um aceno avisa na hora. Os dois ficam na aba \"Interessados\".",
      },
      browse: {
        name: "Explorar",
        desc: "Uma segunda forma opcional de conhecer pessoas: sem se limitar à proximidade, mostra mais gente que combina com seus filtros. Mude para ela no modo Pessoas do Descobrir.",
      },
      gatherings: {
        name: "Encontros",
        desc: "Coisas reais acontecendo por perto, como cafés, trilhas e noites de jogos, organizadas por pessoas da sua região. Um ótimo jeito de conhecer gente antes mesmo de dar match.",
      },
      gatheringsMap: {
        name: "Mapa de encontros",
        desc: "Veja os encontros num mapa em vez de uma lista. Os locais são aproximados, nunca seu endereço exato.",
      },
      ourConstitution: {
        name: "Nossa constituição",
        desc: "Um acordo vivo com um match: como vocês lidam com conflitos, tomam grandes decisões e se apoiam, escrito juntos.",
      },
      timelineThoughts: {
        name: "Ideias sobre o ritmo",
        desc: "Um espaço para compartilhar expectativas sobre ritmo e tempo, antes que as diferenças virem atrito.",
      },
      memoryVault: {
        name: "Baú de memórias",
        desc: "Um lugar compartilhado para guardar as pequenas coisas que valem lembrar: marcos, piadas internas, momentos engraçados.",
      },
      whatIf: {
        name: "E se...",
        desc: "Cenários hipotéticos para abrir conversas que valem a pena antes que aconteçam de verdade.",
      },
      sharedPlaylist: {
        name: "Playlist compartilhada",
        desc: "Monte uma playlist junto com um match.",
      },
      planATrip: {
        name: "Planejar uma viagem",
        desc: "Pensem juntos em destinos, atividades e ideias de orçamento.",
      },
      bigPicture: {
        name: "Visão geral",
        desc: "Um espaço para as conversas maiores: onde morar, finanças, família, planos de longo prazo.",
      },
      relationshipWisdom: {
        name: "Sabedoria de relacionamento",
        desc: "Leia reflexões anônimas que outros casais escolheram compartilhar, ou deixe a sua.",
      },
      rehearsalRoom: {
        name: "Sala de ensaio",
        desc: "Pratique uma conversa difícil com um parceiro de simulação com IA antes de ter a conversa de verdade. Nada é salvo para sempre nem é sobre uma pessoa real.",
      },
      toolkit: {
        name: "Caixa de ferramentas",
        desc: "Orientações gerais sobre conversas difíceis, pedir desculpas, reconstruir a confiança e se reconectar depois da distância.",
      },
      chemistryDiary: {
        name: "Diário de química",
        desc: "Um registro privado de como foi de verdade passar tempo com alguém. Com o tempo, forma uma imagem honesta do que realmente faz bem a você.",
      },
      privateReflections: {
        name: "Reflexões privadas",
        desc: "Um espaço privado para escrever o que você aprendeu com uma conexão, seja como for que terminou. Só você vê.",
      },
      helpMeSayIt: {
        name: "Me ajude a dizer",
        desc: "Tem dificuldade para dizer algo difícil? Tenha ajuda para achar as palavras, direto do chat.",
      },
      idVerification: {
        name: "Verificação de identidade",
        desc: "Verifique sua identidade para ganhar um selo no perfil e aparecer quando outras pessoas filtrarem por perfis verificados.",
      },
      blockedUsers: {
        name: "Usuários bloqueados",
        desc: "Gerencie quem você bloqueou. Você pode desbloquear qualquer pessoa a qualquer momento.",
      },
      dateSafetyCheckIn: {
        name: "Check-in de segurança no encontro",
        desc: "Compartilhe um registro da sua localização com um contato de confiança antes de um encontro, pelo chat.",
      },
      disappearingMessages: {
        name: "Mensagens temporárias",
        desc: "Ative a exclusão automática em 24 horas para uma conversa, pelo menu de opções do chat.",
      },
      inviteFriends: {
        name: "Convidar amigos",
        desc: "Compartilhe seu código de indicação: quando um amigo entrar com ele, vocês dois ganham 3 avisos extras.",
      },
      offersPerks: {
        name: "Ofertas e vantagens",
        desc: "Ofertas de negócios e marcas locais parceiras do Nearby.",
      },
      languages: {
        name: "11 idiomas",
        desc: "Troque o idioma do app quando quiser em Ajustes.",
      },
    },
    title: "Tudo no Nearby",
    subtitle: "Um guia rápido de tudo o que o app faz: toque em uma categoria para ver o que tem dentro.",
    collapseA11y: "{title}, toque para recolher",
    expandA11y: "{title}, toque para expandir",
  },
  ht: {
    cat: {
      meeting: "Rankontre moun",
      together: "Bati yon bagay ki vre",
      growth: "Pou ou",
      safety: "Sekirite ak konfyans",
      extras: "Siplemantè",
    },
    f: {
      crossedPaths: {
        name: "Chemen Kwaze",
        desc: "Prensipal fason pou jwenn moun: li montre w moun ki te vrèman toupre w dènyèman (anviwon 35 pye, kèk minit de sa), pa nenpòt moun nan vil la.",
      },
      noticesWaves: {
        name: "Avi ak salitasyon",
        desc: "Yon avi an silans: lòt moun nan konnen sèlman si li remake w tou. Yon salitasyon di l touswit. Tou de nan onglè \"Enterese\" a.",
      },
      browse: {
        name: "Gade",
        desc: "Yon dezyèm fason opsyonèl pou dekouvri moun: san limit distans, li montre plis moun ki koresponn ak filt ou yo. Chanje pou li nan mòd Moun nan Dekouvri.",
      },
      gatherings: {
        name: "Rankont",
        desc: "Vrè bagay k ap pase toupre w, tankou rankont pou kafe, randone, swa jwèt, òganize pa moun ki toupre w. Yon bon fason pou rankontre moun menm anvan yon match.",
      },
      gatheringsMap: {
        name: "Kat rankont yo",
        desc: "Wè rankont yo sou yon kat olye yon lis. Kote yo montre apeprè, pa janm adrès egzak ou.",
      },
      ourConstitution: {
        name: "Konstitisyon nou",
        desc: "Yon akò vivan ak yon match: kijan nou jere konfli, pran gwo desizyon ak sipòte youn lòt, ekri ansanm.",
      },
      timelineThoughts: {
        name: "Panse sou ritm",
        desc: "Yon espas pou pataje sa nou atann sou ritm ak tan, anvan diferans yo tounen friksyon.",
      },
      memoryVault: {
        name: "Bwat souvni",
        desc: "Yon kote pataje pou kenbe ti bagay ki merite sonje: etap enpòtan, blag ant nou, moman komik.",
      },
      whatIf: {
        name: "E si...",
        desc: "Senaryo imajinè pou louvri vrè konvèsasyon ki merite fèt anvan sa rive vre.",
      },
      sharedPlaylist: {
        name: "Playlist pataje",
        desc: "Kreye yon playlist ansanm ak yon match.",
      },
      planATrip: {
        name: "Planifye yon vwayaj",
        desc: "Reflechi ansanm sou destinasyon, aktivite ak ide bidjè.",
      },
      bigPicture: {
        name: "Gwo foto a",
        desc: "Yon espas pou gwo konvèsasyon: kote pou viv, lajan, fanmi, plan alontèm.",
      },
      relationshipWisdom: {
        name: "Sajès nan relasyon",
        desc: "Li refleksyon anonim lòt koup chwazi pataje, oswa kite pa w.",
      },
      rehearsalRoom: {
        name: "Sal repetisyon",
        desc: "Pratike yon konvèsasyon difisil ak yon patnè jwe wòl IA anvan w fè l tout bon. Anyen pa anrejistre pou toujou, ni pa konsène yon vrè moun.",
      },
      toolkit: {
        name: "Bwat zouti",
        desc: "Konsèy jeneral sou konvèsasyon difisil, mande padon, rebati konfyans ak rekonekte apre distans.",
      },
      chemistryDiary: {
        name: "Jounal chimi",
        desc: "Yon jounal prive sou jan tan ak yon moun te fè w santi w vre. Avèk tan, li bati yon foto onèt sou sa ki fè w byen tout bon.",
      },
      privateReflections: {
        name: "Refleksyon prive",
        desc: "Yon espas prive pou ekri sa ou te aprann nan yon koneksyon, kèlkeswa jan li te fini. Se ou sèl ki ka wè l.",
      },
      helpMeSayIt: {
        name: "Ede m di l",
        desc: "Ou bloke pou di yon bagay difisil? Jwenn èd pou chwazi mo yo, dirèkteman nan yon chat.",
      },
      idVerification: {
        name: "Verifikasyon idantite",
        desc: "Verifye idantite w pou jwenn yon badj sou pwofil ou epi parèt lè lòt moun filtre pou pwofil verifye.",
      },
      blockedUsers: {
        name: "Moun ki bloke",
        desc: "Jere moun ou bloke yo. Ou ka debloke nenpòt moun nenpòt ki lè.",
      },
      dateSafetyCheckIn: {
        name: "Tchèk sekirite pou randevou",
        desc: "Pataje yon foto kote w ye ak yon moun ou fè konfyans anvan yon randevou, dirèkteman nan chat la.",
      },
      disappearingMessages: {
        name: "Mesaj ki disparèt",
        desc: "Limen efasman otomatik apre 24 èdtan pou yon konvèsasyon, nan meni opsyon chat la.",
      },
      inviteFriends: {
        name: "Envite zanmi",
        desc: "Pataje kòd referans ou: lè yon zanmi antre avè l, nou tou de jwenn 3 avi bonis.",
      },
      offersPerks: {
        name: "Òf ak avantaj",
        desc: "Òf biznis ak mak lokal ki fè patenarya ak Nearby.",
      },
      languages: {
        name: "11 lang",
        desc: "Chanje lang aplikasyon an nenpòt ki lè nan Paramèt.",
      },
    },
    title: "Tout sa ki nan Nearby",
    subtitle: "Yon ti referans rapid sou tout sa aplikasyon an ka fè: tape sou yon kategori pou wè sa ki ladan l.",
    collapseA11y: "{title}, tape pou fèmen",
    expandA11y: "{title}, tape pou louvri",
  },
  zh: {
    cat: {
      meeting: "认识新朋友",
      together: "经营一段真实的关系",
      growth: "为你准备",
      safety: "安全与信任",
      extras: "更多功能",
    },
    f: {
      crossedPaths: {
        name: "擦肩而过",
        desc: "找到人的主要方式：显示最近真正在你附近出现过的人（约 10 米内、几分钟前），而不是城里的任何人。",
      },
      noticesWaves: {
        name: "提醒与招手",
        desc: "提醒是悄悄的：只有对方也提醒你时才会知道。招手会立即告诉对方。两者都在“感兴趣”标签页里。",
      },
      browse: {
        name: "浏览",
        desc: "发现他人的可选第二种方式：不限距离，显示更多符合你筛选条件的人。可在“发现”的“人”模式中切换。",
      },
      gatherings: {
        name: "聚会",
        desc: "附近真实发生的活动，比如咖啡聚会、徒步、桌游之夜，由你附近的人发起。即使还没配对，也是认识新朋友的好方式。",
      },
      gatheringsMap: {
        name: "聚会地图",
        desc: "在地图上而不是列表中查看聚会。位置只显示大概，绝不会显示你的确切地址。",
      },
      ourConstitution: {
        name: "我们的约定",
        desc: "与配对对象共同写下的动态约定：如何处理冲突、做重大决定以及互相支持。",
      },
      timelineThoughts: {
        name: "节奏想法",
        desc: "分享对节奏和时间的期待，避免分歧变成摩擦。",
      },
      memoryVault: {
        name: "回忆库",
        desc: "共同保存值得纪念的小事：里程碑、只有你们懂的梗、有趣的瞬间。",
      },
      whatIf: {
        name: "如果……",
        desc: "通过假设情景，提前开启值得聊的真实话题。",
      },
      sharedPlaylist: {
        name: "共享歌单",
        desc: "和配对对象一起创建歌单。",
      },
      planATrip: {
        name: "计划旅行",
        desc: "一起构思目的地、活动和预算。",
      },
      bigPicture: {
        name: "长远规划",
        desc: "用于更重要话题的空间：居住安排、财务、家庭、长期规划。",
      },
      relationshipWisdom: {
        name: "感情智慧",
        desc: "阅读其他情侣选择分享的匿名感悟，或留下你自己的。",
      },
      rehearsalRoom: {
        name: "排练室",
        desc: "在真正开口前，先和 AI 角色扮演伙伴练习一场艰难的对话。这里不会永久保存任何内容，也不涉及真实的人。",
      },
      toolkit: {
        name: "工具箱",
        desc: "关于艰难对话、道歉、重建信任以及疏远后重新靠近的一般建议。",
      },
      chemistryDiary: {
        name: "化学反应日记",
        desc: "私密记录和某人相处的真实感受。久而久之，你会更真实地了解什么才真正让你舒服。",
      },
      privateReflections: {
        name: "私密感悟",
        desc: "私密记录你从一段关系中学到了什么，无论它如何结束。只有你能看到。",
      },
      helpMeSayIt: {
        name: "帮我说出口",
        desc: "不知道怎么说出难以启齿的话？直接在聊天中获得措辞帮助。",
      },
      idVerification: {
        name: "身份认证",
        desc: "认证身份后，资料上会显示徽章，别人筛选已认证资料时也能看到你。",
      },
      blockedUsers: {
        name: "已屏蔽的用户",
        desc: "管理你屏蔽的人，你随时可以解除屏蔽。",
      },
      dateSafetyCheckIn: {
        name: "约会安全报备",
        desc: "约会前，直接在聊天中与信任的联系人分享你的实时位置快照。",
      },
      disappearingMessages: {
        name: "阅后即焚消息",
        desc: "在聊天选项菜单中，为某个对话开启 24 小时自动删除。",
      },
      inviteFriends: {
        name: "邀请好友",
        desc: "分享你的邀请码：好友用它加入后，你们都能获得 3 次额外提醒。",
      },
      offersPerks: {
        name: "优惠与福利",
        desc: "与 Nearby 合作的本地商家和品牌提供的优惠。",
      },
      languages: {
        name: "11 种语言",
        desc: "随时可在设置中切换应用语言。",
      },
    },
    title: "Nearby 全部功能",
    subtitle: "快速了解应用的所有功能，点按分类即可查看详情。",
    collapseA11y: "{title}，点按收起",
    expandA11y: "{title}，点按展开",
  },
  vi: {
    cat: {
      meeting: "Gặp gỡ mọi người",
      together: "Xây dựng điều thật sự",
      growth: "Dành cho bạn",
      safety: "An toàn & tin cậy",
      extras: "Tiện ích thêm",
    },
    f: {
      crossedPaths: {
        name: "Đường Đời Giao Nhau",
        desc: "Cách chính để tìm người: cho bạn thấy ai thật sự ở gần bạn gần đây (khoảng 10 mét, vài phút trước), không phải bất kỳ ai trong thành phố.",
      },
      noticesWaves: {
        name: "Thông báo & vẫy tay",
        desc: "Thông báo là âm thầm: người kia chỉ biết khi họ cũng để ý bạn. Vẫy tay cho họ biết ngay. Cả hai nằm trong thẻ \"Quan tâm\".",
      },
      browse: {
        name: "Khám phá",
        desc: "Cách thứ hai (không bắt buộc) để khám phá mọi người: không giới hạn khoảng cách, cho thấy nhiều người hợp với bộ lọc hơn. Chuyển sang từ chế độ Mọi người trong Khám phá.",
      },
      gatherings: {
        name: "Buổi tụ họp",
        desc: "Những hoạt động thật đang diễn ra gần bạn, như hẹn cà phê, đi bộ đường dài, đêm trò chơi, do người quanh bạn tổ chức. Cách tuyệt vời để gặp gỡ ngay cả trước khi ghép đôi.",
      },
      gatheringsMap: {
        name: "Bản đồ tụ họp",
        desc: "Xem các buổi tụ họp trên bản đồ thay vì danh sách. Vị trí chỉ hiển thị gần đúng, không bao giờ là địa chỉ chính xác của bạn.",
      },
      ourConstitution: {
        name: "Hiến chương của chúng mình",
        desc: "Một thỏa thuận sống cùng người ghép đôi: cách xử lý mâu thuẫn, đưa ra quyết định lớn và hỗ trợ nhau, cùng nhau viết ra.",
      },
      timelineThoughts: {
        name: "Suy nghĩ về tiến độ",
        desc: "Không gian chia sẻ mong đợi về tốc độ và thời điểm, trước khi khác biệt thành va chạm.",
      },
      memoryVault: {
        name: "Kho kỷ niệm",
        desc: "Nơi chung để lưu những điều nhỏ đáng nhớ: cột mốc, chuyện đùa riêng, khoảnh khắc vui.",
      },
      whatIf: {
        name: "Nếu như...",
        desc: "Những tình huống giả định để mở ra các cuộc trò chuyện đáng có trước khi chúng thật sự xảy ra.",
      },
      sharedPlaylist: {
        name: "Danh sách phát chung",
        desc: "Cùng người ghép đôi tạo danh sách phát.",
      },
      planATrip: {
        name: "Lên kế hoạch chuyến đi",
        desc: "Cùng nhau lên ý tưởng điểm đến, hoạt động và ngân sách.",
      },
      bigPicture: {
        name: "Bức tranh lớn",
        desc: "Không gian cho những cuộc trò chuyện lớn hơn: chỗ ở, tài chính, gia đình, kế hoạch lâu dài.",
      },
      relationshipWisdom: {
        name: "Kinh nghiệm tình cảm",
        desc: "Đọc những chia sẻ ẩn danh mà các cặp đôi khác chọn đăng, hoặc để lại của bạn.",
      },
      rehearsalRoom: {
        name: "Phòng tập dượt",
        desc: "Luyện tập một cuộc trò chuyện khó với bạn nhập vai AI trước khi nói thật. Không có gì được lưu vĩnh viễn và không liên quan đến người thật.",
      },
      toolkit: {
        name: "Bộ công cụ",
        desc: "Hướng dẫn chung về những cuộc trò chuyện khó, xin lỗi, xây dựng lại niềm tin và kết nối lại sau khoảng cách.",
      },
      chemistryDiary: {
        name: "Nhật ký cảm xúc",
        desc: "Nhật ký riêng về cảm giác thật khi ở bên ai đó. Theo thời gian, bạn sẽ thấy rõ điều gì thật sự khiến mình dễ chịu.",
      },
      privateReflections: {
        name: "Suy ngẫm riêng tư",
        desc: "Nơi riêng tư để ghi lại điều bạn học được từ một mối kết nối, dù nó kết thúc thế nào. Chỉ mình bạn thấy.",
      },
      helpMeSayIt: {
        name: "Giúp mình nói ra",
        desc: "Khó nói điều gì đó? Nhận trợ giúp tìm từ ngữ ngay trong đoạn chat.",
      },
      idVerification: {
        name: "Xác minh danh tính",
        desc: "Xác minh danh tính để có huy hiệu trên hồ sơ và xuất hiện khi người khác lọc hồ sơ đã xác minh.",
      },
      blockedUsers: {
        name: "Người đã chặn",
        desc: "Quản lý những người bạn đã chặn. Bạn có thể bỏ chặn bất cứ ai, bất cứ lúc nào.",
      },
      dateSafetyCheckIn: {
        name: "Báo an toàn khi hẹn hò",
        desc: "Chia sẻ ảnh chụp vị trí hiện tại với người tin cậy trước buổi hẹn, ngay trong đoạn chat.",
      },
      disappearingMessages: {
        name: "Tin nhắn tự xóa",
        desc: "Bật tự xóa sau 24 giờ cho một cuộc trò chuyện, từ menu tùy chọn của chat.",
      },
      inviteFriends: {
        name: "Mời bạn bè",
        desc: "Chia sẻ mã giới thiệu: khi bạn bè tham gia bằng mã đó, cả hai đều nhận thêm 3 lượt thông báo.",
      },
      offersPerks: {
        name: "Ưu đãi & quyền lợi",
        desc: "Ưu đãi từ doanh nghiệp và thương hiệu địa phương hợp tác với Nearby.",
      },
      languages: {
        name: "11 ngôn ngữ",
        desc: "Đổi ngôn ngữ ứng dụng bất cứ lúc nào trong Cài đặt.",
      },
    },
    title: "Mọi thứ trong Nearby",
    subtitle: "Tổng quan nhanh mọi thứ ứng dụng làm được: chạm vào một danh mục để xem bên trong.",
    collapseA11y: "{title}, chạm để thu gọn",
    expandA11y: "{title}, chạm để mở rộng",
  },
  tl: {
    cat: {
      meeting: "Pagkilala sa mga tao",
      together: "Pagbuo ng totoong ugnayan",
      growth: "Para sa iyo",
      safety: "Kaligtasan at tiwala",
      extras: "Iba pa",
    },
    f: {
      crossedPaths: {
        name: "Nagkrus na Landas",
        desc: "Ang pangunahing paraan para makahanap ng tao: ipinapakita kung sino talaga ang napalapit sa iyo kamakailan (mga 35 talampakan, ilang minuto na ang nakalipas), hindi kung sinuman sa lungsod.",
      },
      noticesWaves: {
        name: "Mga abiso at Wave",
        desc: "Tahimik ang abiso: malalaman lang ng kabila kung mapansin ka rin nila. Agad namang sinasabi ng Wave. Pareho silang nasa tab na \"Interested\".",
      },
      browse: {
        name: "Browse",
        desc: "Opsyonal na pangalawang paraan para tumuklas ng mga tao: hindi limitado sa lapit, nagpapakita ng mas maraming tugma sa mga filter mo. Lumipat dito mula sa People mode ng Discover.",
      },
      gatherings: {
        name: "Mga gathering",
        desc: "Mga totoong nangyayari sa malapit, gaya ng coffee meetup, hike, at game night, na inoorganisa ng mga tao sa paligid mo. Magandang paraan para makakilala ng tao kahit bago pa mag-match.",
      },
      gatheringsMap: {
        name: "Mapa ng mga gathering",
        desc: "Tingnan ang mga gathering sa mapa sa halip na listahan. Tinatayang lokasyon lang ang ipinapakita, hindi kailanman ang eksaktong address mo.",
      },
      ourConstitution: {
        name: "Aming Konstitusyon",
        desc: "Isang buhay na kasunduan kasama ang match: kung paano ninyo haharapin ang away, gagawa ng malalaking desisyon, at susuportahan ang isa't isa, na isinulat nang magkasama.",
      },
      timelineThoughts: {
        name: "Mga iniisip sa takbo",
        desc: "Isang espasyo para ibahagi ang inaasahan sa bilis at timing, bago maging alitan ang di-pagkakatugma.",
      },
      memoryVault: {
        name: "Memory Vault",
        desc: "Isang shared na lugar para itabi ang maliliit na bagay na sulit alalahanin: milestone, inside joke, nakakatawang sandali.",
      },
      whatIf: {
        name: "Paano kung...",
        desc: "Mga hypothetical na sitwasyon para magsimula ng totoong usapan bago pa ito mangyari.",
      },
      sharedPlaylist: {
        name: "Shared playlist",
        desc: "Gumawa ng playlist kasama ang isang match.",
      },
      planATrip: {
        name: "Magplano ng biyahe",
        desc: "Mag-brainstorm nang magkasama ng destinasyon, aktibidad, at budget.",
      },
      bigPicture: {
        name: "Malaking larawan",
        desc: "Isang espasyo para sa mas malalaking usapan: tirahan, pera, pamilya, pangmatagalang plano.",
      },
      relationshipWisdom: {
        name: "Karunungan sa relasyon",
        desc: "Basahin ang mga anonymous na pagninilay na ibinahagi ng ibang magkapareha, o mag-iwan ng sa iyo.",
      },
      rehearsalRoom: {
        name: "Rehearsal Room",
        desc: "Magpraktis ng mahirap na usapan kasama ang AI role-play partner bago ito gawin nang totoo. Walang permanenteng nase-save at hindi ito tungkol sa totoong tao.",
      },
      toolkit: {
        name: "Toolkit",
        desc: "Pangkalahatang gabay sa mahihirap na usapan, paghingi ng tawad, muling pagbuo ng tiwala, at muling pagkonekta pagkatapos ng paglayo.",
      },
      chemistryDiary: {
        name: "Chemistry Diary",
        desc: "Isang pribadong tala kung ano talaga ang naramdaman mo kasama ang isang tao. Sa paglipas ng panahon, nabubuo ang tapat na larawan ng tunay na nagpapagaan ng loob mo.",
      },
      privateReflections: {
        name: "Pribadong pagninilay",
        desc: "Isang pribadong espasyo para isulat ang natutunan mo sa isang koneksyon, paano man ito natapos. Ikaw lang ang makakakita.",
      },
      helpMeSayIt: {
        name: "Tulungan akong sabihin",
        desc: "Hirap sabihin ang isang mahirap na bagay? Magpatulong sa paghahanap ng tamang salita, mismo sa chat.",
      },
      idVerification: {
        name: "ID verification",
        desc: "I-verify ang pagkakakilanlan mo para magkaroon ng badge sa profile at lumabas kapag nag-filter ang iba ng verified na profile.",
      },
      blockedUsers: {
        name: "Mga naka-block",
        desc: "Pamahalaan ang mga na-block mo. Puwede mong i-unblock ang sinuman anumang oras.",
      },
      dateSafetyCheckIn: {
        name: "Safety check-in sa date",
        desc: "Ibahagi ang snapshot ng lokasyon mo sa pinagkakatiwalaang contact bago ang date, mula sa chat.",
      },
      disappearingMessages: {
        name: "Nawawalang mensahe",
        desc: "I-on ang 24 na oras na auto-delete para sa isang usapan, mula sa options menu ng chat.",
      },
      inviteFriends: {
        name: "Mag-imbita ng kaibigan",
        desc: "Ibahagi ang referral code mo: kapag sumali ang kaibigan gamit ito, pareho kayong makakakuha ng 3 bonus na abiso.",
      },
      offersPerks: {
        name: "Mga alok at perk",
        desc: "Mga deal mula sa mga lokal na negosyo at brand na partner ng Nearby.",
      },
      languages: {
        name: "11 wika",
        desc: "Palitan ang wika ng app anumang oras sa Settings.",
      },
    },
    title: "Lahat ng nasa Nearby",
    subtitle: "Mabilisang gabay sa lahat ng kayang gawin ng app: i-tap ang isang kategorya para makita ang laman.",
    collapseA11y: "{title}, i-tap para i-collapse",
    expandA11y: "{title}, i-tap para i-expand",
  },
  ru: {
    cat: {
      meeting: "Знакомства",
      together: "Строим что-то настоящее",
      growth: "Для вас",
      safety: "Безопасность и доверие",
      extras: "Дополнительно",
    },
    f: {
      crossedPaths: {
        name: "Пересечённые Пути",
        desc: "Главный способ находить людей: показывает тех, кто недавно действительно был рядом (около 10 метров, несколько минут назад), а не кого угодно в городе.",
      },
      noticesWaves: {
        name: "Уведомления и взмахи",
        desc: "Уведомление тихое: человек узнает о нём, только если тоже заметит вас. Взмах сообщает сразу. И то и другое во вкладке «Интересуются».",
      },
      browse: {
        name: "Обзор",
        desc: "Необязательный второй способ находить людей: без ограничения по близости, показывает больше людей под ваши фильтры. Переключается в режиме «Люди» в разделе «Обзор».",
      },
      gatherings: {
        name: "Встречи",
        desc: "Настоящие события рядом: встречи за кофе, походы, вечера настольных игр, которые устраивают люди поблизости. Отличный способ познакомиться ещё до мэтча.",
      },
      gatheringsMap: {
        name: "Карта встреч",
        desc: "Смотрите встречи на карте вместо списка. Места показываются примерно, ваш точный адрес никогда.",
      },
      ourConstitution: {
        name: "Наша конституция",
        desc: "Живое соглашение с мэтчем: как вы решаете конфликты, принимаете важные решения и поддерживаете друг друга, написанное вместе.",
      },
      timelineThoughts: {
        name: "Мысли о темпе",
        desc: "Место, чтобы обсудить ожидания по темпу и срокам, пока несовпадения не стали трением.",
      },
      memoryVault: {
        name: "Хранилище воспоминаний",
        desc: "Общее место для мелочей, которые стоит помнить: важные моменты, свои шутки, забавные случаи.",
      },
      whatIf: {
        name: "Что если...",
        desc: "Гипотетические ситуации, чтобы начать важные разговоры заранее.",
      },
      sharedPlaylist: {
        name: "Общий плейлист",
        desc: "Собирайте плейлист вместе с мэтчем.",
      },
      planATrip: {
        name: "Спланировать поездку",
        desc: "Вместе придумывайте направления, занятия и бюджет.",
      },
      bigPicture: {
        name: "Главное",
        desc: "Место для больших разговоров: жильё, финансы, семья, долгосрочные планы.",
      },
      relationshipWisdom: {
        name: "Мудрость отношений",
        desc: "Читайте анонимные размышления, которыми поделились другие пары, или оставьте своё.",
      },
      rehearsalRoom: {
        name: "Репетиционная",
        desc: "Отрепетируйте трудный разговор с ИИ-партнёром по ролевой игре, прежде чем говорить по-настоящему. Ничего не сохраняется навсегда и не касается реальных людей.",
      },
      toolkit: {
        name: "Инструменты",
        desc: "Общие советы о трудных разговорах, извинениях, восстановлении доверия и сближении после отдаления.",
      },
      chemistryDiary: {
        name: "Дневник химии",
        desc: "Личный журнал о том, каково вам было с кем-то на самом деле. Со временем складывается честная картина того, что вам действительно подходит.",
      },
      privateReflections: {
        name: "Личные размышления",
        desc: "Личное место, чтобы записать, чему вас научила связь, как бы она ни закончилась. Видите только вы.",
      },
      helpMeSayIt: {
        name: "Помоги сказать",
        desc: "Трудно сказать что-то сложное? Помощь в подборе слов прямо в чате.",
      },
      idVerification: {
        name: "Проверка личности",
        desc: "Подтвердите личность, чтобы получить значок в профиле и появляться, когда другие фильтруют проверенные профили.",
      },
      blockedUsers: {
        name: "Заблокированные",
        desc: "Управляйте списком заблокированных. Разблокировать можно в любой момент.",
      },
      dateSafetyCheckIn: {
        name: "Проверка безопасности на свидании",
        desc: "Перед свиданием отправьте снимок своего местоположения доверенному контакту прямо из чата.",
      },
      disappearingMessages: {
        name: "Исчезающие сообщения",
        desc: "Включите автоудаление через 24 часа для конкретного чата в его меню.",
      },
      inviteFriends: {
        name: "Пригласить друзей",
        desc: "Поделитесь реферальным кодом: когда друг зарегистрируется с ним, вы оба получите 3 бонусных уведомления.",
      },
      offersPerks: {
        name: "Предложения и бонусы",
        desc: "Предложения от местных заведений и брендов, сотрудничающих с Nearby.",
      },
      languages: {
        name: "11 языков",
        desc: "Меняйте язык приложения в любое время в настройках.",
      },
    },
    title: "Всё в Nearby",
    subtitle: "Краткий обзор всего, что умеет приложение: нажмите на раздел, чтобы увидеть, что в нём.",
    collapseA11y: "{title}, нажмите, чтобы свернуть",
    expandA11y: "{title}, нажмите, чтобы развернуть",
  },
  ko: {
    cat: {
      meeting: "새로운 만남",
      together: "진지한 관계 만들기",
      growth: "나를 위해",
      safety: "안전 & 신뢰",
      extras: "기타 기능",
    },
    f: {
      crossedPaths: {
        name: "스쳐 지나간 인연",
        desc: "사람을 찾는 주된 방법이에요. 도시 아무나가 아니라 최근 실제로 가까이 있었던 사람(약 10미터, 몇 분 전)을 보여 줘요.",
      },
      noticesWaves: {
        name: "알림 & 웨이브",
        desc: "알림은 조용해요. 상대방도 나에게 관심을 보여야만 알게 돼요. 웨이브는 바로 알려 줘요. 둘 다 '관심' 탭에 있어요.",
      },
      browse: {
        name: "둘러보기",
        desc: "사람을 찾는 선택적인 두 번째 방법이에요. 거리와 상관없이 필터에 맞는 더 많은 사람을 보여 줘요. 탐색의 사람 모드에서 전환할 수 있어요.",
      },
      gatherings: {
        name: "모임",
        desc: "커피 모임, 하이킹, 보드게임의 밤처럼 근처 사람들이 여는 실제 모임이에요. 매칭 전에도 사람을 만나기 좋은 방법이에요.",
      },
      gatheringsMap: {
        name: "모임 지도",
        desc: "목록 대신 지도에서 모임을 볼 수 있어요. 위치는 대략적으로만 표시되고 정확한 주소는 절대 보이지 않아요.",
      },
      ourConstitution: {
        name: "우리의 약속",
        desc: "매칭 상대와 함께 쓰는 살아 있는 약속이에요. 갈등을 어떻게 다루고, 큰 결정을 어떻게 내리고, 서로를 어떻게 지지할지 정해요.",
      },
      timelineThoughts: {
        name: "속도에 대한 생각",
        desc: "속도와 시기에 대한 기대를 나누는 공간이에요. 엇갈림이 갈등이 되기 전에요.",
      },
      memoryVault: {
        name: "추억 보관함",
        desc: "기념할 만한 작은 것들을 함께 모아 두는 곳이에요. 중요한 순간, 둘만의 농담, 웃긴 순간들.",
      },
      whatIf: {
        name: "만약에...",
        desc: "실제로 일어나기 전에 나눠 볼 만한 대화를 끌어내는 가상 시나리오예요.",
      },
      sharedPlaylist: {
        name: "공유 플레이리스트",
        desc: "매칭 상대와 함께 플레이리스트를 만들어요.",
      },
      planATrip: {
        name: "여행 계획하기",
        desc: "여행지, 활동, 예산 아이디어를 함께 모아 봐요.",
      },
      bigPicture: {
        name: "큰 그림",
        desc: "주거, 재정, 가족, 장기 계획 같은 큰 대화를 나누는 공간이에요.",
      },
      relationshipWisdom: {
        name: "관계의 지혜",
        desc: "다른 커플이 공유한 익명의 이야기를 읽거나 내 이야기를 남겨 보세요.",
      },
      rehearsalRoom: {
        name: "연습실",
        desc: "실제로 말하기 전에 AI 역할극 상대와 어려운 대화를 연습해 보세요. 영구 저장되지 않으며 실제 인물에 관한 것도 아니에요.",
      },
      toolkit: {
        name: "도구 모음",
        desc: "어려운 대화, 사과, 신뢰 회복, 멀어진 뒤 다시 가까워지기에 대한 일반적인 안내예요.",
      },
      chemistryDiary: {
        name: "케미 일기",
        desc: "누군가와 보낸 시간이 실제로 어땠는지 적는 개인 기록이에요. 시간이 지나면 나에게 정말 잘 맞는 게 무엇인지 솔직하게 보여 줘요.",
      },
      privateReflections: {
        name: "나만의 회고",
        desc: "어떻게 끝났든 한 인연에서 배운 것을 적는 개인 공간이에요. 나만 볼 수 있어요.",
      },
      helpMeSayIt: {
        name: "말하기 도우미",
        desc: "하기 어려운 말이 있나요? 채팅에서 바로 표현을 찾는 도움을 받아 보세요.",
      },
      idVerification: {
        name: "신원 인증",
        desc: "신원을 인증하면 프로필에 배지가 생기고, 인증된 프로필만 보는 사람에게도 표시돼요.",
      },
      blockedUsers: {
        name: "차단한 사용자",
        desc: "차단한 사람을 관리해요. 언제든지 차단을 해제할 수 있어요.",
      },
      dateSafetyCheckIn: {
        name: "데이트 안전 체크인",
        desc: "데이트 전에 채팅에서 믿을 수 있는 연락처에 현재 위치를 공유해요.",
      },
      disappearingMessages: {
        name: "사라지는 메시지",
        desc: "채팅 옵션 메뉴에서 특정 대화에 24시간 자동 삭제를 켤 수 있어요.",
      },
      inviteFriends: {
        name: "친구 초대",
        desc: "추천 코드를 공유하세요. 친구가 그 코드로 가입하면 둘 다 알림 3개를 추가로 받아요.",
      },
      offersPerks: {
        name: "혜택 & 특전",
        desc: "Nearby와 제휴한 지역 업체와 브랜드의 혜택이에요.",
      },
      languages: {
        name: "11개 언어",
        desc: "설정에서 언제든지 앱 언어를 바꿀 수 있어요.",
      },
    },
    title: "Nearby의 모든 기능",
    subtitle: "앱의 모든 기능을 빠르게 살펴보세요. 카테고리를 누르면 내용을 볼 수 있어요.",
    collapseA11y: "{title}, 눌러서 접기",
    expandA11y: "{title}, 눌러서 펼치기",
  },
};
