// Option labels for the gathering fields shared by Create and Edit (localization pass 5). Keys = the stored values of the
// source lists (whenPresets, gatheringPractical, activityFormat, skillLevel, intensityEffort, CreateGathering's plan kinds and
// capacity buckets); gatheringOptions.test.js keeps them equal. Display only. Machine-authored outside English; needs review.
// Generated by scripts/i18n/gen-gathering-options.py -- edit there, not here.
export default {
  "en": {
    "notSpecified": "Not specified",
    "free": "Free",
    "when": {
      "now": "Now",
      "tonight": "Tonight",
      "tomorrow": "Tomorrow",
      "custom": "Pick a Date"
    },
    "repeat": {
      "none": "Doesn't repeat",
      "weekly": "Weekly",
      "biweekly": "Every 2 weeks",
      "monthly": "Monthly"
    },
    "kind": {
      "friends": "👥 Friends / casual hangout",
      "date": "💕 Date",
      "family": "👨‍👩‍👧 Family",
      "coworkers": "💼 Networking / work",
      "new_people": "🤝 Meet new people",
      "groups": "👨‍👩‍👧‍👦 Big group",
      "solo": "🧍 Solo-friendly"
    },
    "capacity": {
      "no_limit": "No Limit",
      "2-4": "2-4 people",
      "5-10": "5-10 people",
      "10+": "10+ people"
    },
    "feature": {
      "wheelchair_accessible": "Wheelchair accessible",
      "accessible_parking": "Accessible parking",
      "accessible_restroom": "Accessible restroom",
      "service_animal_friendly": "Service animal friendly",
      "quiet": "Quiet environment",
      "kid_friendly": "Kids welcome",
      "stroller_friendly": "Stroller friendly",
      "family_seating": "Family seating",
      "outdoor_seating": "Outdoor seating",
      "pet_friendly": "Pets welcome",
      "dog_friendly": "Dogs welcome"
    },
    "equipment": {
      "provided": "Equipment provided",
      "byo": "Bring your own"
    },
    "duration": {
      "30": "30 min",
      "60": "1 hr",
      "90": "1.5 hr",
      "120": "2 hr",
      "180": "3 hr"
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Country",
      "hip_hop": "Hip-Hop",
      "electronic": "Electronic",
      "techno": "Techno",
      "classical": "Classical",
      "folk": "Folk",
      "latin": "Latin",
      "r_and_b": "R&B",
      "open_mic": "Open Mic"
    },
    "format": {
      "drop_in": "Drop-in",
      "class": "Class",
      "tournament": "Tournament",
      "meetup": "Meetup",
      "concert": "Concert",
      "show": "Show",
      "festival": "Festival",
      "tour": "Tour",
      "workshop": "Workshop",
      "appointment": "Appointment",
      "reservation": "Reservation",
      "open_play": "Open play",
      "competition": "Competition",
      "exhibition": "Exhibition",
      "market": "Market",
      "party": "Party"
    },
    "skill": {
      "beginner": "Beginner",
      "intermediate": "Intermediate",
      "advanced": "Advanced",
      "all_levels": "All levels",
      "casual": "Casual",
      "competitive": "Competitive"
    },
    "effort": {
      "light": "Light",
      "moderate": "Moderate",
      "challenging": "Challenging"
    }
  },
  "es": {
    "notSpecified": "Sin especificar",
    "free": "Gratis",
    "when": {
      "now": "Ahora",
      "tonight": "Esta noche",
      "tomorrow": "Mañana",
      "custom": "Elegir fecha"
    },
    "repeat": {
      "none": "No se repite",
      "weekly": "Cada semana",
      "biweekly": "Cada 2 semanas",
      "monthly": "Cada mes"
    },
    "kind": {
      "friends": "👥 Amigos / plan casual",
      "date": "💕 Cita",
      "family": "👨‍👩‍👧 Familia",
      "coworkers": "💼 Networking / trabajo",
      "new_people": "🤝 Conocer gente nueva",
      "groups": "👨‍👩‍👧‍👦 Grupo grande",
      "solo": "🧍 Para ir solo"
    },
    "capacity": {
      "no_limit": "Sin límite",
      "2-4": "2-4 personas",
      "5-10": "5-10 personas",
      "10+": "10+ personas"
    },
    "feature": {
      "wheelchair_accessible": "Accesible en silla de ruedas",
      "accessible_parking": "Estacionamiento accesible",
      "accessible_restroom": "Baño accesible",
      "service_animal_friendly": "Se admiten animales de servicio",
      "quiet": "Ambiente tranquilo",
      "kid_friendly": "Niños bienvenidos",
      "stroller_friendly": "Apto para carriolas",
      "family_seating": "Mesas para familias",
      "outdoor_seating": "Mesas al aire libre",
      "pet_friendly": "Se admiten mascotas",
      "dog_friendly": "Se admiten perros"
    },
    "equipment": {
      "provided": "Se incluye el equipo",
      "byo": "Trae el tuyo"
    },
    "duration": {
      "30": "30 min",
      "60": "1 h",
      "90": "1,5 h",
      "120": "2 h",
      "180": "3 h"
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Country",
      "hip_hop": "Hip-hop",
      "electronic": "Electrónica",
      "techno": "Techno",
      "classical": "Clásica",
      "folk": "Folk",
      "latin": "Latina",
      "r_and_b": "R&B",
      "open_mic": "Micrófono abierto"
    },
    "format": {
      "drop_in": "Llega cuando quieras",
      "class": "Clase",
      "tournament": "Torneo",
      "meetup": "Encuentro",
      "concert": "Concierto",
      "show": "Espectáculo",
      "festival": "Festival",
      "tour": "Recorrido",
      "workshop": "Taller",
      "appointment": "Cita",
      "reservation": "Reserva",
      "open_play": "Juego libre",
      "competition": "Competencia",
      "exhibition": "Exposición",
      "market": "Mercado",
      "party": "Fiesta"
    },
    "skill": {
      "beginner": "Principiante",
      "intermediate": "Intermedio",
      "advanced": "Avanzado",
      "all_levels": "Todos los niveles",
      "casual": "Casual",
      "competitive": "Competitivo"
    },
    "effort": {
      "light": "Ligero",
      "moderate": "Moderado",
      "challenging": "Exigente"
    }
  },
  "de": {
    "notSpecified": "Keine Angabe",
    "free": "Kostenlos",
    "when": {
      "now": "Jetzt",
      "tonight": "Heute Abend",
      "tomorrow": "Morgen",
      "custom": "Datum wählen"
    },
    "repeat": {
      "none": "Wiederholt sich nicht",
      "weekly": "Wöchentlich",
      "biweekly": "Alle 2 Wochen",
      "monthly": "Monatlich"
    },
    "kind": {
      "friends": "👥 Freunde / lockeres Treffen",
      "date": "💕 Date",
      "family": "👨‍👩‍👧 Familie",
      "coworkers": "💼 Networking / Arbeit",
      "new_people": "🤝 Neue Leute kennenlernen",
      "groups": "👨‍👩‍👧‍👦 Große Gruppe",
      "solo": "🧍 Auch allein"
    },
    "capacity": {
      "no_limit": "Keine Grenze",
      "2-4": "2-4 Personen",
      "5-10": "5-10 Personen",
      "10+": "10+ Personen"
    },
    "feature": {
      "wheelchair_accessible": "Rollstuhlgerecht",
      "accessible_parking": "Behindertenparkplatz",
      "accessible_restroom": "Barrierefreie Toilette",
      "service_animal_friendly": "Assistenztiere willkommen",
      "quiet": "Ruhige Umgebung",
      "kid_friendly": "Kinder willkommen",
      "stroller_friendly": "Kinderwagenfreundlich",
      "family_seating": "Familienplätze",
      "outdoor_seating": "Sitzplätze draußen",
      "pet_friendly": "Haustiere willkommen",
      "dog_friendly": "Hunde willkommen"
    },
    "equipment": {
      "provided": "Ausrüstung wird gestellt",
      "byo": "Selbst mitbringen"
    },
    "duration": {
      "30": "30 Min.",
      "60": "1 Std.",
      "90": "1,5 Std.",
      "120": "2 Std.",
      "180": "3 Std."
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Country",
      "hip_hop": "Hip-Hop",
      "electronic": "Elektronisch",
      "techno": "Techno",
      "classical": "Klassik",
      "folk": "Folk",
      "latin": "Latin",
      "r_and_b": "R&B",
      "open_mic": "Open Mic"
    },
    "format": {
      "drop_in": "Offen für alle",
      "class": "Kurs",
      "tournament": "Turnier",
      "meetup": "Meetup",
      "concert": "Konzert",
      "show": "Show",
      "festival": "Festival",
      "tour": "Führung",
      "workshop": "Workshop",
      "appointment": "Termin",
      "reservation": "Reservierung",
      "open_play": "Freies Spiel",
      "competition": "Wettbewerb",
      "exhibition": "Ausstellung",
      "market": "Markt",
      "party": "Party"
    },
    "skill": {
      "beginner": "Anfänger",
      "intermediate": "Fortgeschritten",
      "advanced": "Experte",
      "all_levels": "Alle Niveaus",
      "casual": "Locker",
      "competitive": "Wettkampf"
    },
    "effort": {
      "light": "Leicht",
      "moderate": "Mittel",
      "challenging": "Anspruchsvoll"
    }
  },
  "fr": {
    "notSpecified": "Non précisé",
    "free": "Gratuit",
    "when": {
      "now": "Maintenant",
      "tonight": "Ce soir",
      "tomorrow": "Demain",
      "custom": "Choisir une date"
    },
    "repeat": {
      "none": "Ne se répète pas",
      "weekly": "Chaque semaine",
      "biweekly": "Toutes les 2 semaines",
      "monthly": "Chaque mois"
    },
    "kind": {
      "friends": "👥 Amis / moment détente",
      "date": "💕 Rendez-vous",
      "family": "👨‍👩‍👧 Famille",
      "coworkers": "💼 Réseautage / travail",
      "new_people": "🤝 Rencontrer du monde",
      "groups": "👨‍👩‍👧‍👦 Grand groupe",
      "solo": "🧍 Seul, c’est bien aussi"
    },
    "capacity": {
      "no_limit": "Sans limite",
      "2-4": "2 à 4 personnes",
      "5-10": "5 à 10 personnes",
      "10+": "10 personnes et plus"
    },
    "feature": {
      "wheelchair_accessible": "Accessible en fauteuil roulant",
      "accessible_parking": "Stationnement accessible",
      "accessible_restroom": "Toilettes accessibles",
      "service_animal_friendly": "Animaux d’assistance acceptés",
      "quiet": "Environnement calme",
      "kid_friendly": "Enfants bienvenus",
      "stroller_friendly": "Accessible en poussette",
      "family_seating": "Places pour les familles",
      "outdoor_seating": "Places en extérieur",
      "pet_friendly": "Animaux bienvenus",
      "dog_friendly": "Chiens bienvenus"
    },
    "equipment": {
      "provided": "Équipement fourni",
      "byo": "Apportez le vôtre"
    },
    "duration": {
      "30": "30 min",
      "60": "1 h",
      "90": "1 h 30",
      "120": "2 h",
      "180": "3 h"
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Country",
      "hip_hop": "Hip-hop",
      "electronic": "Électronique",
      "techno": "Techno",
      "classical": "Classique",
      "folk": "Folk",
      "latin": "Latino",
      "r_and_b": "R&B",
      "open_mic": "Scène ouverte"
    },
    "format": {
      "drop_in": "Passage libre",
      "class": "Cours",
      "tournament": "Tournoi",
      "meetup": "Rencontre",
      "concert": "Concert",
      "show": "Spectacle",
      "festival": "Festival",
      "tour": "Visite",
      "workshop": "Atelier",
      "appointment": "Rendez-vous",
      "reservation": "Réservation",
      "open_play": "Jeu libre",
      "competition": "Compétition",
      "exhibition": "Exposition",
      "market": "Marché",
      "party": "Fête"
    },
    "skill": {
      "beginner": "Débutant",
      "intermediate": "Intermédiaire",
      "advanced": "Avancé",
      "all_levels": "Tous niveaux",
      "casual": "Détente",
      "competitive": "Compétitif"
    },
    "effort": {
      "light": "Léger",
      "moderate": "Modéré",
      "challenging": "Exigeant"
    }
  },
  "pt": {
    "notSpecified": "Não especificado",
    "free": "Grátis",
    "when": {
      "now": "Agora",
      "tonight": "Hoje à noite",
      "tomorrow": "Amanhã",
      "custom": "Escolher data"
    },
    "repeat": {
      "none": "Não se repete",
      "weekly": "Semanal",
      "biweekly": "A cada 2 semanas",
      "monthly": "Mensal"
    },
    "kind": {
      "friends": "👥 Amigos / encontro casual",
      "date": "💕 Encontro romântico",
      "family": "👨‍👩‍👧 Família",
      "coworkers": "💼 Networking / trabalho",
      "new_people": "🤝 Conhecer gente nova",
      "groups": "👨‍👩‍👧‍👦 Grupo grande",
      "solo": "🧍 Dá para ir sozinho"
    },
    "capacity": {
      "no_limit": "Sem limite",
      "2-4": "2-4 pessoas",
      "5-10": "5-10 pessoas",
      "10+": "10+ pessoas"
    },
    "feature": {
      "wheelchair_accessible": "Acessível para cadeira de rodas",
      "accessible_parking": "Estacionamento acessível",
      "accessible_restroom": "Banheiro acessível",
      "service_animal_friendly": "Aceita animais de serviço",
      "quiet": "Ambiente tranquilo",
      "kid_friendly": "Crianças bem-vindas",
      "stroller_friendly": "Acessível para carrinho de bebê",
      "family_seating": "Lugares para famílias",
      "outdoor_seating": "Mesas ao ar livre",
      "pet_friendly": "Animais bem-vindos",
      "dog_friendly": "Cães bem-vindos"
    },
    "equipment": {
      "provided": "Equipamento fornecido",
      "byo": "Traga o seu"
    },
    "duration": {
      "30": "30 min",
      "60": "1 h",
      "90": "1,5 h",
      "120": "2 h",
      "180": "3 h"
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Country",
      "hip_hop": "Hip-hop",
      "electronic": "Eletrônica",
      "techno": "Techno",
      "classical": "Clássica",
      "folk": "Folk",
      "latin": "Latina",
      "r_and_b": "R&B",
      "open_mic": "Microfone aberto"
    },
    "format": {
      "drop_in": "Passe quando quiser",
      "class": "Aula",
      "tournament": "Torneio",
      "meetup": "Encontro",
      "concert": "Show",
      "show": "Espetáculo",
      "festival": "Festival",
      "tour": "Passeio guiado",
      "workshop": "Oficina",
      "appointment": "Horário marcado",
      "reservation": "Reserva",
      "open_play": "Jogo livre",
      "competition": "Competição",
      "exhibition": "Exposição",
      "market": "Feira",
      "party": "Festa"
    },
    "skill": {
      "beginner": "Iniciante",
      "intermediate": "Intermediário",
      "advanced": "Avançado",
      "all_levels": "Todos os níveis",
      "casual": "Casual",
      "competitive": "Competitivo"
    },
    "effort": {
      "light": "Leve",
      "moderate": "Moderado",
      "challenging": "Desafiador"
    }
  },
  "ht": {
    "notSpecified": "Pa presize",
    "free": "Gratis",
    "when": {
      "now": "Kounye a",
      "tonight": "Aswè a",
      "tomorrow": "Demen",
      "custom": "Chwazi yon dat"
    },
    "repeat": {
      "none": "Pa repete",
      "weekly": "Chak semèn",
      "biweekly": "Chak 2 semèn",
      "monthly": "Chak mwa"
    },
    "kind": {
      "friends": "👥 Zanmi / rankont tou senp",
      "date": "💕 Randevou",
      "family": "👨‍👩‍👧 Fanmi",
      "coworkers": "💼 Rezo / travay",
      "new_people": "🤝 Rankontre nouvo moun",
      "groups": "👨‍👩‍👧‍👦 Gwo gwoup",
      "solo": "🧍 Bon pou ale pou kont ou"
    },
    "capacity": {
      "no_limit": "San limit",
      "2-4": "2-4 moun",
      "5-10": "5-10 moun",
      "10+": "10+ moun"
    },
    "feature": {
      "wheelchair_accessible": "Aksesib pou chèz woulant",
      "accessible_parking": "Pakin aksesib",
      "accessible_restroom": "Twalèt aksesib",
      "service_animal_friendly": "Bèt sèvis akseptab",
      "quiet": "Anviwònman trankil",
      "kid_friendly": "Timoun byenveni",
      "stroller_friendly": "Bon pou pousèt",
      "family_seating": "Plas pou fanmi",
      "outdoor_seating": "Plas deyò",
      "pet_friendly": "Bèt kay akseptab",
      "dog_friendly": "Chen akseptab"
    },
    "equipment": {
      "provided": "Yo bay ekipman",
      "byo": "Pote pa w"
    },
    "duration": {
      "30": "30 min",
      "60": "1 è",
      "90": "1,5 è",
      "120": "2 è",
      "180": "3 è"
    },
    "genre": {
      "rock": "Wòk",
      "pop": "Pòp",
      "jazz": "Djaz",
      "blues": "Blouz",
      "country": "Country",
      "hip_hop": "Hip-hop",
      "electronic": "Elektwonik",
      "techno": "Tekno",
      "classical": "Klasik",
      "folk": "Folk",
      "latin": "Laten",
      "r_and_b": "R&B",
      "open_mic": "Mikwo louvri"
    },
    "format": {
      "drop_in": "Vin lè w vle",
      "class": "Kou",
      "tournament": "Tounwa",
      "meetup": "Rankont",
      "concert": "Konsè",
      "show": "Espektak",
      "festival": "Festival",
      "tour": "Vizit",
      "workshop": "Atelye",
      "appointment": "Randevou",
      "reservation": "Rezèvasyon",
      "open_play": "Jwe lib",
      "competition": "Konpetisyon",
      "exhibition": "Ekspozisyon",
      "market": "Mache",
      "party": "Fèt"
    },
    "skill": {
      "beginner": "Debitan",
      "intermediate": "Mwayen",
      "advanced": "Avanse",
      "all_levels": "Tout nivo",
      "casual": "Pou plezi",
      "competitive": "Konpetitif"
    },
    "effort": {
      "light": "Lejè",
      "moderate": "Mwayen",
      "challenging": "Difisil"
    }
  },
  "zh": {
    "notSpecified": "未指定",
    "free": "免费",
    "when": {
      "now": "现在",
      "tonight": "今晚",
      "tomorrow": "明天",
      "custom": "选择日期"
    },
    "repeat": {
      "none": "不重复",
      "weekly": "每周",
      "biweekly": "每两周",
      "monthly": "每月"
    },
    "kind": {
      "friends": "👥 朋友 / 轻松小聚",
      "date": "💕 约会",
      "family": "👨‍👩‍👧 家庭",
      "coworkers": "💼 社交 / 工作",
      "new_people": "🤝 认识新朋友",
      "groups": "👨‍👩‍👧‍👦 大团体",
      "solo": "🧍 适合独自参加"
    },
    "capacity": {
      "no_limit": "不限人数",
      "2-4": "2-4 人",
      "5-10": "5-10 人",
      "10+": "10 人以上"
    },
    "feature": {
      "wheelchair_accessible": "无障碍轮椅通行",
      "accessible_parking": "无障碍停车位",
      "accessible_restroom": "无障碍洗手间",
      "service_animal_friendly": "可带服务动物",
      "quiet": "安静的环境",
      "kid_friendly": "欢迎儿童",
      "stroller_friendly": "方便婴儿车",
      "family_seating": "家庭座位",
      "outdoor_seating": "户外座位",
      "pet_friendly": "欢迎携带宠物",
      "dog_friendly": "欢迎携带狗狗"
    },
    "equipment": {
      "provided": "提供装备",
      "byo": "自带"
    },
    "duration": {
      "30": "30 分钟",
      "60": "1 小时",
      "90": "1.5 小时",
      "120": "2 小时",
      "180": "3 小时"
    },
    "genre": {
      "rock": "摇滚",
      "pop": "流行",
      "jazz": "爵士",
      "blues": "蓝调",
      "country": "乡村",
      "hip_hop": "嘻哈",
      "electronic": "电子",
      "techno": "Techno",
      "classical": "古典",
      "folk": "民谣",
      "latin": "拉丁",
      "r_and_b": "节奏布鲁斯",
      "open_mic": "开放麦"
    },
    "format": {
      "drop_in": "随到随参加",
      "class": "课程",
      "tournament": "锦标赛",
      "meetup": "见面会",
      "concert": "音乐会",
      "show": "演出",
      "festival": "节日活动",
      "tour": "导览",
      "workshop": "工作坊",
      "appointment": "预约",
      "reservation": "订位",
      "open_play": "自由参与",
      "competition": "比赛",
      "exhibition": "展览",
      "market": "市集",
      "party": "派对"
    },
    "skill": {
      "beginner": "初学者",
      "intermediate": "中级",
      "advanced": "高级",
      "all_levels": "所有水平",
      "casual": "休闲",
      "competitive": "竞技"
    },
    "effort": {
      "light": "轻松",
      "moderate": "适中",
      "challenging": "有挑战"
    }
  },
  "vi": {
    "notSpecified": "Chưa xác định",
    "free": "Miễn phí",
    "when": {
      "now": "Bây giờ",
      "tonight": "Tối nay",
      "tomorrow": "Ngày mai",
      "custom": "Chọn ngày"
    },
    "repeat": {
      "none": "Không lặp lại",
      "weekly": "Hằng tuần",
      "biweekly": "Mỗi 2 tuần",
      "monthly": "Hằng tháng"
    },
    "kind": {
      "friends": "👥 Bạn bè / gặp gỡ thoải mái",
      "date": "💕 Hẹn hò",
      "family": "👨‍👩‍👧 Gia đình",
      "coworkers": "💼 Kết nối / công việc",
      "new_people": "🤝 Làm quen người mới",
      "groups": "👨‍👩‍👧‍👦 Nhóm đông",
      "solo": "🧍 Đi một mình cũng được"
    },
    "capacity": {
      "no_limit": "Không giới hạn",
      "2-4": "2-4 người",
      "5-10": "5-10 người",
      "10+": "10+ người"
    },
    "feature": {
      "wheelchair_accessible": "Có lối cho xe lăn",
      "accessible_parking": "Chỗ đậu xe cho người khuyết tật",
      "accessible_restroom": "Nhà vệ sinh cho người khuyết tật",
      "service_animal_friendly": "Chấp nhận động vật hỗ trợ",
      "quiet": "Không gian yên tĩnh",
      "kid_friendly": "Chào đón trẻ em",
      "stroller_friendly": "Thuận tiện xe đẩy",
      "family_seating": "Chỗ ngồi gia đình",
      "outdoor_seating": "Chỗ ngồi ngoài trời",
      "pet_friendly": "Chào đón thú cưng",
      "dog_friendly": "Chào đón chó"
    },
    "equipment": {
      "provided": "Có cung cấp dụng cụ",
      "byo": "Tự mang theo"
    },
    "duration": {
      "30": "30 phút",
      "60": "1 giờ",
      "90": "1,5 giờ",
      "120": "2 giờ",
      "180": "3 giờ"
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Đồng quê",
      "hip_hop": "Hip-hop",
      "electronic": "Điện tử",
      "techno": "Techno",
      "classical": "Cổ điển",
      "folk": "Dân gian",
      "latin": "Latin",
      "r_and_b": "R&B",
      "open_mic": "Open Mic"
    },
    "format": {
      "drop_in": "Ghé lúc nào cũng được",
      "class": "Lớp học",
      "tournament": "Giải đấu",
      "meetup": "Buổi gặp gỡ",
      "concert": "Hòa nhạc",
      "show": "Buổi biểu diễn",
      "festival": "Lễ hội",
      "tour": "Tham quan",
      "workshop": "Hội thảo thực hành",
      "appointment": "Lịch hẹn",
      "reservation": "Đặt chỗ",
      "open_play": "Chơi tự do",
      "competition": "Cuộc thi",
      "exhibition": "Triển lãm",
      "market": "Chợ phiên",
      "party": "Tiệc"
    },
    "skill": {
      "beginner": "Người mới",
      "intermediate": "Trung cấp",
      "advanced": "Nâng cao",
      "all_levels": "Mọi trình độ",
      "casual": "Vui là chính",
      "competitive": "Thi đấu"
    },
    "effort": {
      "light": "Nhẹ",
      "moderate": "Vừa phải",
      "challenging": "Thử thách"
    }
  },
  "tl": {
    "notSpecified": "Hindi tinukoy",
    "free": "Libre",
    "when": {
      "now": "Ngayon",
      "tonight": "Mamayang gabi",
      "tomorrow": "Bukas",
      "custom": "Pumili ng Petsa"
    },
    "repeat": {
      "none": "Hindi umuulit",
      "weekly": "Lingguhan",
      "biweekly": "Tuwing 2 linggo",
      "monthly": "Buwanan"
    },
    "kind": {
      "friends": "👥 Mga kaibigan / tambayan",
      "date": "💕 Date",
      "family": "👨‍👩‍👧 Pamilya",
      "coworkers": "💼 Networking / trabaho",
      "new_people": "🤝 Makakilala ng bagong tao",
      "groups": "👨‍👩‍👧‍👦 Malaking grupo",
      "solo": "🧍 Puwedeng mag-isa"
    },
    "capacity": {
      "no_limit": "Walang limit",
      "2-4": "2-4 tao",
      "5-10": "5-10 tao",
      "10+": "10+ tao"
    },
    "feature": {
      "wheelchair_accessible": "Accessible sa wheelchair",
      "accessible_parking": "Accessible na paradahan",
      "accessible_restroom": "Accessible na banyo",
      "service_animal_friendly": "Puwede ang service animal",
      "quiet": "Tahimik na lugar",
      "kid_friendly": "Welcome ang mga bata",
      "stroller_friendly": "Puwede ang stroller",
      "family_seating": "Upuan para sa pamilya",
      "outdoor_seating": "Upuan sa labas",
      "pet_friendly": "Welcome ang mga alagang hayop",
      "dog_friendly": "Welcome ang mga aso"
    },
    "equipment": {
      "provided": "May ibibigay na gamit",
      "byo": "Magdala ng sarili"
    },
    "duration": {
      "30": "30 min",
      "60": "1 oras",
      "90": "1.5 oras",
      "120": "2 oras",
      "180": "3 oras"
    },
    "genre": {
      "rock": "Rock",
      "pop": "Pop",
      "jazz": "Jazz",
      "blues": "Blues",
      "country": "Country",
      "hip_hop": "Hip-Hop",
      "electronic": "Electronic",
      "techno": "Techno",
      "classical": "Classical",
      "folk": "Folk",
      "latin": "Latin",
      "r_and_b": "R&B",
      "open_mic": "Open Mic"
    },
    "format": {
      "drop_in": "Drop-in",
      "class": "Klase",
      "tournament": "Torneo",
      "meetup": "Meetup",
      "concert": "Konsiyerto",
      "show": "Palabas",
      "festival": "Pista",
      "tour": "Tour",
      "workshop": "Workshop",
      "appointment": "Appointment",
      "reservation": "Reserbasyon",
      "open_play": "Open play",
      "competition": "Kompetisyon",
      "exhibition": "Eksibisyon",
      "market": "Palengke",
      "party": "Party"
    },
    "skill": {
      "beginner": "Baguhan",
      "intermediate": "Intermediate",
      "advanced": "Advanced",
      "all_levels": "Lahat ng antas",
      "casual": "Casual",
      "competitive": "Competitive"
    },
    "effort": {
      "light": "Magaan",
      "moderate": "Katamtaman",
      "challenging": "Mahirap"
    }
  },
  "ru": {
    "notSpecified": "Не указано",
    "free": "Бесплатно",
    "when": {
      "now": "Сейчас",
      "tonight": "Сегодня вечером",
      "tomorrow": "Завтра",
      "custom": "Выбрать дату"
    },
    "repeat": {
      "none": "Не повторяется",
      "weekly": "Каждую неделю",
      "biweekly": "Раз в 2 недели",
      "monthly": "Каждый месяц"
    },
    "kind": {
      "friends": "👥 Друзья / просто посидеть",
      "date": "💕 Свидание",
      "family": "👨‍👩‍👧 Семья",
      "coworkers": "💼 Нетворкинг / работа",
      "new_people": "🤝 Новые знакомства",
      "groups": "👨‍👩‍👧‍👦 Большая компания",
      "solo": "🧍 Можно одному"
    },
    "capacity": {
      "no_limit": "Без ограничений",
      "2-4": "2-4 человека",
      "5-10": "5-10 человек",
      "10+": "10+ человек"
    },
    "feature": {
      "wheelchair_accessible": "Доступно для колясок",
      "accessible_parking": "Доступная парковка",
      "accessible_restroom": "Доступный туалет",
      "service_animal_friendly": "Можно с собакой-помощником",
      "quiet": "Тихая обстановка",
      "kid_friendly": "Можно с детьми",
      "stroller_friendly": "Удобно с коляской",
      "family_seating": "Места для семей",
      "outdoor_seating": "Места на улице",
      "pet_friendly": "Можно с питомцами",
      "dog_friendly": "Можно с собаками"
    },
    "equipment": {
      "provided": "Снаряжение предоставляется",
      "byo": "Приносите своё"
    },
    "duration": {
      "30": "30 мин",
      "60": "1 ч",
      "90": "1,5 ч",
      "120": "2 ч",
      "180": "3 ч"
    },
    "genre": {
      "rock": "Рок",
      "pop": "Поп",
      "jazz": "Джаз",
      "blues": "Блюз",
      "country": "Кантри",
      "hip_hop": "Хип-хоп",
      "electronic": "Электроника",
      "techno": "Техно",
      "classical": "Классика",
      "folk": "Фолк",
      "latin": "Латино",
      "r_and_b": "R&B",
      "open_mic": "Открытый микрофон"
    },
    "format": {
      "drop_in": "Свободный вход",
      "class": "Занятие",
      "tournament": "Турнир",
      "meetup": "Встреча",
      "concert": "Концерт",
      "show": "Шоу",
      "festival": "Фестиваль",
      "tour": "Экскурсия",
      "workshop": "Мастер-класс",
      "appointment": "Запись",
      "reservation": "Бронирование",
      "open_play": "Свободная игра",
      "competition": "Соревнование",
      "exhibition": "Выставка",
      "market": "Рынок",
      "party": "Вечеринка"
    },
    "skill": {
      "beginner": "Новичок",
      "intermediate": "Средний",
      "advanced": "Продвинутый",
      "all_levels": "Любой уровень",
      "casual": "Для удовольствия",
      "competitive": "Соревновательный"
    },
    "effort": {
      "light": "Лёгкая",
      "moderate": "Средняя",
      "challenging": "Сложная"
    }
  },
  "ko": {
    "notSpecified": "지정 안 함",
    "free": "무료",
    "when": {
      "now": "지금",
      "tonight": "오늘 밤",
      "tomorrow": "내일",
      "custom": "날짜 선택"
    },
    "repeat": {
      "none": "반복 안 함",
      "weekly": "매주",
      "biweekly": "2주마다",
      "monthly": "매월"
    },
    "kind": {
      "friends": "👥 친구 / 가벼운 만남",
      "date": "💕 데이트",
      "family": "👨‍👩‍👧 가족",
      "coworkers": "💼 네트워킹 / 업무",
      "new_people": "🤝 새로운 사람 만나기",
      "groups": "👨‍👩‍👧‍👦 큰 그룹",
      "solo": "🧍 혼자도 좋아요"
    },
    "capacity": {
      "no_limit": "제한 없음",
      "2-4": "2~4명",
      "5-10": "5~10명",
      "10+": "10명 이상"
    },
    "feature": {
      "wheelchair_accessible": "휠체어 접근 가능",
      "accessible_parking": "장애인 주차",
      "accessible_restroom": "장애인 화장실",
      "service_animal_friendly": "보조견 동반 가능",
      "quiet": "조용한 환경",
      "kid_friendly": "아이 환영",
      "stroller_friendly": "유모차 이용 편리",
      "family_seating": "가족 좌석",
      "outdoor_seating": "야외 좌석",
      "pet_friendly": "반려동물 환영",
      "dog_friendly": "반려견 환영"
    },
    "equipment": {
      "provided": "장비 제공",
      "byo": "개인 지참"
    },
    "duration": {
      "30": "30분",
      "60": "1시간",
      "90": "1시간 30분",
      "120": "2시간",
      "180": "3시간"
    },
    "genre": {
      "rock": "록",
      "pop": "팝",
      "jazz": "재즈",
      "blues": "블루스",
      "country": "컨트리",
      "hip_hop": "힙합",
      "electronic": "일렉트로닉",
      "techno": "테크노",
      "classical": "클래식",
      "folk": "포크",
      "latin": "라틴",
      "r_and_b": "R&B",
      "open_mic": "오픈 마이크"
    },
    "format": {
      "drop_in": "자유 참여",
      "class": "수업",
      "tournament": "토너먼트",
      "meetup": "밋업",
      "concert": "콘서트",
      "show": "공연",
      "festival": "페스티벌",
      "tour": "투어",
      "workshop": "워크숍",
      "appointment": "예약 방문",
      "reservation": "예약",
      "open_play": "자유 게임",
      "competition": "대회",
      "exhibition": "전시",
      "market": "마켓",
      "party": "파티"
    },
    "skill": {
      "beginner": "초급",
      "intermediate": "중급",
      "advanced": "고급",
      "all_levels": "모든 수준",
      "casual": "캐주얼",
      "competitive": "경쟁"
    },
    "effort": {
      "light": "가벼움",
      "moderate": "보통",
      "challenging": "도전적"
    }
  }
};
