// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/notificationPrefs.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    section: {
      plans: {
        label: "Plans",
        hint: "Invitations, changes and reminders for plans you're part of.",
      },
      businesses: {
        label: "Businesses you use",
        hint: "Offers and replies to requests you made as a customer.",
      },
      business_owner: {
        label: "Your business",
        hint: "Alerts for running your business. Separate from Businesses you use.",
      },
      people: {
        label: "People",
        hint: "Friends, messages, calls, birthdays, dating and people you cross paths with.",
      },
      nearby: {
        label: "Nearby",
        hint: "Ideas near you, and communities you lead.",
      },
    },
    group: {
      plans_invitations: {
        label: "Invitations",
        hint: "Someone invites you to a gathering or plan.",
      },
      plans_changes: {
        label: "Changes to your plans",
        hint: "You're approved, a time or place moves, a plan is confirmed or cancelled.",
      },
      plans_reminders: {
        label: "Reminders",
        hint: "Before something you're going to starts.",
      },
      friends_activity: {
        label: "Friend requests and activity",
        hint: "Friend requests, a friend joins a gathering, new stories.",
      },
      friends_occasions: {
        label: "Birthdays and occasions",
        hint: "A friend's birthday or an occasion coming up.",
      },
      dating: {
        label: "Dating matches",
        hint: "New matches, waves and things you add together.",
      },
      business_offers: {
        label: "Offers",
        hint: "A business makes you an offer or posts an update.",
      },
      business_responses: {
        label: "Replies to your requests",
        hint: "A business declines, withdraws or confirms your booking.",
      },
      discover_recommendations: {
        label: "Recommendations",
        hint: "Gatherings and places nearby that fit your interests.",
      },
      discover_nearby_people: {
        label: "People you cross paths with",
        hint: "When you cross paths with someone nearby.",
      },
      communities: {
        label: "Communities you lead",
        hint: "Demand growing in, or a change to, a community you lead.",
      },
      messages: {
        label: "Messages",
        hint: "New messages in your one-on-one chats, with friends and matches.",
      },
      video_calls: {
        label: "Video calls",
        hint: "Someone starts a video or voice call with you, friends and matches alike.",
      },
    },
    toggleA11y: "Notify me about {label}",
  },
  es: {
    section: {
      plans: {
        label: "Planes",
        hint: "Invitaciones, cambios y recordatorios de los planes en los que participas.",
      },
      businesses: {
        label: "Negocios que usas",
        hint: "Ofertas y respuestas a las solicitudes que hiciste como cliente.",
      },
      business_owner: {
        label: "Tu negocio",
        hint: "Avisos para gestionar tu negocio. Aparte de Negocios que usas.",
      },
      people: {
        label: "Personas",
        hint: "Amigos, mensajes, llamadas, cumpleaños, citas y personas con las que te cruzas.",
      },
      nearby: {
        label: "Cerca",
        hint: "Ideas cerca de ti y las comunidades que diriges.",
      },
    },
    group: {
      plans_invitations: {
        label: "Invitaciones",
        hint: "Alguien te invita a una reunión o un plan.",
      },
      plans_changes: {
        label: "Cambios en tus planes",
        hint: "Te aprueban, cambia la hora o el lugar, se confirma o cancela un plan.",
      },
      plans_reminders: {
        label: "Recordatorios",
        hint: "Antes de que empiece algo a lo que vas.",
      },
      friends_activity: {
        label: "Solicitudes y actividad de amigos",
        hint: "Solicitudes de amistad, un amigo se une a una reunión, nuevas historias.",
      },
      friends_occasions: {
        label: "Cumpleaños y ocasiones",
        hint: "El cumpleaños de un amigo o una ocasión que se acerca.",
      },
      dating: {
        label: "Matches de citas",
        hint: "Nuevos matches, saludos y lo que agregan juntos.",
      },
      business_offers: {
        label: "Ofertas",
        hint: "Un negocio te hace una oferta o publica una novedad.",
      },
      business_responses: {
        label: "Respuestas a tus solicitudes",
        hint: "Un negocio rechaza, retira o confirma tu reserva.",
      },
      discover_recommendations: {
        label: "Recomendaciones",
        hint: "Reuniones y lugares cercanos que encajan con tus intereses.",
      },
      discover_nearby_people: {
        label: "Personas con las que te cruzas",
        hint: "Cuando te cruzas con alguien cerca.",
      },
      communities: {
        label: "Comunidades que diriges",
        hint: "Crece la demanda en una comunidad que diriges o hay un cambio en ella.",
      },
      messages: {
        label: "Mensajes",
        hint: "Mensajes nuevos en tus chats individuales, con amigos y matches.",
      },
      video_calls: {
        label: "Videollamadas",
        hint: "Alguien inicia una videollamada o llamada de voz contigo, sean amigos o matches.",
      },
    },
    toggleA11y: "Notificarme sobre {label}",
  },
  de: {
    section: {
      plans: {
        label: "Pläne",
        hint: "Einladungen, Änderungen und Erinnerungen zu Plänen, bei denen du dabei bist.",
      },
      businesses: {
        label: "Geschäfte, die du nutzt",
        hint: "Angebote und Antworten auf Anfragen, die du als Kunde gestellt hast.",
      },
      business_owner: {
        label: "Dein Geschäft",
        hint: "Hinweise zur Führung deines Geschäfts. Getrennt von „Geschäfte, die du nutzt“.",
      },
      people: {
        label: "Menschen",
        hint: "Freunde, Nachrichten, Anrufe, Geburtstage, Dating und Menschen, denen du begegnest.",
      },
      nearby: {
        label: "In der Nähe",
        hint: "Ideen in deiner Nähe und Communitys, die du leitest.",
      },
    },
    group: {
      plans_invitations: {
        label: "Einladungen",
        hint: "Jemand lädt dich zu einem Treffen oder Plan ein.",
      },
      plans_changes: {
        label: "Änderungen an deinen Plänen",
        hint: "Du bist bestätigt, Zeit oder Ort ändern sich, ein Plan wird bestätigt oder abgesagt.",
      },
      plans_reminders: {
        label: "Erinnerungen",
        hint: "Bevor etwas beginnt, zu dem du gehst.",
      },
      friends_activity: {
        label: "Freundschaftsanfragen und Aktivität",
        hint: "Freundschaftsanfragen, ein Freund tritt einem Treffen bei, neue Storys.",
      },
      friends_occasions: {
        label: "Geburtstage und Anlässe",
        hint: "Der Geburtstag eines Freundes oder ein bevorstehender Anlass.",
      },
      dating: {
        label: "Dating-Matches",
        hint: "Neue Matches, Winken und was ihr gemeinsam hinzufügt.",
      },
      business_offers: {
        label: "Angebote",
        hint: "Ein Geschäft macht dir ein Angebot oder postet ein Update.",
      },
      business_responses: {
        label: "Antworten auf deine Anfragen",
        hint: "Ein Geschäft lehnt ab, zieht zurück oder bestätigt deine Buchung.",
      },
      discover_recommendations: {
        label: "Empfehlungen",
        hint: "Treffen und Orte in der Nähe, die zu deinen Interessen passen.",
      },
      discover_nearby_people: {
        label: "Menschen, denen du begegnest",
        hint: "Wenn du jemandem in der Nähe begegnest.",
      },
      communities: {
        label: "Communitys, die du leitest",
        hint: "Wachsende Nachfrage in oder eine Änderung an einer Community, die du leitest.",
      },
      messages: {
        label: "Nachrichten",
        hint: "Neue Nachrichten in deinen Einzelchats, mit Freunden und Matches.",
      },
      video_calls: {
        label: "Videoanrufe",
        hint: "Jemand startet einen Video- oder Sprachanruf mit dir, Freunde wie Matches.",
      },
    },
    toggleA11y: "Benachrichtige mich über {label}",
  },
  fr: {
    section: {
      plans: {
        label: "Plans",
        hint: "Invitations, changements et rappels pour les plans auxquels vous participez.",
      },
      businesses: {
        label: "Commerces que vous utilisez",
        hint: "Offres et réponses aux demandes que vous avez faites en tant que client.",
      },
      business_owner: {
        label: "Votre commerce",
        hint: "Alertes pour gérer votre commerce. Distinctes de « Commerces que vous utilisez ».",
      },
      people: {
        label: "Personnes",
        hint: "Amis, messages, appels, anniversaires, rencontres et personnes que vous croisez.",
      },
      nearby: {
        label: "À proximité",
        hint: "Des idées près de chez vous et les communautés que vous animez.",
      },
    },
    group: {
      plans_invitations: {
        label: "Invitations",
        hint: "Quelqu'un vous invite à une rencontre ou un plan.",
      },
      plans_changes: {
        label: "Changements de vos plans",
        hint: "Vous êtes accepté, l'heure ou le lieu change, un plan est confirmé ou annulé.",
      },
      plans_reminders: {
        label: "Rappels",
        hint: "Avant le début d'un événement auquel vous allez.",
      },
      friends_activity: {
        label: "Demandes d’amis et activité",
        hint: "Demandes d'amis, un ami rejoint une rencontre, nouvelles stories.",
      },
      friends_occasions: {
        label: "Anniversaires et occasions",
        hint: "L'anniversaire d'un ami ou une occasion qui approche.",
      },
      dating: {
        label: "Matchs de rencontre",
        hint: "Nouveaux matchs, coucous et ce que vous ajoutez ensemble.",
      },
      business_offers: {
        label: "Offres",
        hint: "Un commerce vous fait une offre ou publie une nouveauté.",
      },
      business_responses: {
        label: "Réponses à vos demandes",
        hint: "Un commerce refuse, retire ou confirme votre réservation.",
      },
      discover_recommendations: {
        label: "Recommandations",
        hint: "Rencontres et lieux proches qui correspondent à vos centres d'intérêt.",
      },
      discover_nearby_people: {
        label: "Personnes que vous croisez",
        hint: "Quand vous croisez quelqu'un à proximité.",
      },
      communities: {
        label: "Communautés que vous animez",
        hint: "La demande grandit dans une communauté que vous animez, ou elle change.",
      },
      messages: {
        label: "Messages",
        hint: "Nouveaux messages dans vos discussions privées, avec vos amis et vos matchs.",
      },
      video_calls: {
        label: "Appels vidéo",
        hint: "Quelqu’un lance un appel vidéo ou vocal avec vous, ami ou match.",
      },
    },
    toggleA11y: "Me prévenir pour {label}",
  },
  pt: {
    section: {
      plans: {
        label: "Planos",
        hint: "Convites, mudanças e lembretes dos planos de que você participa.",
      },
      businesses: {
        label: "Negócios que você usa",
        hint: "Ofertas e respostas aos pedidos que você fez como cliente.",
      },
      business_owner: {
        label: "Seu negócio",
        hint: "Alertas para administrar seu negócio. Separados de Negócios que você usa.",
      },
      people: {
        label: "Pessoas",
        hint: "Amigos, mensagens, chamadas, aniversários, encontros e pessoas com quem você cruza.",
      },
      nearby: {
        label: "Por perto",
        hint: "Ideias perto de você e comunidades que você lidera.",
      },
    },
    group: {
      plans_invitations: {
        label: "Convites",
        hint: "Alguém convida você para um encontro ou plano.",
      },
      plans_changes: {
        label: "Mudanças nos seus planos",
        hint: "Você é aprovado, o horário ou local muda, um plano é confirmado ou cancelado.",
      },
      plans_reminders: {
        label: "Lembretes",
        hint: "Antes de começar algo a que você vai.",
      },
      friends_activity: {
        label: "Pedidos e atividade de amigos",
        hint: "Pedidos de amizade, um amigo entra em um encontro, novos stories.",
      },
      friends_occasions: {
        label: "Aniversários e ocasiões",
        hint: "O aniversário de um amigo ou uma ocasião chegando.",
      },
      dating: {
        label: "Matches de encontros",
        hint: "Novos matches, acenos e o que vocês adicionam juntos.",
      },
      business_offers: {
        label: "Ofertas",
        hint: "Um negócio faz uma oferta ou publica uma novidade.",
      },
      business_responses: {
        label: "Respostas aos seus pedidos",
        hint: "Um negócio recusa, retira ou confirma sua reserva.",
      },
      discover_recommendations: {
        label: "Recomendações",
        hint: "Encontros e lugares por perto que combinam com seus interesses.",
      },
      discover_nearby_people: {
        label: "Pessoas que cruzam seu caminho",
        hint: "Quando você cruza com alguém por perto.",
      },
      communities: {
        label: "Comunidades que você lidera",
        hint: "A demanda cresce em uma comunidade que você lidera, ou ela muda.",
      },
      messages: {
        label: "Mensagens",
        hint: "Novas mensagens nas suas conversas individuais, com amigos e matches.",
      },
      video_calls: {
        label: "Chamadas de vídeo",
        hint: "Alguém inicia uma chamada de vídeo ou de voz com você, amigos ou matches.",
      },
    },
    toggleA11y: "Notificar sobre {label}",
  },
  ht: {
    section: {
      plans: {
        label: "Plan",
        hint: "Envitasyon, chanjman ak rapèl pou plan ou ladan yo.",
      },
      businesses: {
        label: "Biznis ou itilize",
        hint: "Òf ak repons sou demann ou te fè kòm kliyan.",
      },
      business_owner: {
        label: "Biznis ou",
        hint: "Alèt pou jere biznis ou. Separe ak Biznis ou itilize.",
      },
      people: {
        label: "Moun",
        hint: "Zanmi, mesaj, apèl, anivèsè, randevou ak moun ou kwaze.",
      },
      nearby: {
        label: "Toupre",
        hint: "Ide toupre w, ak kominote w ap dirije.",
      },
    },
    group: {
      plans_invitations: {
        label: "Envitasyon",
        hint: "Yon moun envite ou nan yon rasanbleman oswa yon plan.",
      },
      plans_changes: {
        label: "Chanjman nan plan ou",
        hint: "Yo apwouve ou, lè oswa kote a chanje, yon plan konfime oswa anile.",
      },
      plans_reminders: {
        label: "Rapèl",
        hint: "Anvan yon bagay ou prale kòmanse.",
      },
      friends_activity: {
        label: "Demann zanmi ak aktivite",
        hint: "Demann zanmi, yon zanmi antre nan yon rasanbleman, nouvo istwa.",
      },
      friends_occasions: {
        label: "Anivèsè ak okazyon",
        hint: "Anivèsè yon zanmi oswa yon okazyon k ap vini.",
      },
      dating: {
        label: "Match randevou",
        hint: "Nouvo match, bonjou ak sa nou ajoute ansanm.",
      },
      business_offers: {
        label: "Òf",
        hint: "Yon biznis fè ou yon òf oswa poste yon nouvèl.",
      },
      business_responses: {
        label: "Repons a demann ou yo",
        hint: "Yon biznis refize, retire oswa konfime rezèvasyon ou.",
      },
      discover_recommendations: {
        label: "Rekòmandasyon",
        hint: "Rasanbleman ak kote toupre ki matche ak enterè ou.",
      },
      discover_nearby_people: {
        label: "Moun ou kwaze",
        hint: "Lè ou kwaze yon moun toupre.",
      },
      communities: {
        label: "Kominote w ap dirije",
        hint: "Demann ap grandi nan yon kominote ou dirije, oswa li chanje.",
      },
      messages: {
        label: "Mesaj",
        hint: "Nouvo mesaj nan chat youn-a-youn ou, ak zanmi ak match.",
      },
      video_calls: {
        label: "Apèl videyo",
        hint: "Yon moun kòmanse yon apèl videyo oswa vwa avè w, zanmi kou match.",
      },
    },
    toggleA11y: "Fè m konnen sou {label}",
  },
  zh: {
    section: {
      plans: {
        label: "计划",
        hint: "你参与的计划的邀请、变更和提醒。",
      },
      businesses: {
        label: "你光顾的商家",
        hint: "你作为顾客发出的请求收到的优惠和回复。",
      },
      business_owner: {
        label: "你的商家",
        hint: "经营你的商家时的提醒。与“你光顾的商家”分开。",
      },
      people: {
        label: "人",
        hint: "好友、消息、通话、生日、约会，以及与你擦肩而过的人。",
      },
      nearby: {
        label: "附近",
        hint: "你附近的点子，以及你管理的社区。",
      },
    },
    group: {
      plans_invitations: {
        label: "邀请",
        hint: "有人邀请你参加聚会或计划。",
      },
      plans_changes: {
        label: "你的计划变更",
        hint: "你被批准、时间或地点变化、计划确认或取消。",
      },
      plans_reminders: {
        label: "提醒",
        hint: "你要参加的活动开始之前。",
      },
      friends_activity: {
        label: "好友请求和动态",
        hint: "好友请求、好友加入聚会、新动态。",
      },
      friends_occasions: {
        label: "生日和纪念日",
        hint: "好友的生日或即将到来的纪念日。",
      },
      dating: {
        label: "约会配对",
        hint: "新配对、打招呼，以及你们一起添加的内容。",
      },
      business_offers: {
        label: "报价",
        hint: "商家向你发出报价或发布更新。",
      },
      business_responses: {
        label: "对你请求的回复",
        hint: "商家拒绝、撤回或确认你的预订。",
      },
      discover_recommendations: {
        label: "推荐",
        hint: "附近符合你兴趣的聚会和地点。",
      },
      discover_nearby_people: {
        label: "擦肩而过的人",
        hint: "当你与附近的人擦肩而过时。",
      },
      communities: {
        label: "你管理的社区",
        hint: "你管理的社区需求增长或发生变化。",
      },
      messages: {
        label: "消息",
        hint: "你一对一聊天中的新消息，包括好友和配对。",
      },
      video_calls: {
        label: "视频通话",
        hint: "有人向你发起视频或语音通话，好友和配对都包括。",
      },
    },
    toggleA11y: "通知我：{label}",
  },
  vi: {
    section: {
      plans: {
        label: "Kế hoạch",
        hint: "Lời mời, thay đổi và lời nhắc cho các kế hoạch bạn tham gia.",
      },
      businesses: {
        label: "Doanh nghiệp bạn dùng",
        hint: "Ưu đãi và phản hồi cho các yêu cầu bạn gửi với tư cách khách hàng.",
      },
      business_owner: {
        label: "Doanh nghiệp của bạn",
        hint: "Thông báo để vận hành doanh nghiệp của bạn. Tách riêng với Doanh nghiệp bạn dùng.",
      },
      people: {
        label: "Mọi người",
        hint: "Bạn bè, tin nhắn, cuộc gọi, sinh nhật, hẹn hò và những người bạn tình cờ gặp.",
      },
      nearby: {
        label: "Gần đây",
        hint: "Ý tưởng gần bạn và các cộng đồng bạn dẫn dắt.",
      },
    },
    group: {
      plans_invitations: {
        label: "Lời mời",
        hint: "Ai đó mời bạn tham gia buổi gặp mặt hoặc kế hoạch.",
      },
      plans_changes: {
        label: "Thay đổi trong kế hoạch của bạn",
        hint: "Bạn được duyệt, giờ hoặc địa điểm thay đổi, kế hoạch được xác nhận hoặc bị hủy.",
      },
      plans_reminders: {
        label: "Lời nhắc",
        hint: "Trước khi điều bạn sẽ tham gia bắt đầu.",
      },
      friends_activity: {
        label: "Lời mời kết bạn và hoạt động",
        hint: "Lời mời kết bạn, bạn bè tham gia buổi gặp mặt, tin mới.",
      },
      friends_occasions: {
        label: "Sinh nhật và dịp đặc biệt",
        hint: "Sinh nhật của bạn bè hoặc một dịp sắp đến.",
      },
      dating: {
        label: "Ghép đôi hẹn hò",
        hint: "Ghép đôi mới, lời chào và những gì hai bạn cùng thêm.",
      },
      business_offers: {
        label: "Ưu đãi",
        hint: "Một doanh nghiệp gửi bạn ưu đãi hoặc đăng cập nhật.",
      },
      business_responses: {
        label: "Phản hồi cho yêu cầu của bạn",
        hint: "Doanh nghiệp từ chối, rút lại hoặc xác nhận đặt chỗ của bạn.",
      },
      discover_recommendations: {
        label: "Gợi ý",
        hint: "Buổi gặp mặt và địa điểm gần đây hợp với sở thích của bạn.",
      },
      discover_nearby_people: {
        label: "Người bạn tình cờ gặp",
        hint: "Khi bạn tình cờ gặp ai đó gần đây.",
      },
      communities: {
        label: "Cộng đồng bạn dẫn dắt",
        hint: "Nhu cầu tăng hoặc có thay đổi trong cộng đồng bạn quản lý.",
      },
      messages: {
        label: "Tin nhắn",
        hint: "Tin nhắn mới trong các cuộc trò chuyện riêng, với bạn bè và người ghép đôi.",
      },
      video_calls: {
        label: "Cuộc gọi video",
        hint: "Ai đó bắt đầu cuộc gọi video hoặc thoại với bạn, cả bạn bè lẫn người ghép đôi.",
      },
    },
    toggleA11y: "Thông báo cho tôi về {label}",
  },
  tl: {
    section: {
      plans: {
        label: "Mga Plano",
        hint: "Mga imbitasyon, pagbabago at paalala para sa mga planong kasali ka.",
      },
      businesses: {
        label: "Mga negosyong ginagamit mo",
        hint: "Mga alok at sagot sa mga request mo bilang customer.",
      },
      business_owner: {
        label: "Ang negosyo mo",
        hint: "Mga alerto sa pagpapatakbo ng negosyo mo. Hiwalay sa Mga negosyong ginagamit mo.",
      },
      people: {
        label: "Mga tao",
        hint: "Mga kaibigan, mensahe, tawag, kaarawan, dating at mga taong nakakasalubong mo.",
      },
      nearby: {
        label: "Malapit",
        hint: "Mga ideya malapit sa iyo, at mga komunidad na pinamumunuan mo.",
      },
    },
    group: {
      plans_invitations: {
        label: "Mga imbitasyon",
        hint: "May nag-imbita sa iyo sa isang gathering o plano.",
      },
      plans_changes: {
        label: "Mga pagbabago sa plano mo",
        hint: "Naaprubahan ka, nagbago ang oras o lugar, nakumpirma o nakansela ang plano.",
      },
      plans_reminders: {
        label: "Mga paalala",
        hint: "Bago magsimula ang isang pupuntahan mo.",
      },
      friends_activity: {
        label: "Mga friend request at aktibidad",
        hint: "Mga friend request, may kaibigang sumali sa gathering, bagong stories.",
      },
      friends_occasions: {
        label: "Kaarawan at okasyon",
        hint: "Kaarawan ng kaibigan o paparating na okasyon.",
      },
      dating: {
        label: "Mga dating match",
        hint: "Mga bagong match, kaway at mga idinadagdag ninyo nang magkasama.",
      },
      business_offers: {
        label: "Mga alok",
        hint: "May negosyong nag-alok sa iyo o nag-post ng update.",
      },
      business_responses: {
        label: "Mga sagot sa request mo",
        hint: "Tinanggihan, binawi o kinumpirma ng negosyo ang booking mo.",
      },
      discover_recommendations: {
        label: "Mga rekomendasyon",
        hint: "Mga gathering at lugar sa malapit na tugma sa interes mo.",
      },
      discover_nearby_people: {
        label: "Mga taong nakakasalubong mo",
        hint: "Kapag may nakasalubong kang tao sa malapit.",
      },
      communities: {
        label: "Mga komunidad na pinamumunuan mo",
        hint: "Lumalaki ang demand o may pagbabago sa komunidad na pinamumunuan mo.",
      },
      messages: {
        label: "Mga mensahe",
        hint: "Mga bagong mensahe sa one-on-one chats mo, kasama ang mga kaibigan at match.",
      },
      video_calls: {
        label: "Mga video call",
        hint: "May nagsimula ng video o voice call sa iyo, kaibigan man o match.",
      },
    },
    toggleA11y: "Abisuhan ako tungkol sa {label}",
  },
  ru: {
    section: {
      plans: {
        label: "Планы",
        hint: "Приглашения, изменения и напоминания о планах, в которых вы участвуете.",
      },
      businesses: {
        label: "Заведения, которыми вы пользуетесь",
        hint: "Предложения и ответы на заявки, которые вы отправили как клиент.",
      },
      business_owner: {
        label: "Ваш бизнес",
        hint: "Уведомления для ведения вашего бизнеса. Отдельно от «Заведения, которыми вы пользуетесь».",
      },
      people: {
        label: "Люди",
        hint: "Друзья, сообщения, звонки, дни рождения, знакомства и люди, которых вы встречаете.",
      },
      nearby: {
        label: "Рядом",
        hint: "Идеи поблизости и сообщества, которыми вы руководите.",
      },
    },
    group: {
      plans_invitations: {
        label: "Приглашения",
        hint: "Вас приглашают на встречу или в план.",
      },
      plans_changes: {
        label: "Изменения в ваших планах",
        hint: "Вас одобрили, изменились время или место, план подтверждён или отменён.",
      },
      plans_reminders: {
        label: "Напоминания",
        hint: "Перед началом того, куда вы идёте.",
      },
      friends_activity: {
        label: "Заявки в друзья и активность",
        hint: "Заявки в друзья, друг присоединился к встрече, новые истории.",
      },
      friends_occasions: {
        label: "Дни рождения и события",
        hint: "День рождения друга или приближающееся событие.",
      },
      dating: {
        label: "Знакомства: совпадения",
        hint: "Новые совпадения, приветы и то, что вы добавляете вместе.",
      },
      business_offers: {
        label: "Предложения",
        hint: "Бизнес делает вам предложение или публикует новость.",
      },
      business_responses: {
        label: "Ответы на ваши запросы",
        hint: "Бизнес отказывает, отзывает предложение или подтверждает бронь.",
      },
      discover_recommendations: {
        label: "Рекомендации",
        hint: "Встречи и места рядом, подходящие под ваши интересы.",
      },
      discover_nearby_people: {
        label: "Люди, с которыми вы пересекаетесь",
        hint: "Когда вы пересекаетесь с кем-то рядом.",
      },
      communities: {
        label: "Сообщества, которыми вы руководите",
        hint: "Растёт спрос в сообществе, которое вы ведёте, или оно меняется.",
      },
      messages: {
        label: "Сообщения",
        hint: "Новые сообщения в личных чатах с друзьями и совпадениями.",
      },
      video_calls: {
        label: "Видеозвонки",
        hint: "Кто-то начинает с вами видео- или голосовой звонок, друзья и совпадения.",
      },
    },
    toggleA11y: "Уведомлять о: {label}",
  },
  ko: {
    section: {
      plans: {
        label: "계획",
        hint: "참여 중인 계획의 초대, 변경, 알림.",
      },
      businesses: {
        label: "이용하는 업체",
        hint: "고객으로서 보낸 요청에 대한 혜택과 답변.",
      },
      business_owner: {
        label: "내 업체",
        hint: "업체 운영 알림. ‘이용하는 업체’와 별개입니다.",
      },
      people: {
        label: "사람",
        hint: "친구, 메시지, 통화, 생일, 데이트, 그리고 마주친 사람.",
      },
      nearby: {
        label: "근처",
        hint: "근처의 아이디어와 내가 운영하는 커뮤니티.",
      },
    },
    group: {
      plans_invitations: {
        label: "초대",
        hint: "누군가 모임이나 계획에 초대했을 때.",
      },
      plans_changes: {
        label: "내 계획 변경",
        hint: "승인되었거나, 시간·장소가 바뀌었거나, 계획이 확정·취소되었을 때.",
      },
      plans_reminders: {
        label: "알림",
        hint: "참여하는 일정이 시작되기 전.",
      },
      friends_activity: {
        label: "친구 요청과 활동",
        hint: "친구 요청, 친구의 모임 참여, 새 스토리.",
      },
      friends_occasions: {
        label: "생일과 기념일",
        hint: "친구의 생일이나 다가오는 기념일.",
      },
      dating: {
        label: "데이트 매치",
        hint: "새 매치, 인사, 함께 추가한 항목.",
      },
      business_offers: {
        label: "제안",
        hint: "업체가 제안을 보내거나 소식을 올렸을 때.",
      },
      business_responses: {
        label: "내 요청에 대한 답변",
        hint: "업체가 거절, 철회하거나 예약을 확정했을 때.",
      },
      discover_recommendations: {
        label: "추천",
        hint: "관심사에 맞는 주변 모임과 장소.",
      },
      discover_nearby_people: {
        label: "마주친 사람",
        hint: "주변에서 누군가와 마주쳤을 때.",
      },
      communities: {
        label: "내가 운영하는 커뮤니티",
        hint: "운영 중인 커뮤니티의 수요 증가나 변경.",
      },
      messages: {
        label: "메시지",
        hint: "친구와 매치와의 1:1 채팅 새 메시지.",
      },
      video_calls: {
        label: "영상 통화",
        hint: "친구나 매치가 영상 또는 음성 통화를 시작할 때.",
      },
    },
    toggleA11y: "{label} 알림 받기",
  },
};
