// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/notificationPrefs.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    area: {
      plans: {
        label: "Plans",
        hint: "Invitations, changes and reminders for plans you're part of.",
      },
      friends: {
        label: "Friends",
        hint: "Friend requests, what friends are up to, birthdays.",
      },
      dating: {
        label: "Dating",
        hint: "Matches, messages, waves and calls.",
      },
      businesses: {
        label: "Businesses you use",
        hint: "Offers and replies to requests you made as a customer.",
      },
      discover: {
        label: "Discover",
        hint: "Things to do that fit your interests, and people you cross paths with.",
      },
      communities: {
        label: "Communities",
        hint: "Activity in communities you lead.",
      },
      business_owner: {
        label: "Your business",
        hint: "Alerts for running your business. Separate from Businesses you use.",
      },
    },
    group: {
      plans_invitations: {
        label: "Invitations",
        hint: "Someone invites you to a gathering or plan.",
      },
      plans_changes: {
        label: "Changes",
        hint: "You're approved, a time or place moves, a plan is confirmed or cancelled.",
      },
      plans_reminders: {
        label: "Reminders",
        hint: "Before something you're going to starts.",
      },
      friends_activity: {
        label: "Friend activity",
        hint: "Friend requests, a friend joins a gathering, new stories.",
      },
      friends_occasions: {
        label: "Birthdays and occasions",
        hint: "A friend's birthday or an occasion coming up.",
      },
      dating: {
        label: "Matches and messages",
        hint: "New matches, messages, waves and calls.",
      },
      business_offers: {
        label: "Offers",
        hint: "A business makes you an offer or posts an update.",
      },
      business_responses: {
        label: "Request responses",
        hint: "A business declines, withdraws or confirms your booking.",
      },
      discover_recommendations: {
        label: "Recommendations",
        hint: "Gatherings and places nearby that fit your interests.",
      },
      discover_nearby_people: {
        label: "People you cross paths with",
        hint: "When you cross paths with someone nearby.",
      },
      communities: {
        label: "Community activity",
        hint: "Demand growing in, or a change to, a community you lead.",
      },
    },
    toggleA11y: "Notify me about {label}",
  },
  es: {
    area: {
      plans: {
        label: "Planes",
        hint: "Invitaciones, cambios y recordatorios de los planes en los que participas.",
      },
      friends: {
        label: "Amigos",
        hint: "Solicitudes de amistad, lo que hacen tus amigos, cumpleaños.",
      },
      dating: {
        label: "Citas",
        hint: "Matches, mensajes, saludos y llamadas.",
      },
      businesses: {
        label: "Negocios que usas",
        hint: "Ofertas y respuestas a las solicitudes que hiciste como cliente.",
      },
      discover: {
        label: "Descubrir",
        hint: "Cosas que hacer según tus intereses y personas con las que te cruzas.",
      },
      communities: {
        label: "Comunidades",
        hint: "Actividad en las comunidades que diriges.",
      },
      business_owner: {
        label: "Tu negocio",
        hint: "Avisos para gestionar tu negocio. Aparte de Negocios que usas.",
      },
    },
    group: {
      plans_invitations: {
        label: "Invitaciones",
        hint: "Alguien te invita a una reunión o un plan.",
      },
      plans_changes: {
        label: "Cambios",
        hint: "Te aprueban, cambia la hora o el lugar, se confirma o cancela un plan.",
      },
      plans_reminders: {
        label: "Recordatorios",
        hint: "Antes de que empiece algo a lo que vas.",
      },
      friends_activity: {
        label: "Actividad de amigos",
        hint: "Solicitudes de amistad, un amigo se une a una reunión, nuevas historias.",
      },
      friends_occasions: {
        label: "Cumpleaños y ocasiones",
        hint: "El cumpleaños de un amigo o una ocasión que se acerca.",
      },
      dating: {
        label: "Matches y mensajes",
        hint: "Nuevos matches, mensajes, saludos y llamadas.",
      },
      business_offers: {
        label: "Ofertas",
        hint: "Un negocio te hace una oferta o publica una novedad.",
      },
      business_responses: {
        label: "Respuestas a solicitudes",
        hint: "Un negocio rechaza, retira o confirma tu reserva.",
      },
      discover_recommendations: {
        label: "Recomendaciones",
        hint: "Reuniones y lugares cercanos que encajan con tus intereses.",
      },
      discover_nearby_people: {
        label: "Personas con las que te cruzas",
        hint: "Cuando te cruzas con alguien cerca.",
      },
      communities: {
        label: "Actividad de la comunidad",
        hint: "Crece la demanda en una comunidad que diriges o hay un cambio en ella.",
      },
    },
    toggleA11y: "Notificarme sobre {label}",
  },
  de: {
    area: {
      plans: {
        label: "Pläne",
        hint: "Einladungen, Änderungen und Erinnerungen zu Plänen, bei denen du dabei bist.",
      },
      friends: {
        label: "Freunde",
        hint: "Freundschaftsanfragen, was Freunde vorhaben, Geburtstage.",
      },
      dating: {
        label: "Dating",
        hint: "Matches, Nachrichten, Winken und Anrufe.",
      },
      businesses: {
        label: "Geschäfte, die du nutzt",
        hint: "Angebote und Antworten auf Anfragen, die du als Kunde gestellt hast.",
      },
      discover: {
        label: "Entdecken",
        hint: "Unternehmungen passend zu deinen Interessen und Menschen, denen du begegnest.",
      },
      communities: {
        label: "Communities",
        hint: "Aktivität in Communities, die du leitest.",
      },
      business_owner: {
        label: "Dein Geschäft",
        hint: "Hinweise zur Führung deines Geschäfts. Getrennt von „Geschäfte, die du nutzt“.",
      },
    },
    group: {
      plans_invitations: {
        label: "Einladungen",
        hint: "Jemand lädt dich zu einem Treffen oder Plan ein.",
      },
      plans_changes: {
        label: "Änderungen",
        hint: "Du bist bestätigt, Zeit oder Ort ändern sich, ein Plan wird bestätigt oder abgesagt.",
      },
      plans_reminders: {
        label: "Erinnerungen",
        hint: "Bevor etwas beginnt, zu dem du gehst.",
      },
      friends_activity: {
        label: "Aktivität von Freunden",
        hint: "Freundschaftsanfragen, ein Freund tritt einem Treffen bei, neue Storys.",
      },
      friends_occasions: {
        label: "Geburtstage und Anlässe",
        hint: "Der Geburtstag eines Freundes oder ein bevorstehender Anlass.",
      },
      dating: {
        label: "Matches und Nachrichten",
        hint: "Neue Matches, Nachrichten, Winken und Anrufe.",
      },
      business_offers: {
        label: "Angebote",
        hint: "Ein Geschäft macht dir ein Angebot oder postet ein Update.",
      },
      business_responses: {
        label: "Antworten auf Anfragen",
        hint: "Ein Geschäft lehnt ab, zieht zurück oder bestätigt deine Buchung.",
      },
      discover_recommendations: {
        label: "Empfehlungen",
        hint: "Treffen und Orte in der Nähe, die zu deinen Interessen passen.",
      },
      discover_nearby_people: {
        label: "Menschen, denen du begegnest",
        hint: "Wenn du jemandem in der Nähe begegnest.",
      },
      communities: {
        label: "Community-Aktivität",
        hint: "Wachsende Nachfrage in oder eine Änderung an einer Community, die du leitest.",
      },
    },
    toggleA11y: "Benachrichtige mich über {label}",
  },
  fr: {
    area: {
      plans: {
        label: "Plans",
        hint: "Invitations, changements et rappels pour les plans auxquels vous participez.",
      },
      friends: {
        label: "Amis",
        hint: "Demandes d'amis, ce que font vos amis, anniversaires.",
      },
      dating: {
        label: "Rencontres",
        hint: "Matchs, messages, saluts et appels.",
      },
      businesses: {
        label: "Commerces que vous utilisez",
        hint: "Offres et réponses aux demandes que vous avez faites en tant que client.",
      },
      discover: {
        label: "Découvrir",
        hint: "Des sorties selon vos centres d'intérêt et les personnes que vous croisez.",
      },
      communities: {
        label: "Communautés",
        hint: "L'activité des communautés que vous animez.",
      },
      business_owner: {
        label: "Votre commerce",
        hint: "Alertes pour gérer votre commerce. Distinctes de « Commerces que vous utilisez ».",
      },
    },
    group: {
      plans_invitations: {
        label: "Invitations",
        hint: "Quelqu'un vous invite à une rencontre ou un plan.",
      },
      plans_changes: {
        label: "Changements",
        hint: "Vous êtes accepté, l'heure ou le lieu change, un plan est confirmé ou annulé.",
      },
      plans_reminders: {
        label: "Rappels",
        hint: "Avant le début d'un événement auquel vous allez.",
      },
      friends_activity: {
        label: "Activité des amis",
        hint: "Demandes d'amis, un ami rejoint une rencontre, nouvelles stories.",
      },
      friends_occasions: {
        label: "Anniversaires et occasions",
        hint: "L'anniversaire d'un ami ou une occasion qui approche.",
      },
      dating: {
        label: "Matchs et messages",
        hint: "Nouveaux matchs, messages, saluts et appels.",
      },
      business_offers: {
        label: "Offres",
        hint: "Un commerce vous fait une offre ou publie une nouveauté.",
      },
      business_responses: {
        label: "Réponses aux demandes",
        hint: "Un commerce refuse, retire ou confirme votre réservation.",
      },
      discover_recommendations: {
        label: "Recommandations",
        hint: "Rencontres et lieux proches qui correspondent à vos centres d'intérêt.",
      },
      discover_nearby_people: {
        label: "Personnes que vous croisez",
        hint: "Quand vous croisez quelqu'un à proximité.",
      },
      communities: {
        label: "Activité de la communauté",
        hint: "La demande grandit dans une communauté que vous animez, ou elle change.",
      },
    },
    toggleA11y: "Me prévenir pour {label}",
  },
  pt: {
    area: {
      plans: {
        label: "Planos",
        hint: "Convites, mudanças e lembretes dos planos de que você participa.",
      },
      friends: {
        label: "Amigos",
        hint: "Pedidos de amizade, o que seus amigos estão fazendo, aniversários.",
      },
      dating: {
        label: "Encontros",
        hint: "Matches, mensagens, acenos e chamadas.",
      },
      businesses: {
        label: "Negócios que você usa",
        hint: "Ofertas e respostas aos pedidos que você fez como cliente.",
      },
      discover: {
        label: "Descobrir",
        hint: "Coisas para fazer de acordo com seus interesses e pessoas que cruzam seu caminho.",
      },
      communities: {
        label: "Comunidades",
        hint: "Atividade nas comunidades que você lidera.",
      },
      business_owner: {
        label: "Seu negócio",
        hint: "Alertas para administrar seu negócio. Separados de Negócios que você usa.",
      },
    },
    group: {
      plans_invitations: {
        label: "Convites",
        hint: "Alguém convida você para um encontro ou plano.",
      },
      plans_changes: {
        label: "Mudanças",
        hint: "Você é aprovado, o horário ou local muda, um plano é confirmado ou cancelado.",
      },
      plans_reminders: {
        label: "Lembretes",
        hint: "Antes de começar algo a que você vai.",
      },
      friends_activity: {
        label: "Atividade dos amigos",
        hint: "Pedidos de amizade, um amigo entra em um encontro, novos stories.",
      },
      friends_occasions: {
        label: "Aniversários e ocasiões",
        hint: "O aniversário de um amigo ou uma ocasião chegando.",
      },
      dating: {
        label: "Matches e mensagens",
        hint: "Novos matches, mensagens, acenos e chamadas.",
      },
      business_offers: {
        label: "Ofertas",
        hint: "Um negócio faz uma oferta ou publica uma novidade.",
      },
      business_responses: {
        label: "Respostas a pedidos",
        hint: "Um negócio recusa, retira ou confirma sua reserva.",
      },
      discover_recommendations: {
        label: "Recomendações",
        hint: "Encontros e lugares por perto que combinam com seus interesses.",
      },
      discover_nearby_people: {
        label: "Pessoas que cruzam seu caminho",
        hint: "Quando você cruza com alguém por perto.",
      },
      communities: {
        label: "Atividade da comunidade",
        hint: "A demanda cresce em uma comunidade que você lidera, ou ela muda.",
      },
    },
    toggleA11y: "Notificar sobre {label}",
  },
  ht: {
    area: {
      plans: {
        label: "Plan",
        hint: "Envitasyon, chanjman ak rapèl pou plan ou ladan yo.",
      },
      friends: {
        label: "Zanmi",
        hint: "Demann zanmi, sa zanmi ou ap fè, anivèsè.",
      },
      dating: {
        label: "Rankont",
        hint: "Match, mesaj, salitasyon ak apèl.",
      },
      businesses: {
        label: "Biznis ou itilize",
        hint: "Òf ak repons sou demann ou te fè kòm kliyan.",
      },
      discover: {
        label: "Dekouvri",
        hint: "Bagay pou fè ki matche ak enterè ou, ak moun ou kwaze.",
      },
      communities: {
        label: "Kominote",
        hint: "Aktivite nan kominote ou dirije.",
      },
      business_owner: {
        label: "Biznis ou",
        hint: "Alèt pou jere biznis ou. Separe ak Biznis ou itilize.",
      },
    },
    group: {
      plans_invitations: {
        label: "Envitasyon",
        hint: "Yon moun envite ou nan yon rasanbleman oswa yon plan.",
      },
      plans_changes: {
        label: "Chanjman",
        hint: "Yo apwouve ou, lè oswa kote a chanje, yon plan konfime oswa anile.",
      },
      plans_reminders: {
        label: "Rapèl",
        hint: "Anvan yon bagay ou prale kòmanse.",
      },
      friends_activity: {
        label: "Aktivite zanmi",
        hint: "Demann zanmi, yon zanmi antre nan yon rasanbleman, nouvo istwa.",
      },
      friends_occasions: {
        label: "Anivèsè ak okazyon",
        hint: "Anivèsè yon zanmi oswa yon okazyon k ap vini.",
      },
      dating: {
        label: "Match ak mesaj",
        hint: "Nouvo match, mesaj, salitasyon ak apèl.",
      },
      business_offers: {
        label: "Òf",
        hint: "Yon biznis fè ou yon òf oswa poste yon nouvèl.",
      },
      business_responses: {
        label: "Repons a demann",
        hint: "Yon biznis refize, retire oswa konfime rezèvasyon ou.",
      },
      discover_recommendations: {
        label: "Rekòmandasyon",
        hint: "Rasanbleman ak kote toupre ki matche ak enterè ou.",
      },
      discover_nearby_people: {
        label: "Moun ou kwaze",
        hint: "Lè ou kwaze yon moun toupre.",
      },
      communities: {
        label: "Aktivite kominote",
        hint: "Demann ap grandi nan yon kominote ou dirije, oswa li chanje.",
      },
    },
    toggleA11y: "Fè m konnen sou {label}",
  },
  zh: {
    area: {
      plans: {
        label: "计划",
        hint: "你参与的计划的邀请、变更和提醒。",
      },
      friends: {
        label: "好友",
        hint: "好友请求、好友动态、生日。",
      },
      dating: {
        label: "约会",
        hint: "配对、消息、招呼和通话。",
      },
      businesses: {
        label: "你光顾的商家",
        hint: "你作为顾客发出的请求收到的优惠和回复。",
      },
      discover: {
        label: "发现",
        hint: "符合你兴趣的活动，以及与你擦肩而过的人。",
      },
      communities: {
        label: "社区",
        hint: "你管理的社区中的动态。",
      },
      business_owner: {
        label: "你的商家",
        hint: "经营你的商家时的提醒。与“你光顾的商家”分开。",
      },
    },
    group: {
      plans_invitations: {
        label: "邀请",
        hint: "有人邀请你参加聚会或计划。",
      },
      plans_changes: {
        label: "变更",
        hint: "你被批准、时间或地点变化、计划确认或取消。",
      },
      plans_reminders: {
        label: "提醒",
        hint: "你要参加的活动开始之前。",
      },
      friends_activity: {
        label: "好友动态",
        hint: "好友请求、好友加入聚会、新动态。",
      },
      friends_occasions: {
        label: "生日和纪念日",
        hint: "好友的生日或即将到来的纪念日。",
      },
      dating: {
        label: "配对和消息",
        hint: "新配对、消息、招呼和通话。",
      },
      business_offers: {
        label: "报价",
        hint: "商家向你发出报价或发布更新。",
      },
      business_responses: {
        label: "请求回复",
        hint: "商家拒绝、撤回或确认你的预订。",
      },
      discover_recommendations: {
        label: "推荐",
        hint: "附近符合你兴趣的聚会和地点。",
      },
      discover_nearby_people: {
        label: "擦肩而过的人",
        hint: "当你与附近的人擦肩而过时。",
      },
      communities: {
        label: "社区动态",
        hint: "你管理的社区需求增长或发生变化。",
      },
    },
    toggleA11y: "通知我：{label}",
  },
  vi: {
    area: {
      plans: {
        label: "Kế hoạch",
        hint: "Lời mời, thay đổi và lời nhắc cho các kế hoạch bạn tham gia.",
      },
      friends: {
        label: "Bạn bè",
        hint: "Lời mời kết bạn, bạn bè đang làm gì, sinh nhật.",
      },
      dating: {
        label: "Hẹn hò",
        hint: "Ghép đôi, tin nhắn, vẫy tay và cuộc gọi.",
      },
      businesses: {
        label: "Doanh nghiệp bạn dùng",
        hint: "Ưu đãi và phản hồi cho các yêu cầu bạn gửi với tư cách khách hàng.",
      },
      discover: {
        label: "Khám phá",
        hint: "Hoạt động hợp với sở thích của bạn và những người bạn tình cờ gặp.",
      },
      communities: {
        label: "Cộng đồng",
        hint: "Hoạt động trong các cộng đồng bạn quản lý.",
      },
      business_owner: {
        label: "Doanh nghiệp của bạn",
        hint: "Thông báo để vận hành doanh nghiệp của bạn. Tách riêng với Doanh nghiệp bạn dùng.",
      },
    },
    group: {
      plans_invitations: {
        label: "Lời mời",
        hint: "Ai đó mời bạn tham gia buổi gặp mặt hoặc kế hoạch.",
      },
      plans_changes: {
        label: "Thay đổi",
        hint: "Bạn được duyệt, giờ hoặc địa điểm thay đổi, kế hoạch được xác nhận hoặc bị hủy.",
      },
      plans_reminders: {
        label: "Lời nhắc",
        hint: "Trước khi điều bạn sẽ tham gia bắt đầu.",
      },
      friends_activity: {
        label: "Hoạt động của bạn bè",
        hint: "Lời mời kết bạn, bạn bè tham gia buổi gặp mặt, tin mới.",
      },
      friends_occasions: {
        label: "Sinh nhật và dịp đặc biệt",
        hint: "Sinh nhật của bạn bè hoặc một dịp sắp đến.",
      },
      dating: {
        label: "Ghép đôi và tin nhắn",
        hint: "Ghép đôi mới, tin nhắn, vẫy tay và cuộc gọi.",
      },
      business_offers: {
        label: "Ưu đãi",
        hint: "Một doanh nghiệp gửi bạn ưu đãi hoặc đăng cập nhật.",
      },
      business_responses: {
        label: "Phản hồi yêu cầu",
        hint: "Doanh nghiệp từ chối, rút lại hoặc xác nhận đặt chỗ của bạn.",
      },
      discover_recommendations: {
        label: "Gợi ý",
        hint: "Buổi gặp mặt và địa điểm gần đây hợp với sở thích của bạn.",
      },
      discover_nearby_people: {
        label: "Người bạn tình cờ gặp",
        hint: "Khi bạn tình cờ gặp ai đó gần đây.",
      },
      communities: {
        label: "Hoạt động cộng đồng",
        hint: "Nhu cầu tăng hoặc có thay đổi trong cộng đồng bạn quản lý.",
      },
    },
    toggleA11y: "Thông báo cho tôi về {label}",
  },
  tl: {
    area: {
      plans: {
        label: "Mga Plano",
        hint: "Mga imbitasyon, pagbabago at paalala para sa mga planong kasali ka.",
      },
      friends: {
        label: "Mga Kaibigan",
        hint: "Mga friend request, ginagawa ng mga kaibigan, kaarawan.",
      },
      dating: {
        label: "Dating",
        hint: "Mga match, mensahe, kaway at tawag.",
      },
      businesses: {
        label: "Mga negosyong ginagamit mo",
        hint: "Mga alok at sagot sa mga request mo bilang customer.",
      },
      discover: {
        label: "Tuklasin",
        hint: "Mga gawaing tugma sa interes mo, at mga taong nakakasalubong mo.",
      },
      communities: {
        label: "Mga Komunidad",
        hint: "Aktibidad sa mga komunidad na pinamumunuan mo.",
      },
      business_owner: {
        label: "Ang negosyo mo",
        hint: "Mga alerto sa pagpapatakbo ng negosyo mo. Hiwalay sa Mga negosyong ginagamit mo.",
      },
    },
    group: {
      plans_invitations: {
        label: "Mga imbitasyon",
        hint: "May nag-imbita sa iyo sa isang gathering o plano.",
      },
      plans_changes: {
        label: "Mga pagbabago",
        hint: "Naaprubahan ka, nagbago ang oras o lugar, nakumpirma o nakansela ang plano.",
      },
      plans_reminders: {
        label: "Mga paalala",
        hint: "Bago magsimula ang isang pupuntahan mo.",
      },
      friends_activity: {
        label: "Aktibidad ng kaibigan",
        hint: "Mga friend request, may kaibigang sumali sa gathering, bagong stories.",
      },
      friends_occasions: {
        label: "Kaarawan at okasyon",
        hint: "Kaarawan ng kaibigan o paparating na okasyon.",
      },
      dating: {
        label: "Mga match at mensahe",
        hint: "Bagong match, mensahe, kaway at tawag.",
      },
      business_offers: {
        label: "Mga alok",
        hint: "May negosyong nag-alok sa iyo o nag-post ng update.",
      },
      business_responses: {
        label: "Mga sagot sa request",
        hint: "Tinanggihan, binawi o kinumpirma ng negosyo ang booking mo.",
      },
      discover_recommendations: {
        label: "Mga rekomendasyon",
        hint: "Mga gathering at lugar sa malapit na tugma sa interes mo.",
      },
      discover_nearby_people: {
        label: "Mga taong nakakasalubong mo",
        hint: "Kapag may nakasalubong kang tao sa malapit.",
      },
      communities: {
        label: "Aktibidad ng komunidad",
        hint: "Lumalaki ang demand o may pagbabago sa komunidad na pinamumunuan mo.",
      },
    },
    toggleA11y: "Abisuhan ako tungkol sa {label}",
  },
  ru: {
    area: {
      plans: {
        label: "Планы",
        hint: "Приглашения, изменения и напоминания о планах, в которых вы участвуете.",
      },
      friends: {
        label: "Друзья",
        hint: "Заявки в друзья, чем заняты друзья, дни рождения.",
      },
      dating: {
        label: "Знакомства",
        hint: "Совпадения, сообщения, приветы и звонки.",
      },
      businesses: {
        label: "Заведения, которыми вы пользуетесь",
        hint: "Предложения и ответы на заявки, которые вы отправили как клиент.",
      },
      discover: {
        label: "Открыть",
        hint: "Занятия по вашим интересам и люди, с которыми вы пересекаетесь.",
      },
      communities: {
        label: "Сообщества",
        hint: "Активность в сообществах, которые вы ведёте.",
      },
      business_owner: {
        label: "Ваш бизнес",
        hint: "Уведомления для ведения вашего бизнеса. Отдельно от «Заведения, которыми вы пользуетесь».",
      },
    },
    group: {
      plans_invitations: {
        label: "Приглашения",
        hint: "Вас приглашают на встречу или в план.",
      },
      plans_changes: {
        label: "Изменения",
        hint: "Вас одобрили, изменились время или место, план подтверждён или отменён.",
      },
      plans_reminders: {
        label: "Напоминания",
        hint: "Перед началом того, куда вы идёте.",
      },
      friends_activity: {
        label: "Активность друзей",
        hint: "Заявки в друзья, друг присоединился к встрече, новые истории.",
      },
      friends_occasions: {
        label: "Дни рождения и события",
        hint: "День рождения друга или приближающееся событие.",
      },
      dating: {
        label: "Совпадения и сообщения",
        hint: "Новые совпадения, сообщения, приветы и звонки.",
      },
      business_offers: {
        label: "Предложения",
        hint: "Бизнес делает вам предложение или публикует новость.",
      },
      business_responses: {
        label: "Ответы на запросы",
        hint: "Бизнес отказывает, отзывает предложение или подтверждает бронь.",
      },
      discover_recommendations: {
        label: "Рекомендации",
        hint: "Встречи и места рядом, подходящие под ваши интересы.",
      },
      discover_nearby_people: {
        label: "Люди, с которыми вы пересекаетесь",
        hint: "Когда вы пересекаетесь с кем-то рядом.",
      },
      communities: {
        label: "Активность сообщества",
        hint: "Растёт спрос в сообществе, которое вы ведёте, или оно меняется.",
      },
    },
    toggleA11y: "Уведомлять о: {label}",
  },
  ko: {
    area: {
      plans: {
        label: "계획",
        hint: "참여 중인 계획의 초대, 변경, 알림.",
      },
      friends: {
        label: "친구",
        hint: "친구 요청, 친구 소식, 생일.",
      },
      dating: {
        label: "데이트",
        hint: "매치, 메시지, 인사, 통화.",
      },
      businesses: {
        label: "이용하는 업체",
        hint: "고객으로서 보낸 요청에 대한 혜택과 답변.",
      },
      discover: {
        label: "탐색",
        hint: "관심사에 맞는 할 일과 마주친 사람들.",
      },
      communities: {
        label: "커뮤니티",
        hint: "운영 중인 커뮤니티의 활동.",
      },
      business_owner: {
        label: "내 업체",
        hint: "업체 운영 알림. ‘이용하는 업체’와 별개입니다.",
      },
    },
    group: {
      plans_invitations: {
        label: "초대",
        hint: "누군가 모임이나 계획에 초대했을 때.",
      },
      plans_changes: {
        label: "변경",
        hint: "승인되었거나, 시간·장소가 바뀌었거나, 계획이 확정·취소되었을 때.",
      },
      plans_reminders: {
        label: "알림",
        hint: "참여하는 일정이 시작되기 전.",
      },
      friends_activity: {
        label: "친구 활동",
        hint: "친구 요청, 친구의 모임 참여, 새 스토리.",
      },
      friends_occasions: {
        label: "생일과 기념일",
        hint: "친구의 생일이나 다가오는 기념일.",
      },
      dating: {
        label: "매치와 메시지",
        hint: "새 매치, 메시지, 인사, 통화.",
      },
      business_offers: {
        label: "제안",
        hint: "업체가 제안을 보내거나 소식을 올렸을 때.",
      },
      business_responses: {
        label: "요청 답변",
        hint: "업체가 거절, 철회하거나 예약을 확정했을 때.",
      },
      discover_recommendations: {
        label: "추천",
        hint: "관심사에 맞는 주변 모임과 장소.",
      },
      discover_nearby_people: {
        label: "마주친 사람",
        hint: "주변에서 누군가와 마주쳤을 때.",
      },
      communities: {
        label: "커뮤니티 활동",
        hint: "운영 중인 커뮤니티의 수요 증가나 변경.",
      },
    },
    toggleA11y: "{label} 알림 받기",
  },
};
