// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/optionVocab.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    budget: {
      any: "No preference",
      cheap: "Cheap · $",
      moderate: "Moderate · $$",
      special: "Special occasion · $$$",
    },
    experience: {
      simple: "Keep it simple",
      special: "Make it special",
      go_all_out: "Go all out",
    },
    date: {
      today: "Today",
      tonight: "Tonight",
      tomorrow: "Tomorrow",
      weekend: "This weekend",
      flexible: "I'm flexible",
    },
    nearYourGathering: "Near your gathering",
  },
  es: {
    budget: {
      any: "Sin preferencia",
      cheap: "Económico · $",
      moderate: "Moderado · $$",
      special: "Ocasión especial · $$$",
    },
    experience: {
      simple: "Algo sencillo",
      special: "Algo especial",
      go_all_out: "Por todo lo alto",
    },
    date: {
      today: "Hoy",
      tonight: "Esta noche",
      tomorrow: "Mañana",
      weekend: "Este fin de semana",
      flexible: "Me da igual",
    },
    nearYourGathering: "Cerca de tu reunión",
  },
  de: {
    budget: {
      any: "Egal",
      cheap: "Günstig · $",
      moderate: "Mittel · $$",
      special: "Besonderer Anlass · $$$",
    },
    experience: {
      simple: "Einfach halten",
      special: "Besonders machen",
      go_all_out: "Richtig groß",
    },
    date: {
      today: "Heute",
      tonight: "Heute Abend",
      tomorrow: "Morgen",
      weekend: "Dieses Wochenende",
      flexible: "Ich bin flexibel",
    },
    nearYourGathering: "In der Nähe deines Treffens",
  },
  fr: {
    budget: {
      any: "Sans préférence",
      cheap: "Bon marché · $",
      moderate: "Modéré · $$",
      special: "Occasion spéciale · $$$",
    },
    experience: {
      simple: "Rester simple",
      special: "Rendre ça spécial",
      go_all_out: "Mettre le paquet",
    },
    date: {
      today: "Aujourd'hui",
      tonight: "Ce soir",
      tomorrow: "Demain",
      weekend: "Ce week-end",
      flexible: "Je suis flexible",
    },
    nearYourGathering: "Près de votre rencontre",
  },
  pt: {
    budget: {
      any: "Sem preferência",
      cheap: "Barato · $",
      moderate: "Moderado · $$",
      special: "Ocasião especial · $$$",
    },
    experience: {
      simple: "Algo simples",
      special: "Algo especial",
      go_all_out: "Caprichar ao máximo",
    },
    date: {
      today: "Hoje",
      tonight: "Hoje à noite",
      tomorrow: "Amanhã",
      weekend: "Neste fim de semana",
      flexible: "Sou flexível",
    },
    nearYourGathering: "Perto do seu encontro",
  },
  ht: {
    budget: {
      any: "Nenpòt",
      cheap: "Bon mache · $",
      moderate: "Mwayen · $$",
      special: "Okazyon espesyal · $$$",
    },
    experience: {
      simple: "Fè l senp",
      special: "Fè l espesyal",
      go_all_out: "Fè l gwo",
    },
    date: {
      today: "Jodi a",
      tonight: "Aswè a",
      tomorrow: "Demen",
      weekend: "Wikenn sa a",
      flexible: "M fleksib",
    },
    nearYourGathering: "Toupre rasanbleman w",
  },
  zh: {
    budget: {
      any: "不限",
      cheap: "实惠 · $",
      moderate: "适中 · $$",
      special: "特别场合 · $$$",
    },
    experience: {
      simple: "简单就好",
      special: "来点特别的",
      go_all_out: "全力以赴",
    },
    date: {
      today: "今天",
      tonight: "今晚",
      tomorrow: "明天",
      weekend: "这个周末",
      flexible: "时间灵活",
    },
    nearYourGathering: "在你的聚会附近",
  },
  vi: {
    budget: {
      any: "Không ưu tiên",
      cheap: "Rẻ · $",
      moderate: "Vừa phải · $$",
      special: "Dịp đặc biệt · $$$",
    },
    experience: {
      simple: "Đơn giản thôi",
      special: "Làm cho đặc biệt",
      go_all_out: "Thật hoành tráng",
    },
    date: {
      today: "Hôm nay",
      tonight: "Tối nay",
      tomorrow: "Ngày mai",
      weekend: "Cuối tuần này",
      flexible: "Linh hoạt",
    },
    nearYourGathering: "Gần buổi gặp mặt của bạn",
  },
  tl: {
    budget: {
      any: "Kahit ano",
      cheap: "Mura · $",
      moderate: "Katamtaman · $$",
      special: "Espesyal na okasyon · $$$",
    },
    experience: {
      simple: "Simple lang",
      special: "Gawing espesyal",
      go_all_out: "Todo-todo na",
    },
    date: {
      today: "Ngayon",
      tonight: "Mamayang gabi",
      tomorrow: "Bukas",
      weekend: "Ngayong weekend",
      flexible: "Flexible ako",
    },
    nearYourGathering: "Malapit sa pagtitipon mo",
  },
  ru: {
    budget: {
      any: "Без разницы",
      cheap: "Недорого · $",
      moderate: "Средне · $$",
      special: "Особый случай · $$$",
    },
    experience: {
      simple: "Попроще",
      special: "Что-то особенное",
      go_all_out: "С размахом",
    },
    date: {
      today: "Сегодня",
      tonight: "Сегодня вечером",
      tomorrow: "Завтра",
      weekend: "На этих выходных",
      flexible: "Могу в любое время",
    },
    nearYourGathering: "Рядом с местом встречи",
  },
  ko: {
    budget: {
      any: "상관없음",
      cheap: "저렴 · $",
      moderate: "보통 · $$",
      special: "특별한 날 · $$$",
    },
    experience: {
      simple: "간단하게",
      special: "특별하게",
      go_all_out: "제대로 크게",
    },
    date: {
      today: "오늘",
      tonight: "오늘 밤",
      tomorrow: "내일",
      weekend: "이번 주말",
      flexible: "언제든 괜찮아요",
    },
    nearYourGathering: "모임 장소 근처",
  },
};
