// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/relationship.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    hub: {
      intro: "Everything for building and reflecting on a relationship, in one place.",
      together: {
        title: "With Someone",
        subtitle: "Shared tools, used together with a specific match.",
      },
      onYourOwn: {
        title: "On Your Own",
        subtitle: "Private reflection — nothing here is shared with a match.",
      },
      row: {
        tools: {
          label: "Relationship Tools",
          a11y: "Relationship tools shared with a specific match",
        },
        vault: {
          label: "Memory Vault",
          a11y: "Memory vault, memories saved with your matches",
        },
        rehearsal: {
          label: "Rehearsal Room",
          a11y: "Rehearsal Room, practice hard conversations",
        },
        chemistry: {
          label: "Chemistry Diary",
          a11y: "Your chemistry diary",
        },
        goodbye: {
          label: "Private Reflections",
          a11y: "Your private reflections",
        },
        legacy: {
          label: "Relationship Wisdom",
          a11y: "Relationship wisdom library",
        },
        kit: {
          label: "Toolkit",
          a11y: "Relationship toolkit",
        },
      },
    },
    tools: {
      loading: "Loading relationship tools...",
      loadError: "Couldn't load your relationship tools.",
      intro: "These tools are shared with a specific match — pick who you want to use one with.",
      meetPeopleA11y: "Meet people",
      meetPeople: "Meet People →",
      withA11y: "Relationship tools with {name}",
      someone: "Someone",
      toolsWith: "Tools with {name}",
    },
    kit: {
      expandA11y: "{title}, double tap to expand",
      collapseA11y: "{title}, double tap to collapse",
      hard_conversation: {
        "1": "Pick a real moment, not mid-argument — ask \"can we talk about something later tonight?\" rather than diving in when either of you is already upset.",
        "2": "Start with what you need, not what they did wrong: \"I need to feel included in weekend plans\" lands differently than \"you never include me.\"",
        "3": "Expect it to feel awkward at first. That's normal, not a sign it's going badly.",
      },
      apologize: {
        "1": "Name the specific thing, not a vague feeling: \"I dismissed how you felt earlier\" beats \"sorry you're upset.\"",
        "2": "Skip the \"but\" — an apology followed by an explanation often lands as an excuse, even when that's not the intent.",
        "3": "Ask what would actually help, rather than assuming you already know.",
      },
      rebuild_trust: {
        "1": "Trust rebuilds through small, consistent follow-through over time — not one grand gesture.",
        "2": "Be patient with their caution. It's not punishment, it's a nervous system that got hurt and is being careful.",
        "3": "Consider naming it directly: \"What would help you feel more sure of me right now?\"",
      },
      resentment: {
        "1": "Resentment usually means an unspoken need. Try to name the need underneath it, not just the frustration.",
        "2": "Small things add up. If something feels 'too small to mention,' that's often exactly the thing worth mentioning early.",
        "3": "Consider writing it out privately first — sometimes what comes out is different from what you thought you felt.",
      },
      reconnecting: {
        "1": "Start smaller than feels necessary — a short, low-stakes check-in often works better than a big \"we need to talk.\"",
        "2": "Curiosity helps more than assumptions: ask what's been going on for them, rather than guessing.",
        "3": "Physical presence matters too — sometimes reconnecting starts with just being in the same room, no agenda.",
      },
    },
  },
  es: {
    hub: {
      intro: "Todo para construir una relación y reflexionar sobre ella, en un solo lugar.",
      together: {
        title: "Con alguien",
        subtitle: "Herramientas compartidas, para usar junto a un match concreto.",
      },
      onYourOwn: {
        title: "Por tu cuenta",
        subtitle: "Reflexión privada: nada de esto se comparte con un match.",
      },
      row: {
        tools: {
          label: "Herramientas de pareja",
          a11y: "Herramientas de pareja compartidas con un match concreto",
        },
        vault: {
          label: "Baúl de recuerdos",
          a11y: "Baúl de recuerdos, recuerdos guardados con tus matches",
        },
        rehearsal: {
          label: "Sala de ensayo",
          a11y: "Sala de ensayo, practica conversaciones difíciles",
        },
        chemistry: {
          label: "Diario de química",
          a11y: "Tu diario de química",
        },
        goodbye: {
          label: "Reflexiones privadas",
          a11y: "Tus reflexiones privadas",
        },
        legacy: {
          label: "Sabiduría de relaciones",
          a11y: "Biblioteca de sabiduría de relaciones",
        },
        kit: {
          label: "Herramientas",
          a11y: "Herramientas para la relación",
        },
      },
    },
    tools: {
      loading: "Cargando herramientas de pareja...",
      loadError: "No pudimos cargar tus herramientas de pareja.",
      intro: "Estas herramientas se comparten con un match concreto: elige con quién quieres usarlas.",
      meetPeopleA11y: "Conocer gente",
      meetPeople: "Conocer gente →",
      withA11y: "Herramientas de pareja con {name}",
      someone: "Alguien",
      toolsWith: "Herramientas con {name}",
    },
    kit: {
      expandA11y: "{title}, toca dos veces para abrir",
      collapseA11y: "{title}, toca dos veces para cerrar",
      hard_conversation: {
        "1": "Elige un buen momento, no en plena discusión: pregunta «¿podemos hablar de algo más tarde esta noche?» en vez de lanzarte cuando alguno ya está molesto.",
        "2": "Empieza por lo que necesitas, no por lo que hizo mal: «necesito sentirme incluido en los planes del fin de semana» se recibe distinto que «nunca me incluyes».",
        "3": "Espera que al principio resulte incómodo. Es normal, no una señal de que vaya mal.",
      },
      apologize: {
        "1": "Nombra lo concreto, no un sentimiento vago: «antes no tomé en cuenta cómo te sentías» es mejor que «siento que estés molesto».",
        "2": "Evita el «pero»: una disculpa seguida de una explicación suele sonar a excusa, aunque no sea la intención.",
        "3": "Pregunta qué ayudaría de verdad, en lugar de dar por hecho que ya lo sabes.",
      },
      rebuild_trust: {
        "1": "La confianza se reconstruye con cumplimientos pequeños y constantes a lo largo del tiempo, no con un gran gesto.",
        "2": "Ten paciencia con su cautela. No es un castigo, es un sistema nervioso que salió herido y se está cuidando.",
        "3": "Plantéate decirlo directamente: «¿Qué te ayudaría a sentirte más seguro de mí ahora mismo?»",
      },
      resentment: {
        "1": "El resentimiento suele esconder una necesidad no dicha. Intenta nombrar la necesidad que hay debajo, no solo la frustración.",
        "2": "Las cosas pequeñas se acumulan. Si algo parece «demasiado pequeño para mencionarlo», a menudo es justo lo que vale la pena decir pronto.",
        "3": "Plantéate escribirlo primero en privado: a veces lo que sale es distinto de lo que creías sentir.",
      },
      reconnecting: {
        "1": "Empieza con algo más pequeño de lo que parece necesario: una charla breve y sin presión suele funcionar mejor que un gran «tenemos que hablar».",
        "2": "La curiosidad ayuda más que las suposiciones: pregunta qué le ha estado pasando, en lugar de adivinar.",
        "3": "La presencia física también importa: a veces reconectar empieza simplemente por estar en la misma habitación, sin agenda.",
      },
    },
  },
  de: {
    hub: {
      intro: "Alles, um eine Beziehung aufzubauen und über sie nachzudenken, an einem Ort.",
      together: {
        title: "Mit jemandem",
        subtitle: "Gemeinsame Werkzeuge, zusammen mit einem bestimmten Match genutzt.",
      },
      onYourOwn: {
        title: "Für dich allein",
        subtitle: "Private Reflexion – nichts davon wird mit einem Match geteilt.",
      },
      row: {
        tools: {
          label: "Beziehungswerkzeuge",
          a11y: "Beziehungswerkzeuge, die du mit einem bestimmten Match teilst",
        },
        vault: {
          label: "Erinnerungstresor",
          a11y: "Erinnerungstresor, mit deinen Matches gespeicherte Erinnerungen",
        },
        rehearsal: {
          label: "Probenraum",
          a11y: "Probenraum, schwierige Gespräche üben",
        },
        chemistry: {
          label: "Chemie-Tagebuch",
          a11y: "Dein Chemie-Tagebuch",
        },
        goodbye: {
          label: "Private Reflexionen",
          a11y: "Deine privaten Reflexionen",
        },
        legacy: {
          label: "Beziehungsweisheiten",
          a11y: "Bibliothek der Beziehungsweisheiten",
        },
        kit: {
          label: "Werkzeugkasten",
          a11y: "Werkzeugkasten für Beziehungen",
        },
      },
    },
    tools: {
      loading: "Beziehungswerkzeuge werden geladen...",
      loadError: "Deine Beziehungswerkzeuge konnten nicht geladen werden.",
      intro: "Diese Werkzeuge teilst du mit einem bestimmten Match – wähle, mit wem du eines nutzen möchtest.",
      meetPeopleA11y: "Leute kennenlernen",
      meetPeople: "Leute kennenlernen →",
      withA11y: "Beziehungswerkzeuge mit {name}",
      someone: "Jemand",
      toolsWith: "Werkzeuge mit {name}",
    },
    kit: {
      expandA11y: "{title}, zum Aufklappen doppelt tippen",
      collapseA11y: "{title}, zum Zuklappen doppelt tippen",
      hard_conversation: {
        "1": "Such dir einen guten Moment, nicht mitten im Streit – frag „Können wir heute Abend über etwas reden?“, statt loszulegen, wenn einer von euch schon aufgebracht ist.",
        "2": "Beginne mit dem, was du brauchst, nicht mit dem, was die andere Person falsch gemacht hat: „Ich möchte bei Wochenendplänen dabei sein“ kommt anders an als „Du beziehst mich nie ein“.",
        "3": "Rechne damit, dass es sich anfangs komisch anfühlt. Das ist normal und kein Zeichen, dass es schlecht läuft.",
      },
      apologize: {
        "1": "Benenne das Konkrete, kein vages Gefühl: „Ich habe vorhin übergangen, wie du dich gefühlt hast“ ist besser als „Tut mir leid, dass du verärgert bist“.",
        "2": "Lass das „aber“ weg – eine Entschuldigung mit anschließender Erklärung wirkt oft wie eine Ausrede, auch wenn das nicht die Absicht ist.",
        "3": "Frag, was wirklich helfen würde, statt anzunehmen, dass du es schon weißt.",
      },
      rebuild_trust: {
        "1": "Vertrauen wächst durch kleine, beständige Verlässlichkeit über die Zeit – nicht durch eine große Geste.",
        "2": "Hab Geduld mit der Vorsicht der anderen Person. Das ist keine Strafe, sondern ein verletztes Nervensystem, das aufpasst.",
        "3": "Sprich es vielleicht direkt an: „Was würde dir gerade helfen, dir meiner sicherer zu sein?“",
      },
      resentment: {
        "1": "Groll bedeutet meist ein unausgesprochenes Bedürfnis. Versuch, das Bedürfnis dahinter zu benennen, nicht nur den Frust.",
        "2": "Kleinigkeiten summieren sich. Wenn sich etwas „zu klein zum Ansprechen“ anfühlt, ist es oft genau das, was man früh ansprechen sollte.",
        "3": "Schreib es vielleicht zuerst für dich auf – manchmal kommt etwas anderes heraus, als du dachtest zu fühlen.",
      },
      reconnecting: {
        "1": "Fang kleiner an, als es nötig scheint – ein kurzes, lockeres Nachfragen funktioniert oft besser als ein großes „Wir müssen reden“.",
        "2": "Neugier hilft mehr als Annahmen: Frag, was bei der anderen Person los war, statt zu raten.",
        "3": "Auch körperliche Nähe zählt – manchmal beginnt die Wiederannäherung einfach damit, ohne Plan im selben Raum zu sein.",
      },
    },
  },
  fr: {
    hub: {
      intro: "Tout pour construire une relation et y réfléchir, au même endroit.",
      together: {
        title: "Avec quelqu’un",
        subtitle: "Des outils partagés, à utiliser avec un match en particulier.",
      },
      onYourOwn: {
        title: "Pour toi",
        subtitle: "Réflexion privée : rien ici n’est partagé avec un match.",
      },
      row: {
        tools: {
          label: "Outils pour le couple",
          a11y: "Outils pour le couple partagés avec un match en particulier",
        },
        vault: {
          label: "Coffre à souvenirs",
          a11y: "Coffre à souvenirs, souvenirs enregistrés avec tes matchs",
        },
        rehearsal: {
          label: "Salle de répétition",
          a11y: "Salle de répétition, pour t’entraîner aux conversations difficiles",
        },
        chemistry: {
          label: "Journal de l’alchimie",
          a11y: "Ton journal de l’alchimie",
        },
        goodbye: {
          label: "Réflexions privées",
          a11y: "Tes réflexions privées",
        },
        legacy: {
          label: "Sagesse du couple",
          a11y: "Bibliothèque de sagesse du couple",
        },
        kit: {
          label: "Boîte à outils",
          a11y: "Boîte à outils pour la relation",
        },
      },
    },
    tools: {
      loading: "Chargement des outils pour le couple...",
      loadError: "Impossible de charger tes outils pour le couple.",
      intro: "Ces outils se partagent avec un match en particulier : choisis avec qui tu veux en utiliser un.",
      meetPeopleA11y: "Rencontrer des gens",
      meetPeople: "Rencontrer des gens →",
      withA11y: "Outils pour le couple avec {name}",
      someone: "Quelqu’un",
      toolsWith: "Outils avec {name}",
    },
    kit: {
      expandA11y: "{title}, touche deux fois pour ouvrir",
      collapseA11y: "{title}, touche deux fois pour fermer",
      hard_conversation: {
        "1": "Choisis un vrai bon moment, pas en pleine dispute : demande « on peut parler de quelque chose ce soir ? » plutôt que de te lancer quand l’un de vous est déjà contrarié.",
        "2": "Commence par ce dont tu as besoin, pas par ce que l’autre a mal fait : « j’ai besoin de me sentir inclus dans les plans du week-end » passe autrement que « tu ne m’inclus jamais ».",
        "3": "Attends-toi à ce que ce soit gênant au début. C’est normal, pas le signe que ça se passe mal.",
      },
      apologize: {
        "1": "Nomme le point précis, pas un sentiment vague : « j’ai balayé ce que tu ressentais tout à l’heure » vaut mieux que « désolé que tu sois contrarié ».",
        "2": "Évite le « mais » : des excuses suivies d’une explication sonnent souvent comme une justification, même sans le vouloir.",
        "3": "Demande ce qui aiderait vraiment, plutôt que de supposer que tu le sais déjà.",
      },
      rebuild_trust: {
        "1": "La confiance se reconstruit par de petits engagements tenus dans la durée, pas par un grand geste.",
        "2": "Sois patient avec sa prudence. Ce n’est pas une punition, c’est un système nerveux qui a été blessé et qui fait attention.",
        "3": "Pense à le dire directement : « Qu’est-ce qui t’aiderait à te sentir plus sûr de moi en ce moment ? »",
      },
      resentment: {
        "1": "La rancœur cache souvent un besoin non exprimé. Essaie de nommer le besoin en dessous, pas seulement la frustration.",
        "2": "Les petites choses s’accumulent. Si quelque chose semble « trop petit pour en parler », c’est souvent justement ce qu’il faut dire tôt.",
        "3": "Pense à l’écrire d’abord pour toi : parfois ce qui sort est différent de ce que tu croyais ressentir.",
      },
      reconnecting: {
        "1": "Commence plus petit que ça ne semble nécessaire : un bref échange sans enjeu marche souvent mieux qu’un grand « il faut qu’on parle ».",
        "2": "La curiosité aide plus que les suppositions : demande-lui ce qu’il vit en ce moment, au lieu de deviner.",
        "3": "La présence physique compte aussi : parfois, se retrouver commence simplement par être dans la même pièce, sans rien prévoir.",
      },
    },
  },
  pt: {
    hub: {
      intro: "Tudo para construir um relacionamento e refletir sobre ele, em um só lugar.",
      together: {
        title: "Com alguém",
        subtitle: "Ferramentas compartilhadas, usadas junto com um match específico.",
      },
      onYourOwn: {
        title: "Só você",
        subtitle: "Reflexão privada: nada aqui é compartilhado com um match.",
      },
      row: {
        tools: {
          label: "Ferramentas do relacionamento",
          a11y: "Ferramentas do relacionamento compartilhadas com um match específico",
        },
        vault: {
          label: "Cofre de memórias",
          a11y: "Cofre de memórias, lembranças salvas com seus matches",
        },
        rehearsal: {
          label: "Sala de ensaio",
          a11y: "Sala de ensaio, pratique conversas difíceis",
        },
        chemistry: {
          label: "Diário de química",
          a11y: "Seu diário de química",
        },
        goodbye: {
          label: "Reflexões privadas",
          a11y: "Suas reflexões privadas",
        },
        legacy: {
          label: "Sabedoria de relacionamento",
          a11y: "Biblioteca de sabedoria de relacionamento",
        },
        kit: {
          label: "Ferramentas",
          a11y: "Ferramentas para o relacionamento",
        },
      },
    },
    tools: {
      loading: "Carregando ferramentas do relacionamento...",
      loadError: "Não foi possível carregar suas ferramentas do relacionamento.",
      intro: "Essas ferramentas são compartilhadas com um match específico: escolha com quem quer usar.",
      meetPeopleA11y: "Conhecer pessoas",
      meetPeople: "Conhecer pessoas →",
      withA11y: "Ferramentas do relacionamento com {name}",
      someone: "Alguém",
      toolsWith: "Ferramentas com {name}",
    },
    kit: {
      expandA11y: "{title}, toque duas vezes para abrir",
      collapseA11y: "{title}, toque duas vezes para fechar",
      hard_conversation: {
        "1": "Escolha um bom momento, não no meio de uma briga: pergunte “podemos conversar sobre uma coisa mais tarde hoje?” em vez de começar quando um de vocês já está chateado.",
        "2": "Comece pelo que você precisa, não pelo que a pessoa fez de errado: “preciso me sentir incluído nos planos do fim de semana” soa diferente de “você nunca me inclui”.",
        "3": "Espere que seja estranho no começo. Isso é normal, não um sinal de que está dando errado.",
      },
      apologize: {
        "1": "Diga a coisa específica, não um sentimento vago: “ignorei o que você sentiu mais cedo” é melhor que “desculpe se você ficou chateado”.",
        "2": "Pule o “mas”: um pedido de desculpas seguido de explicação costuma soar como desculpa esfarrapada, mesmo sem intenção.",
        "3": "Pergunte o que realmente ajudaria, em vez de supor que você já sabe.",
      },
      rebuild_trust: {
        "1": "A confiança se reconstrói com pequenas atitudes consistentes ao longo do tempo, não com um grande gesto.",
        "2": "Tenha paciência com a cautela da pessoa. Não é castigo, é um sistema nervoso que se machucou e está se protegendo.",
        "3": "Pense em falar diretamente: “O que te ajudaria a se sentir mais seguro comigo agora?”",
      },
      resentment: {
        "1": "Ressentimento geralmente indica uma necessidade não dita. Tente nomear a necessidade por trás, não só a frustração.",
        "2": "Coisas pequenas se acumulam. Se algo parece “pequeno demais para mencionar”, muitas vezes é exatamente o que vale a pena dizer cedo.",
        "3": "Pense em escrever primeiro só para você: às vezes o que sai é diferente do que você achava que sentia.",
      },
      reconnecting: {
        "1": "Comece menor do que parece necessário: uma conversa curta e leve costuma funcionar melhor que um grande “precisamos conversar”.",
        "2": "Curiosidade ajuda mais que suposições: pergunte o que tem acontecido com a pessoa, em vez de adivinhar.",
        "3": "A presença física também importa: às vezes reconectar começa só por estar no mesmo cômodo, sem pauta.",
      },
    },
  },
  ht: {
    hub: {
      intro: "Tout sa ou bezwen pou bati yon relasyon epi reflechi sou li, nan yon sèl kote.",
      together: {
        title: "Ak yon moun",
        subtitle: "Zouti pataje, pou itilize ansanm ak yon match espesifik.",
      },
      onYourOwn: {
        title: "Pou kont ou",
        subtitle: "Refleksyon prive — anyen isit la pa pataje ak yon match.",
      },
      row: {
        tools: {
          label: "Zouti relasyon",
          a11y: "Zouti relasyon ou pataje ak yon match espesifik",
        },
        vault: {
          label: "Kòf souvni",
          a11y: "Kòf souvni, souvni ou anrejistre ak match ou yo",
        },
        rehearsal: {
          label: "Sal repetisyon",
          a11y: "Sal repetisyon, pratike konvèsasyon difisil",
        },
        chemistry: {
          label: "Jounal chimi",
          a11y: "Jounal chimi ou",
        },
        goodbye: {
          label: "Refleksyon prive yo",
          a11y: "Refleksyon prive ou yo",
        },
        legacy: {
          label: "Sajès relasyon",
          a11y: "Bibliyotèk sajès relasyon",
        },
        kit: {
          label: "Zouti",
          a11y: "Zouti pou relasyon",
        },
      },
    },
    tools: {
      loading: "N ap chaje zouti relasyon yo...",
      loadError: "Nou pa t ka chaje zouti relasyon ou yo.",
      intro: "Zouti sa yo pataje ak yon match espesifik — chwazi ak kiyès ou vle itilize youn.",
      meetPeopleA11y: "Rankontre moun",
      meetPeople: "Rankontre moun →",
      withA11y: "Zouti relasyon ak {name}",
      someone: "Yon moun",
      toolsWith: "Zouti ak {name}",
    },
    kit: {
      expandA11y: "{title}, tape de fwa pou louvri",
      collapseA11y: "{title}, tape de fwa pou fèmen",
      hard_conversation: {
        "1": "Chwazi yon bon moman, pa nan mitan yon diskisyon — mande «èske nou ka pale sou yon bagay pita aswè a?» olye w lanse lè youn nan nou deja fache.",
        "2": "Kòmanse ak sa ou bezwen, pa ak sa l fè mal: «mwen bezwen santi m enkli nan plan wikenn yo» pa sonnen menm jan ak «ou pa janm enkli m».",
        "3": "Atann ou pou sa santi l jennan nan kòmansman. Se nòmal, se pa yon siy li pa mache.",
      },
      apologize: {
        "1": "Nome bagay presi a, pa yon santiman vag: «mwen pa t pran an konsiderasyon jan ou te santi w talè a» pi bon pase «dezole ou fache».",
        "2": "Sote «men» an — yon eskiz ki swiv ak yon eksplikasyon souvan sonnen tankou yon ekskiz, menm si se pa entansyon an.",
        "3": "Mande sa k ta ede vre, olye ou sipoze ou deja konnen.",
      },
      rebuild_trust: {
        "1": "Konfyans rebati ak ti aksyon ki konstan sou tan — pa ak yon sèl gwo jès.",
        "2": "Pran pasyans ak prekosyon l. Se pa yon pinisyon, se yon sistèm nève ki te blese epi k ap fè atansyon.",
        "3": "Konsidere di l dirèkteman: «Kisa k ta ede w santi w pi si de mwen kounye a?»",
      },
      resentment: {
        "1": "Rankin souvan vle di yon bezwen ki pa di. Eseye nome bezwen ki anba a, pa sèlman fristrasyon an.",
        "2": "Ti bagay yo fè gwo. Si yon bagay sanble «twò piti pou pale de li», souvan se egzakteman sa ki vo di bonè.",
        "3": "Konsidere ekri l an prive anvan — pafwa sa k soti a diferan de sa ou te panse ou santi.",
      },
      reconnecting: {
        "1": "Kòmanse pi piti pase sa sanble nesesè — yon ti pale kout, san presyon souvan mache pi byen pase yon gwo «nou bezwen pale».",
        "2": "Kiryozite ede plis pase sipozisyon: mande sa k t ap pase pou li, olye ou devine.",
        "3": "Prezans fizik konte tou — pafwa rekonekte kòmanse jis lè nou nan menm pyès la, san okenn plan.",
      },
    },
  },
  zh: {
    hub: {
      intro: "建立和反思一段关系所需的一切，都在这里。",
      together: {
        title: "和某人一起",
        subtitle: "共享工具，与特定的配对对象一起使用。",
      },
      onYourOwn: {
        title: "独自一人",
        subtitle: "私人反思——这里的内容都不会与配对对象分享。",
      },
      row: {
        tools: {
          label: "感情工具",
          a11y: "与特定配对对象共享的感情工具",
        },
        vault: {
          label: "回忆保险箱",
          a11y: "回忆保险箱，与配对对象保存的回忆",
        },
        rehearsal: {
          label: "排练室",
          a11y: "排练室，练习困难的对话",
        },
        chemistry: {
          label: "默契日记",
          a11y: "你的默契日记",
        },
        goodbye: {
          label: "私人反思",
          a11y: "你的私人反思",
        },
        legacy: {
          label: "感情智慧",
          a11y: "感情智慧库",
        },
        kit: {
          label: "工具箱",
          a11y: "感情工具箱",
        },
      },
    },
    tools: {
      loading: "正在加载感情工具...",
      loadError: "无法加载你的感情工具。",
      intro: "这些工具需要与特定的配对对象共享——选择你想和谁一起使用。",
      meetPeopleA11y: "认识新朋友",
      meetPeople: "认识新朋友 →",
      withA11y: "与 {name} 的感情工具",
      someone: "某人",
      toolsWith: "与 {name} 的工具",
    },
    kit: {
      expandA11y: "{title}，双击展开",
      collapseA11y: "{title}，双击收起",
      hard_conversation: {
        "1": "选一个合适的时机，别在争吵中——问一句“今晚晚些时候我们能聊聊吗？”，而不是在某一方已经不高兴时直接开口。",
        "2": "从你的需要说起，而不是对方哪里做错：“我希望能参与周末的计划”和“你从来不带上我”听起来完全不同。",
        "3": "一开始会觉得别扭，这很正常，并不代表进展不顺。",
      },
      apologize: {
        "1": "说出具体的事，而不是模糊的感受：“我刚才忽视了你的感受”比“抱歉你不高兴了”要好。",
        "2": "别加“但是”——道歉后紧跟解释，往往听起来像借口，即使你并非此意。",
        "3": "问问什么才真正有帮助，而不是认为自己已经知道。",
      },
      rebuild_trust: {
        "1": "信任是通过长期、小而持续的兑现重建的——而不是一次盛大的举动。",
        "2": "对对方的谨慎多一点耐心。这不是惩罚，而是一个受过伤、正在小心的神经系统。",
        "3": "可以考虑直接问：“现在什么能让你对我更有把握？”",
      },
      resentment: {
        "1": "怨气通常意味着没说出口的需要。试着说出背后的需要，而不仅仅是不满。",
        "2": "小事会累积。如果某件事感觉“小到不值得提”，往往恰恰值得早点说。",
        "3": "可以先私下写下来——有时写出来的和你以为的感受并不一样。",
      },
      reconnecting: {
        "1": "从比看起来需要的更小的地方开始——简短、轻松的问候往往比郑重的“我们需要谈谈”更有效。",
        "2": "好奇比假设更有帮助：问问对方最近怎么样，而不是去猜。",
        "3": "身体上的陪伴也很重要——有时重新靠近，只是从毫无目的地待在同一个房间开始。",
      },
    },
  },
  vi: {
    hub: {
      intro: "Mọi thứ để vun đắp và suy ngẫm về một mối quan hệ, ở cùng một nơi.",
      together: {
        title: "Cùng một người",
        subtitle: "Công cụ dùng chung, sử dụng cùng một người kết đôi cụ thể.",
      },
      onYourOwn: {
        title: "Một mình",
        subtitle: "Suy ngẫm riêng tư — không có gì ở đây được chia sẻ với người kết đôi.",
      },
      row: {
        tools: {
          label: "Công cụ tình cảm",
          a11y: "Công cụ tình cảm dùng chung với một người kết đôi cụ thể",
        },
        vault: {
          label: "Kho kỷ niệm",
          a11y: "Kho kỷ niệm, những kỷ niệm lưu cùng người kết đôi",
        },
        rehearsal: {
          label: "Phòng tập dượt",
          a11y: "Phòng tập dượt, luyện tập những cuộc trò chuyện khó",
        },
        chemistry: {
          label: "Nhật ký hòa hợp",
          a11y: "Nhật ký hòa hợp của bạn",
        },
        goodbye: {
          label: "Những suy ngẫm riêng",
          a11y: "Những suy ngẫm riêng của bạn",
        },
        legacy: {
          label: "Kinh nghiệm tình cảm",
          a11y: "Thư viện kinh nghiệm tình cảm",
        },
        kit: {
          label: "Bộ công cụ",
          a11y: "Bộ công cụ cho mối quan hệ",
        },
      },
    },
    tools: {
      loading: "Đang tải công cụ tình cảm...",
      loadError: "Không thể tải công cụ tình cảm của bạn.",
      intro: "Những công cụ này được dùng chung với một người kết đôi cụ thể — hãy chọn người bạn muốn dùng cùng.",
      meetPeopleA11y: "Gặp gỡ mọi người",
      meetPeople: "Gặp gỡ mọi người →",
      withA11y: "Công cụ tình cảm với {name}",
      someone: "Ai đó",
      toolsWith: "Công cụ với {name}",
    },
    kit: {
      expandA11y: "{title}, chạm hai lần để mở",
      collapseA11y: "{title}, chạm hai lần để thu gọn",
      hard_conversation: {
        "1": "Chọn một thời điểm phù hợp, không phải giữa lúc cãi nhau — hãy hỏi “tối nay mình nói chuyện một chút được không?” thay vì lao vào khi một trong hai đang bực.",
        "2": "Bắt đầu bằng điều bạn cần, không phải điều họ làm sai: “Mình cần được cùng tham gia kế hoạch cuối tuần” nghe khác hẳn “Anh/em chẳng bao giờ rủ mình”.",
        "3": "Hãy chấp nhận rằng lúc đầu sẽ gượng gạo. Điều đó bình thường, không phải dấu hiệu mọi chuyện đang tệ đi.",
      },
      apologize: {
        "1": "Nói rõ điều cụ thể, không phải cảm giác mơ hồ: “Lúc nãy mình đã gạt đi cảm xúc của bạn” tốt hơn “xin lỗi vì bạn buồn”.",
        "2": "Bỏ chữ “nhưng” — một lời xin lỗi kèm lời giải thích thường nghe như bao biện, dù không cố ý.",
        "3": "Hỏi điều gì thật sự giúp được, thay vì cho rằng mình đã biết.",
      },
      rebuild_trust: {
        "1": "Niềm tin được xây lại bằng những việc nhỏ, đều đặn theo thời gian — không phải một hành động lớn.",
        "2": "Hãy kiên nhẫn với sự dè dặt của họ. Đó không phải trừng phạt, mà là một hệ thần kinh từng bị tổn thương đang cẩn trọng.",
        "3": "Hãy thử nói thẳng: “Lúc này điều gì giúp bạn yên tâm hơn về mình?”",
      },
      resentment: {
        "1": "Oán giận thường là một nhu cầu chưa nói ra. Hãy thử gọi tên nhu cầu bên dưới, không chỉ sự bực bội.",
        "2": "Chuyện nhỏ cộng lại thành lớn. Nếu điều gì đó có vẻ “quá nhỏ để nhắc”, thường đó chính là điều đáng nói sớm.",
        "3": "Hãy thử viết ra riêng trước — đôi khi điều viết ra khác với điều bạn tưởng mình cảm thấy.",
      },
      reconnecting: {
        "1": "Bắt đầu nhỏ hơn mức tưởng cần — một lần hỏi han ngắn, nhẹ nhàng thường hiệu quả hơn một câu “mình cần nói chuyện” nặng nề.",
        "2": "Tò mò giúp ích hơn phỏng đoán: hãy hỏi dạo này họ thế nào, thay vì đoán.",
        "3": "Sự hiện diện cũng quan trọng — đôi khi gắn kết lại bắt đầu đơn giản bằng việc ở cùng một phòng, không cần kế hoạch gì.",
      },
    },
  },
  tl: {
    hub: {
      intro: "Lahat ng kailangan para buuin at pagnilayan ang isang relasyon, nasa iisang lugar.",
      together: {
        title: "Kasama ang isang tao",
        subtitle: "Mga shared tool, ginagamit kasama ang isang partikular na match.",
      },
      onYourOwn: {
        title: "Mag-isa",
        subtitle: "Pribadong pagninilay — walang ibinabahagi rito sa isang match.",
      },
      row: {
        tools: {
          label: "Mga tool sa relasyon",
          a11y: "Mga tool sa relasyon na ibinabahagi sa isang partikular na match",
        },
        vault: {
          label: "Memory vault",
          a11y: "Memory vault, mga alaalang na-save kasama ang iyong mga match",
        },
        rehearsal: {
          label: "Rehearsal room",
          a11y: "Rehearsal room, magsanay ng mahihirap na usapan",
        },
        chemistry: {
          label: "Chemistry diary",
          a11y: "Ang iyong chemistry diary",
        },
        goodbye: {
          label: "Mga pribadong pagninilay",
          a11y: "Ang iyong mga pribadong pagninilay",
        },
        legacy: {
          label: "Karunungan sa relasyon",
          a11y: "Aklatan ng karunungan sa relasyon",
        },
        kit: {
          label: "Toolkit",
          a11y: "Toolkit sa relasyon",
        },
      },
    },
    tools: {
      loading: "Nilo-load ang mga tool sa relasyon...",
      loadError: "Hindi ma-load ang iyong mga tool sa relasyon.",
      intro: "Ibinabahagi ang mga tool na ito sa isang partikular na match — piliin kung sino ang gusto mong kasama.",
      meetPeopleA11y: "Makakilala ng tao",
      meetPeople: "Makakilala ng tao →",
      withA11y: "Mga tool sa relasyon kasama si {name}",
      someone: "Isang tao",
      toolsWith: "Mga tool kasama si {name}",
    },
    kit: {
      expandA11y: "{title}, i-double tap para buksan",
      collapseA11y: "{title}, i-double tap para isara",
      hard_conversation: {
        "1": "Pumili ng tamang sandali, hindi habang nag-aaway — itanong \"puwede ba nating pag-usapan ang isang bagay mamayang gabi?\" sa halip na sumugod kapag may naiinis na.",
        "2": "Magsimula sa kailangan mo, hindi sa mali niya: \"kailangan kong maramdamang kasama ako sa mga plano sa weekend\" ay iba ang dating kaysa \"hindi mo ako isinasama kahit kailan.\"",
        "3": "Asahan na medyo awkward sa simula. Normal iyon, hindi senyales na pumapalpak.",
      },
      apologize: {
        "1": "Pangalanan ang tiyak na bagay, hindi malabong damdamin: \"binalewala ko ang naramdaman mo kanina\" ay mas mabuti kaysa \"sorry kung naiinis ka.\"",
        "2": "Iwasan ang \"pero\" — ang paghingi ng tawad na may kasunod na paliwanag ay madalas na parang dahilan, kahit hindi iyon ang intensyon.",
        "3": "Itanong kung ano talaga ang makakatulong, sa halip na ipagpalagay na alam mo na.",
      },
      rebuild_trust: {
        "1": "Muling nabubuo ang tiwala sa maliliit at tuloy-tuloy na pagtupad sa paglipas ng panahon — hindi sa isang malaking gesture.",
        "2": "Maging mapagpasensya sa pag-iingat niya. Hindi ito parusa, kundi isang nervous system na nasaktan at nag-iingat.",
        "3": "Isipin na sabihin ito nang direkta: \"Ano ang makakatulong para mas maging sigurado ka sa akin ngayon?\"",
      },
      resentment: {
        "1": "Karaniwang ibig sabihin ng hinanakit ay isang pangangailangang hindi nasabi. Subukang pangalanan ang pangangailangan sa ilalim nito, hindi lang ang inis.",
        "2": "Nagpapatong-patong ang maliliit na bagay. Kung parang \"masyadong maliit para banggitin,\" madalas iyon mismo ang dapat banggitin nang maaga.",
        "3": "Isiping isulat muna ito nang pribado — minsan iba ang lumalabas sa inakala mong nararamdaman mo.",
      },
      reconnecting: {
        "1": "Magsimula nang mas maliit kaysa sa tingin mo'y kailangan — mas madalas gumana ang maikli at magaan na kumustahan kaysa sa malaking \"kailangan nating mag-usap.\"",
        "2": "Mas nakakatulong ang pagkamausisa kaysa sa pag-aakala: itanong kung ano ang pinagdadaanan niya, sa halip na manghula.",
        "3": "Mahalaga rin ang pisikal na presensya — minsan nagsisimula ang muling pagkakalapit sa simpleng pagiging nasa iisang kuwarto, walang agenda.",
      },
    },
  },
  ru: {
    hub: {
      intro: "Всё, чтобы строить отношения и размышлять о них, в одном месте.",
      together: {
        title: "Вместе с кем-то",
        subtitle: "Общие инструменты, которыми пользуются вместе с конкретным мэтчем.",
      },
      onYourOwn: {
        title: "Для себя",
        subtitle: "Личные размышления — ничего отсюда не видно мэтчу.",
      },
      row: {
        tools: {
          label: "Инструменты для отношений",
          a11y: "Инструменты для отношений, общие с конкретным мэтчем",
        },
        vault: {
          label: "Хранилище воспоминаний",
          a11y: "Хранилище воспоминаний, воспоминания с вашими мэтчами",
        },
        rehearsal: {
          label: "Репетиционная",
          a11y: "Репетиционная, практика трудных разговоров",
        },
        chemistry: {
          label: "Дневник химии",
          a11y: "Ваш дневник химии",
        },
        goodbye: {
          label: "Личные размышления",
          a11y: "Ваши личные размышления",
        },
        legacy: {
          label: "Мудрость отношений",
          a11y: "Библиотека мудрости отношений",
        },
        kit: {
          label: "Инструменты",
          a11y: "Инструменты для отношений",
        },
      },
    },
    tools: {
      loading: "Загружаем инструменты для отношений...",
      loadError: "Не удалось загрузить ваши инструменты для отношений.",
      intro: "Эти инструменты общие с конкретным мэтчем — выберите, с кем хотите ими пользоваться.",
      meetPeopleA11y: "Знакомиться",
      meetPeople: "Знакомиться →",
      withA11y: "Инструменты для отношений с {name}",
      someone: "Кто-то",
      toolsWith: "Инструменты с {name}",
    },
    kit: {
      expandA11y: "{title}, дважды коснитесь, чтобы развернуть",
      collapseA11y: "{title}, дважды коснитесь, чтобы свернуть",
      hard_conversation: {
        "1": "Выберите подходящий момент, а не посреди ссоры: спросите «можем поговорить кое о чём сегодня вечером?», а не начинайте, когда кто-то из вас уже расстроен.",
        "2": "Начните с того, что нужно вам, а не с того, что сделал не так другой: «мне важно участвовать в планах на выходные» звучит иначе, чем «ты никогда меня не зовёшь».",
        "3": "Будьте готовы, что сначала будет неловко. Это нормально и не значит, что всё идёт плохо.",
      },
      apologize: {
        "1": "Назовите конкретное, а не размытое чувство: «я отмахнулся от того, что ты чувствовал» лучше, чем «извини, что ты расстроен».",
        "2": "Обойдитесь без «но»: извинение с объяснением часто звучит как оправдание, даже если вы этого не хотели.",
        "3": "Спросите, что действительно поможет, а не думайте, что уже знаете.",
      },
      rebuild_trust: {
        "1": "Доверие восстанавливается маленькими, постоянными делами со временем, а не одним большим жестом.",
        "2": "Будьте терпеливы к осторожности другого. Это не наказание, а нервная система, которой было больно и которая бережётся.",
        "3": "Можно спросить прямо: «Что сейчас поможет тебе больше во мне не сомневаться?»",
      },
      resentment: {
        "1": "Обида обычно говорит о невысказанной потребности. Попробуйте назвать потребность за ней, а не только раздражение.",
        "2": "Мелочи накапливаются. Если что-то кажется «слишком мелким, чтобы упоминать», часто именно об этом стоит сказать пораньше.",
        "3": "Попробуйте сначала записать это для себя — иногда выходит не то, что вы, как вам казалось, чувствовали.",
      },
      reconnecting: {
        "1": "Начните с меньшего, чем кажется нужным: короткий лёгкий разговор часто работает лучше большого «нам надо поговорить».",
        "2": "Любопытство помогает больше догадок: спросите, что происходит у другого, а не гадайте.",
        "3": "Физическое присутствие тоже важно — иногда сближение начинается просто с того, чтобы быть в одной комнате, без всякой цели.",
      },
    },
  },
  ko: {
    hub: {
      intro: "관계를 가꾸고 돌아보는 데 필요한 모든 것을 한곳에.",
      together: {
        title: "누군가와 함께",
        subtitle: "특정 매치와 함께 쓰는 공유 도구예요.",
      },
      onYourOwn: {
        title: "나 혼자",
        subtitle: "나만의 회고 — 여기 있는 것은 매치와 공유되지 않아요.",
      },
      row: {
        tools: {
          label: "관계 도구",
          a11y: "특정 매치와 공유하는 관계 도구",
        },
        vault: {
          label: "추억 보관함",
          a11y: "추억 보관함, 매치와 저장한 추억",
        },
        rehearsal: {
          label: "연습실",
          a11y: "연습실, 어려운 대화 연습하기",
        },
        chemistry: {
          label: "케미 다이어리",
          a11y: "나의 케미 다이어리",
        },
        goodbye: {
          label: "나만의 회고",
          a11y: "나만의 회고 목록",
        },
        legacy: {
          label: "관계의 지혜",
          a11y: "관계의 지혜 라이브러리",
        },
        kit: {
          label: "도구 모음",
          a11y: "관계 도구 모음",
        },
      },
    },
    tools: {
      loading: "관계 도구 불러오는 중...",
      loadError: "관계 도구를 불러오지 못했어요.",
      intro: "이 도구들은 특정 매치와 함께 써요. 함께 쓸 사람을 골라 주세요.",
      meetPeopleA11y: "사람 만나기",
      meetPeople: "사람 만나기 →",
      withA11y: "{name}님과의 관계 도구",
      someone: "누군가",
      toolsWith: "{name}님과 쓰는 도구",
    },
    kit: {
      expandA11y: "{title}, 두 번 탭하여 펼치기",
      collapseA11y: "{title}, 두 번 탭하여 접기",
      hard_conversation: {
        "1": "다투는 중이 아니라 적절한 때를 고르세요. 둘 중 누군가 이미 속상할 때 바로 꺼내기보다 \"오늘 저녁에 얘기 좀 할 수 있을까?\"라고 물어보세요.",
        "2": "상대가 잘못한 것보다 내가 필요한 것부터 말하세요. \"주말 계획에 나도 함께하고 싶어\"는 \"넌 한 번도 날 끼워 주지 않잖아\"와 다르게 들려요.",
        "3": "처음엔 어색할 수 있어요. 자연스러운 일이지, 잘못되고 있다는 신호가 아니에요.",
      },
      apologize: {
        "1": "막연한 감정이 아니라 구체적인 일을 말하세요. \"아까 네 기분을 무시했어\"가 \"속상했다면 미안해\"보다 나아요.",
        "2": "\"하지만\"은 빼세요. 사과 뒤에 설명이 붙으면 의도와 달리 변명처럼 들리기 쉬워요.",
        "3": "이미 안다고 짐작하기보다 무엇이 정말 도움이 될지 물어보세요.",
      },
      rebuild_trust: {
        "1": "신뢰는 한 번의 큰 행동이 아니라 작고 꾸준한 실천이 쌓이며 회복돼요.",
        "2": "상대의 조심스러움에 인내심을 가지세요. 벌이 아니라, 상처받은 마음이 조심하고 있는 거예요.",
        "3": "직접 물어보는 것도 좋아요. \"지금 내가 어떻게 하면 네가 더 안심할 수 있을까?\"",
      },
      resentment: {
        "1": "원망은 보통 말하지 못한 욕구를 뜻해요. 답답함만이 아니라 그 밑에 있는 욕구를 말해 보세요.",
        "2": "작은 일도 쌓여요. \"말하기엔 너무 사소하다\" 싶은 게 오히려 일찍 말할 가치가 있는 경우가 많아요.",
        "3": "먼저 혼자 적어 보세요. 적다 보면 생각했던 감정과 다른 것이 나오기도 해요.",
      },
      reconnecting: {
        "1": "필요해 보이는 것보다 작게 시작하세요. 거창한 \"우리 얘기 좀 해\"보다 짧고 가벼운 안부가 더 효과적일 때가 많아요.",
        "2": "추측보다 호기심이 더 도움이 돼요. 짐작하지 말고 요즘 어떻게 지내는지 물어보세요.",
        "3": "함께 있는 것도 중요해요. 다시 가까워지는 건 그저 아무 계획 없이 같은 공간에 있는 것에서 시작되기도 해요.",
      },
    },
  },
};
