// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/rewards.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    member: "{name} Member",
    youveReachedTheTopTier: "You've reached the top tier",
    moreToNext: { one: "{count} more redemption to {tier}", other: "{count} more redemptions to {tier}" },
    tier: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
    },
  },
  es: {
    member: "Miembro {name}",
    youveReachedTheTopTier: "Llegaste al nivel más alto",
    moreToNext: { one: "Falta {count} canje para {tier}", other: "Faltan {count} canjes para {tier}" },
    tier: {
      bronze: "Bronce",
      silver: "Plata",
      gold: "Oro",
    },
  },
  de: {
    member: "{name}-Mitglied",
    youveReachedTheTopTier: "Du hast die höchste Stufe erreicht",
    moreToNext: { one: "Noch {count} Einlösung bis {tier}", other: "Noch {count} Einlösungen bis {tier}" },
    tier: {
      bronze: "Bronze",
      silver: "Silber",
      gold: "Gold",
    },
  },
  fr: {
    member: "Membre {name}",
    youveReachedTheTopTier: "Tu as atteint le niveau le plus haut",
    moreToNext: { one: "Encore {count} utilisation avant {tier}", other: "Encore {count} utilisations avant {tier}" },
    tier: {
      bronze: "Bronze",
      silver: "Argent",
      gold: "Or",
    },
  },
  pt: {
    member: "Membro {name}",
    youveReachedTheTopTier: "Você chegou ao nível mais alto",
    moreToNext: { one: "Falta {count} resgate para {tier}", other: "Faltam {count} resgates para {tier}" },
    tier: {
      bronze: "Bronze",
      silver: "Prata",
      gold: "Ouro",
    },
  },
  ht: {
    member: "Manm {name}",
    youveReachedTheTopTier: "Ou rive nan pi wo nivo a",
    moreToNext: { one: "Ankò {count} pou rive {tier}", other: "Ankò {count} pou rive {tier}" },
    tier: {
      bronze: "Bwonz",
      silver: "Ajan",
      gold: "Lò",
    },
  },
  zh: {
    member: "{name}会员",
    youveReachedTheTopTier: "你已达到最高等级",
    moreToNext: { other: "再兑换 {count} 次即可达到 {tier}" },
    tier: {
      bronze: "青铜",
      silver: "白银",
      gold: "黄金",
    },
  },
  vi: {
    member: "Thành viên {name}",
    youveReachedTheTopTier: "Bạn đã đạt hạng cao nhất",
    moreToNext: { other: "Thêm {count} lần đổi để lên {tier}" },
    tier: {
      bronze: "Đồng",
      silver: "Bạc",
      gold: "Vàng",
    },
  },
  tl: {
    member: "{name} Member",
    youveReachedTheTopTier: "Naabot mo na ang pinakamataas na tier",
    moreToNext: { one: "{count} pang redemption bago ang {tier}", other: "{count} pang redemption bago ang {tier}" },
    tier: {
      bronze: "Bronze",
      silver: "Silver",
      gold: "Gold",
    },
  },
  ru: {
    member: "Участник уровня {name}",
    youveReachedTheTopTier: "Вы достигли высшего уровня",
    moreToNext: { one: "Ещё {count} использование до уровня {tier}", few: "Ещё {count} использования до уровня {tier}", many: "Ещё {count} использований до уровня {tier}", other: "Ещё {count} использования до уровня {tier}" },
    tier: {
      bronze: "Бронза",
      silver: "Серебро",
      gold: "Золото",
    },
  },
  ko: {
    member: "{name} 회원",
    youveReachedTheTopTier: "최고 등급에 도달했어요",
    moreToNext: { other: "{tier}까지 {count}회 남았어요" },
    tier: {
      bronze: "브론즈",
      silver: "실버",
      gold: "골드",
    },
  },
};
