// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/suitedAges.json (localization pass 5). English is the app's own
// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.
export default {
  en: {
    band: {
      all_ages: "All ages",
      kids: "Kids (up to 12)",
      teens: "Teens (13–17)",
    },
    exactly: "Age {age}",
    range: "Ages {min}–{max}",
    from: "Ages {min}+",
    upTo: "Up to age {max}",
  },
  es: {
    band: {
      all_ages: "Todas las edades",
      kids: "Niños (hasta 12)",
      teens: "Adolescentes (13–17)",
    },
    exactly: "{age} años",
    range: "De {min} a {max} años",
    from: "Desde {min} años",
    upTo: "Hasta {max} años",
  },
  de: {
    band: {
      all_ages: "Alle Altersgruppen",
      kids: "Kinder (bis 12)",
      teens: "Teenager (13–17)",
    },
    exactly: "{age} Jahre",
    range: "{min}–{max} Jahre",
    from: "Ab {min} Jahren",
    upTo: "Bis {max} Jahre",
  },
  fr: {
    band: {
      all_ages: "Tous âges",
      kids: "Enfants (jusqu'à 12 ans)",
      teens: "Ados (13–17 ans)",
    },
    exactly: "{age} ans",
    range: "{min}–{max} ans",
    from: "Dès {min} ans",
    upTo: "Jusqu'à {max} ans",
  },
  pt: {
    band: {
      all_ages: "Todas as idades",
      kids: "Crianças (até 12)",
      teens: "Adolescentes (13–17)",
    },
    exactly: "{age} anos",
    range: "De {min} a {max} anos",
    from: "A partir de {min} anos",
    upTo: "Até {max} anos",
  },
  ht: {
    band: {
      all_ages: "Tout laj",
      kids: "Timoun (jiska 12 an)",
      teens: "Adolesan (13–17 an)",
    },
    exactly: "{age} an",
    range: "{min}–{max} an",
    from: "{min} an oswa plis",
    upTo: "Jiska {max} an",
  },
  zh: {
    band: {
      all_ages: "所有年龄",
      kids: "儿童（12 岁以下）",
      teens: "青少年（13–17 岁）",
    },
    exactly: "{age} 岁",
    range: "{min}–{max} 岁",
    from: "{min} 岁以上",
    upTo: "{max} 岁以下",
  },
  vi: {
    band: {
      all_ages: "Mọi lứa tuổi",
      kids: "Trẻ em (đến 12 tuổi)",
      teens: "Thiếu niên (13–17)",
    },
    exactly: "{age} tuổi",
    range: "{min}–{max} tuổi",
    from: "Từ {min} tuổi",
    upTo: "Đến {max} tuổi",
  },
  tl: {
    band: {
      all_ages: "Lahat ng edad",
      kids: "Mga bata (hanggang 12)",
      teens: "Mga teenager (13–17)",
    },
    exactly: "Edad {age}",
    range: "Edad {min}–{max}",
    from: "Edad {min} pataas",
    upTo: "Hanggang edad {max}",
  },
  ru: {
    band: {
      all_ages: "Любой возраст",
      kids: "Дети (до 12)",
      teens: "Подростки (13–17)",
    },
    exactly: "Возраст {age}",
    range: "Возраст {min}–{max}",
    from: "От {min} лет",
    upTo: "До {max} лет",
  },
  ko: {
    band: {
      all_ages: "전 연령",
      kids: "어린이 (12세까지)",
      teens: "청소년 (13–17세)",
    },
    exactly: "{age}세",
    range: "{min}–{max}세",
    from: "{min}세 이상",
    upTo: "{max}세까지",
  },
};
