export const BASICS_FIELDS = [
  { key: 'height', label: 'Height', type: 'text', placeholder: "e.g. 5'10\"" },
  { key: 'relationship_goals', label: 'Looking For', type: 'select', options: ['Long-term partner', 'Long-term, open to short', 'Short-term fun', 'New friends', 'Still figuring it out'] },
  { key: 'relationship_type', label: 'Relationship Type', type: 'select', options: ['Monogamy', 'Non-monogamy', 'Figuring out'] },
  { key: 'zodiac', label: 'Zodiac', type: 'select', options: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'] },
  { key: 'education', label: 'Education', type: 'select', options: ['High school', 'In college', 'Undergrad degree', 'In grad school', 'Grad degree', 'Trade school', 'Prefer not to say'] },
  { key: 'family_plans', label: 'Family Plans', type: 'select', options: ['Want children', "Don't want children", 'Have children, want more', "Have children, don't want more", 'Not sure yet'] },
  { key: 'communication_style', label: 'Communication Style', type: 'select', options: ['Big texter', 'Phone caller', 'Video chatter', 'Slow to reply', 'Balanced'] },
  { key: 'love_style', label: 'Love Language', type: 'select', options: ['Thoughtful gestures', 'Physical touch', 'Quality time', 'Deep talks', 'Gift giving'] },
  { key: 'pets', label: 'Pets', type: 'select', options: ['Dog', 'Cat', 'Reptile', 'Bird', 'Fish', 'Pet-free', 'Want a pet', 'Other'] },
  { key: 'drinking', label: 'Drinking', type: 'select', options: ['Yes', 'Sometimes', 'No'] },
  { key: 'smoking', label: 'Smoking', type: 'select', options: ['Yes', 'Sometimes', 'No'] },
  { key: 'cannabis', label: 'Cannabis', type: 'select', options: ['Yes', 'Sometimes', 'No'] },
  { key: 'workout', label: 'Workout', type: 'select', options: ['Everyday', 'Often', 'Sometimes', 'Never'] },
  { key: 'social_media', label: 'Social Media', type: 'select', options: ['Very active', 'Sometimes active', 'Prefer not to say', 'Off the grid'] },
  { key: 'school', label: 'School', type: 'text', placeholder: 'e.g. Florida Atlantic University' },
  { key: 'job_title', label: 'Job Title', type: 'text', placeholder: 'e.g. Software Engineer' },
  { key: 'living_in', label: 'Living In', type: 'text', placeholder: 'e.g. Delray Beach' },
];