export const BASICS_FIELDS = [
  { key: 'height', label: 'Height', icon: '📏', type: 'text', placeholder: "e.g. 5'10\"" },
  { key: 'living_in', label: 'Living In', icon: '📍', type: 'text', placeholder: 'e.g. Delray Beach' },
  { key: 'school', label: 'School', icon: '🎓', type: 'text', placeholder: 'e.g. Florida Atlantic University' },
  { key: 'job_title', label: 'Job Title', icon: '💼', type: 'text', placeholder: 'e.g. Software Engineer' },
  { key: 'relationship_goals', label: 'Looking For', icon: '💘', type: 'select', options: ['Long-term partner', 'Long-term, open to short', 'Short-term fun', 'New friends', 'Still figuring it out'] },
  { key: 'relationship_type', label: 'Relationship Type', icon: '💑', type: 'select', options: ['Monogamy', 'Non-monogamy', 'Figuring out'] },
  { key: 'zodiac', label: 'Zodiac', icon: '🔮', type: 'select', options: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'] },
  { key: 'education', label: 'Education', icon: '📚', type: 'select', options: ['High school', 'In college', 'Undergrad degree', 'In grad school', 'Grad degree', 'Trade school', 'Prefer not to say'] },
  { key: 'family_plans', label: 'Family Plans', icon: '👶', type: 'select', options: ['Want children', "Don't want children", 'Have children, want more', "Have children, don't want more", 'Not sure yet'] },
  { key: 'communication_style', label: 'Communication Style', icon: '💬', type: 'select', options: ['Big texter', 'Phone caller', 'Video chatter', 'Slow to reply', 'Balanced'] },
  { key: 'love_style', label: 'Love Language', icon: '❤️', type: 'select', options: ['Thoughtful gestures', 'Physical touch', 'Quality time', 'Deep talks', 'Gift giving'] },
  { key: 'pets', label: 'Pets', icon: '🐾', type: 'select', options: ['Dog', 'Cat', 'Reptile', 'Bird', 'Fish', 'Pet-free', 'Want a pet', 'Other'] },
  { key: 'drinking', label: 'Drinking', icon: '🍷', type: 'select', options: ['Yes', 'Sometimes', 'No'] },
  { key: 'smoking', label: 'Smoking', icon: '🚬', type: 'select', options: ['Yes', 'Sometimes', 'No'] },
  { key: 'cannabis', label: 'Cannabis', icon: '🌿', type: 'select', options: ['Yes', 'Sometimes', 'No'] },
  { key: 'workout', label: 'Workout', icon: '💪', type: 'select', options: ['Everyday', 'Often', 'Sometimes', 'Never'] },
  { key: 'social_media', label: 'Social Media', icon: '📱', type: 'select', options: ['Very active', 'Sometimes active', 'Prefer not to say', 'Off the grid'] },
  { key: 'five_year_vision', label: 'In 5 Years, I See Myself', icon: '🧭', type: 'text', placeholder: 'e.g. Settled somewhere warm, running my own business' },
  { key: 'dream_location', label: 'Dream Place to Live', icon: '🗺️', type: 'text', placeholder: 'e.g. Somewhere near the mountains' },
  { key: 'skill_to_learn', label: 'Skill I Want to Learn', icon: '🎯', type: 'text', placeholder: 'e.g. Spanish, sailing, cooking' },
  { key: 'financial_priority', label: 'Financial Priority', icon: '💰', type: 'select', options: ['Saving aggressively', 'Comfortable spending', 'Building wealth', 'Living in the moment', 'Figuring it out'] },
  { key: 'social_energy', label: 'Social Energy', icon: '🔋', type: 'select', options: ['Recharge alone', 'Recharge with people', 'Depends on the day'] },
  { key: 'weekend_style', label: 'Weekend Style', icon: '🌤️', type: 'select', options: ['Homebody', 'Always out and about', 'A mix of both'] },
  { key: 'independence_preference', label: 'Independence', icon: '🧘', type: 'select', options: ['Need lots of space', 'Love togetherness', 'Somewhere in between'] },
];