export const PROMPT_QUESTIONS = [
  'My simple pleasures are...',
  'The way to win me over is...',
  "I'll know it's time to delete this app when...",
  'A random fact I love is...',
  "My most controversial opinion is...",
  "Together, we could...",
  'The key to my heart is...',
  "I'm looking for...",
  'My ideal Sunday looks like...',
  "Two truths and a lie...",
  'The best way to ask me out is...',
  'My love language is...',
  "What's something you've changed your mind about?",
  'How do you spend a perfect Sunday?',
  'How do you handle disagreements?',
  'What are you excited about this year?',
  'The way I show love is...',
  'When I\'m stressed, what helps most is...',
  "I recharge by...",
  "Something I remember about people is...",
  "Something I'm working on getting better at is...",
  "A recent mistake and what it taught me...",
  "An ordinary Tuesday for me looks like (unfiltered)...",
  "The funniest thing that happened to me this week...",
  "Something small that made me happy recently...",
  "Something I'm a little obsessed with right now...",
];