// Builds src/i18n/ui/<ns>.js from scripts/i18n/strings/<ns>.json ({ en: {...}, es: {...}, ... }), and registers the namespace.
//   node scripts/i18n/build-ns.js <ns> [<localized file> ...]
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const [ns, ...files] = process.argv.slice(2);
const LANGS = ['en', 'es', 'de', 'fr', 'pt', 'ht', 'zh', 'vi', 'tl', 'ru', 'ko'];
const store = JSON.parse(fs.readFileSync(path.join(__dirname, 'strings', `${ns}.json`), 'utf8'));
const missing = LANGS.filter((l) => !store[l]).concat(LANGS.filter((l) => store[l]).flatMap((l) => Object.keys(store.en).filter((k) => store[l][k] == null).map((k) => `${l}.${k}`)));
if (missing.length) { console.error('missing:', missing.slice(0, 40).join(' '), missing.length); process.exit(1); }
const lit = (v) => (typeof v === 'string' ? JSON.stringify(v) : `{ ${Object.entries(v).map(([k, x]) => `${k}: ${JSON.stringify(x)}`).join(', ')} }`);
// dotted keys ("label.height") become nested objects so t('ui.<ns>.label.height') finds them
const nest = (flat) => { const o = {}; for (const [k, v] of Object.entries(flat)) { const parts = k.split('.'); let c = o; parts.slice(0, -1).forEach((p) => { c[p] = c[p] || {}; c = c[p]; }); c[parts[parts.length - 1]] = v; } return o; };
const isPlural = (v) => v && typeof v === 'object' && typeof v.other === 'string';
const ident = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
const emit = (obj, ind) => Object.entries(obj).map(([k, v]) => (typeof v === 'string' || isPlural(v) ? `${ind}${ident(k)}: ${lit(v)},` : `${ind}${ident(k)}: {\n${emit(v, `${ind}  `)}\n${ind}},`)).join('\n');
const body = LANGS.map((l) => `  ${l}: {\n${emit(nest(Object.fromEntries(Object.keys(store.en).map((k) => [k, store[l][k]]))), '    ')}\n  },`).join('\n');
fs.writeFileSync(path.join(__dirname, '../../src/i18n/ui', `${ns}.js`),
  `// Generated by scripts/i18n/build-ns.js from scripts/i18n/strings/${ns}.json (localization pass 5). English is the app's own\n// wording; the other ten languages are machine-authored and need native-speaker review. Edit the JSON, then rebuild.\nexport default {\n${body}\n};\n`);
execFileSync('python3', [path.join(__dirname, 'register.py'), ns, ...files], { stdio: 'inherit' });
console.log(`built ${ns}: ${Object.keys(store.en).length} keys`);
