-- Business Intelligence Phase 8 (Monetization, entitlement half only --
-- see CLAUDE.md's own locked plan for the full reasoning): real,
-- server-enforced business feature entitlements over the existing,
-- already-live brand_partners.tier column. No Stripe, no real money --
-- this is purely "what does each tier's real feature set unlock,"
-- config-driven rather than hardcoded, matching this file's own locked
-- "client-side hiding is not security" rule.
--
-- brand_partners.tier is the one canonical plan column -- already real,
-- already `check (tier in ('basic','growth','brand'))`, already
-- NOT NULL default 'basic'. Reused verbatim, no second tier concept.

create table if not exists public.plan_entitlements (
  id bigint generated by default as identity primary key,
  tier text not null check (tier in ('basic', 'growth', 'brand')),
  feature text not null,
  enabled boolean not null default true,
  -- Nullable -- null means "not a capped feature" (either unlimited, or
  -- a plain boolean enabled/disabled feature with no numeric ceiling).
  limit_value integer,
  unique (tier, feature)
);

-- A plan matrix itself is not sensitive (it's the same real menu every
-- tier already advertises) -- public-readable. The actual enforcement
-- never trusts a client read of this table on its own; every mutating/
-- gated RPC below re-checks server-side via check_business_entitlement().
alter table public.plan_entitlements enable row level security;
create policy "Anyone can view the plan entitlement matrix" on public.plan_entitlements
  for select using (true);

-- Real, locked matrix -- see CLAUDE.md's own "locked ceiling" for the
-- full reasoning behind each row, including the reconciled "Signature
-- Experiences == Offer Templates, one cap not two" correction.
insert into public.plan_entitlements (tier, feature, enabled, limit_value) values
  ('basic', 'signature_experiences', true, 3),
  ('growth', 'signature_experiences', true, null),
  ('brand', 'signature_experiences', true, null),

  ('basic', 'advanced_match_radar', false, null),
  ('growth', 'advanced_match_radar', true, null),
  ('brand', 'advanced_match_radar', true, null),

  ('basic', 'missed_match_reporting', false, null),
  ('growth', 'missed_match_reporting', true, null),
  ('brand', 'missed_match_reporting', true, null),

  ('basic', 'category_outcomes', false, null),
  ('growth', 'category_outcomes', true, null),
  ('brand', 'category_outcomes', true, null),

  ('basic', 'ai_offer_recommendations', false, null),
  ('growth', 'ai_offer_recommendations', true, null),
  ('brand', 'ai_offer_recommendations', true, null),

  ('basic', 'business_moments', false, null),
  ('growth', 'business_moments', true, null),
  ('brand', 'business_moments', true, null),

  ('basic', 'ai_level_1', true, null),
  ('growth', 'ai_level_1', true, null),
  ('brand', 'ai_level_1', true, null),

  ('basic', 'ai_level_2', false, null),
  ('growth', 'ai_level_2', true, null),
  ('brand', 'ai_level_2', true, null),

  ('basic', 'ai_level_3', false, null),
  ('growth', 'ai_level_3', false, null),
  ('brand', 'ai_level_3', true, null),

  ('basic', 'analytics_history_days', true, 30),
  ('growth', 'analytics_history_days', true, 90),
  ('brand', 'analytics_history_days', true, 365)
on conflict (tier, feature) do update set
  enabled = excluded.enabled,
  limit_value = excluded.limit_value;

-- ---------- FUNCTION: check_business_entitlement ----------
-- The one real internal enforcement primitive -- callable both by the
-- client (a legitimate UX-decision read, e.g. "should I show the locked
-- preview") and, more importantly, from inside every other mutating/
-- reading RPC below for the real server-side gate. Deliberately not
-- owner-scoped (auth.uid()) -- it's called with an already-known,
-- already-validated partner_id from contexts that have already checked
-- ownership themselves (or, for a future business-iterating sweep, no
-- single caller identity to check against at all) -- a business's own
-- tier/feature entitlement isn't private information the way a
-- specific customer record would be.
create or replace function public.check_business_entitlement(partner_id_param uuid, feature_param text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_tier text;
  v_row record;
begin
  select tier into v_tier from brand_partners where id = partner_id_param;
  v_tier := coalesce(v_tier, 'basic');

  select enabled, limit_value into v_row from plan_entitlements where tier = v_tier and feature = feature_param;

  if v_row is null then
    -- No matching row for this feature at all -- an honest default of
    -- "not entitled," never a fabricated limit, matching this schema's
    -- own "no invented signal" rule.
    return jsonb_build_object('enabled', false, 'limit_value', null);
  end if;

  return jsonb_build_object('enabled', v_row.enabled, 'limit_value', v_row.limit_value);
end;
$function$;

revoke all on function public.check_business_entitlement(uuid, text) from public, anon;
grant execute on function public.check_business_entitlement(uuid, text) to authenticated;

-- ---------- FUNCTION: get_business_entitlements ----------
-- The real, owner-scoped "here's my whole plan" read -- backs the
-- client's `getEntitlements()` call, one round trip for the whole
-- feature map instead of one check_business_entitlement() call per
-- feature.
create or replace function public.get_business_entitlements(partner_id_param uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_tier text;
  v_result jsonb;
begin
  if not exists (
    select 1 from profiles where id = auth.uid() and managed_partner_id = partner_id_param
  ) then
    raise exception 'You do not manage this business';
  end if;

  select tier into v_tier from brand_partners where id = partner_id_param;
  v_tier := coalesce(v_tier, 'basic');

  select jsonb_object_agg(feature, jsonb_build_object('enabled', enabled, 'limit_value', limit_value))
  into v_result
  from plan_entitlements
  where tier = v_tier;

  return jsonb_build_object('tier', v_tier, 'features', coalesce(v_result, '{}'::jsonb));
end;
$function$;

revoke all on function public.get_business_entitlements(uuid) from public, anon;
grant execute on function public.get_business_entitlements(uuid) to authenticated;

-- ---------- create_business_experience(): real server-side cap ----------
-- Pulled the live function body fresh via the Management API before
-- editing -- every other line below is byte-for-byte unchanged from
-- what was live in production; the only real edit is the new
-- entitlement check inserted right before the insert. Same signature,
-- so this is a plain CREATE OR REPLACE (no orphaned overload risk).
create or replace function public.create_business_experience(
  partner_id_param uuid,
  title_param text,
  description_param text default null,
  icon_param text default null,
  attributes_param text[] default '{}',
  price_level_param text default null,
  party_type_param text default null,
  ai_suggested_param boolean default false
)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_id uuid;
  v_entitlement jsonb;
  v_current_count integer;
begin
  if not exists (
    select 1 from profiles
    where id = auth.uid() and managed_partner_id = partner_id_param
  ) then
    raise exception 'You do not manage this business';
  end if;

  if title_param is null or char_length(trim(title_param)) = 0 then
    raise exception 'Title cannot be empty';
  end if;

  if attributes_param is not null and not (attributes_param <@ array['outdoor_seating', 'date_friendly', 'group_friendly', 'live_music', 'kid_friendly', 'quiet', 'casual', 'upscale']::text[]) then
    raise exception 'Invalid attribute';
  end if;

  if price_level_param is not null and price_level_param not in ('free', '$', '$$', '$$$') then
    raise exception 'Invalid price level';
  end if;

  if party_type_param is not null and party_type_param not in ('solo', 'friends', 'groups', 'date') then
    raise exception 'Invalid party type';
  end if;

  -- Real server-side entitlement enforcement -- a direct RPC call can
  -- never bypass this cap, matching this pass's own "client-side hiding
  -- is not security" instruction. "Signature Experiences" and "Offer
  -- Templates" are the identical real table (business_experiences) --
  -- one real cap, not two, per this plan's own reconciliation.
  select public.check_business_entitlement(partner_id_param, 'signature_experiences') into v_entitlement;
  if (v_entitlement ->> 'limit_value') is not null then
    select count(*) into v_current_count from business_experiences where partner_id = partner_id_param;
    if v_current_count >= (v_entitlement ->> 'limit_value')::integer then
      raise exception 'ENTITLEMENT_LIMIT:signature_experiences';
    end if;
  end if;

  insert into business_experiences (
    partner_id, title, description, icon, attributes, price_level, party_type, ai_suggested
  ) values (
    partner_id_param, trim(title_param), nullif(trim(coalesce(description_param, '')), ''),
    icon_param, coalesce(attributes_param, '{}'), price_level_param, party_type_param, coalesce(ai_suggested_param, false)
  )
  returning id into v_id;

  return v_id;
end;
$function$;

-- ---------- get_aggregated_demand_for_partner(): real redaction, not just hiding ----------
-- Pulled the live body fresh -- every other line unchanged; the only
-- real edit is a new v_advanced check and gating unmet_intent_count/
-- is_demand_gap on it. A Basic-tier business calling this RPC directly
-- gets a genuinely zeroed-out advanced signal, not just a client that
-- chooses not to render it.
create or replace function public.get_aggregated_demand_for_partner(partner_id_param uuid)
returns table(category text, request_count bigint, total_party_size bigint, soonest_date date, dominant_period text, dominant_period_count bigint, unmet_intent_count bigint, is_demand_gap boolean)
language plpgsql
stable security definer
set search_path to 'public'
as $function$
declare
  v_lat double precision;
  v_lng double precision;
  v_bucket_lat double precision;
  v_bucket_lng double precision;
  v_neighbor_buckets text[] := array[]::text[];
  v_dlat double precision;
  v_dlng double precision;
  v_advanced boolean;
begin
  if not exists (
    select 1 from profiles where id = auth.uid() and managed_partner_id = partner_id_param
  ) then
    return;
  end if;

  select coalesce((public.check_business_entitlement(partner_id_param, 'advanced_match_radar') ->> 'enabled')::boolean, false)
  into v_advanced;

  select latitude, longitude into v_lat, v_lng from brand_partners where id = partner_id_param;
  if v_lat is null or v_lng is null then
    return;
  end if;

  v_bucket_lat := round(v_lat::numeric, 1)::double precision;
  v_bucket_lng := round(v_lng::numeric, 1)::double precision;
  foreach v_dlat in array array[-0.1::double precision, 0::double precision, 0.1::double precision] loop
    foreach v_dlng in array array[-0.1::double precision, 0::double precision, 0.1::double precision] loop
      v_neighbor_buckets := array_append(
        v_neighbor_buckets,
        (round((v_bucket_lat + v_dlat)::numeric, 1)::double precision)::text || ',' || (round((v_bucket_lng + v_dlng)::numeric, 1)::double precision)::text
      );
    end loop;
  end loop;

  return query
  with nearby_open as (
    select br.category as req_category, br.party_size, br.date as req_date, br.time_window_start
    from business_requests br
    where br.status = 'open'
    and br.expires_at > now()
    and br.category is not null
    and br.latitude is not null and br.longitude is not null
    and (3958.8 * acos(
      least(1.0, greatest(-1.0,
        cos(radians(v_lat)) * cos(radians(br.latitude)) * cos(radians(br.longitude) - radians(v_lng)) +
        sin(radians(v_lat)) * sin(radians(br.latitude))
      ))
    )) <= br.radius_miles
  ),
  periods as (
    select
      req_category,
      case
        when extract(hour from time_window_start) < 12 then 'morning'
        when extract(hour from time_window_start) < 18 then 'afternoon'
        else 'evening'
      end as period_bucket,
      count(*) as period_count
    from nearby_open
    where time_window_start is not null
    group by 1, 2
  ),
  ranked_periods as (
    select req_category, period_bucket, period_count,
      row_number() over (partition by req_category order by period_count desc) as rn
    from periods
  ),
  real_demand as (
    select
      n.req_category as cat,
      count(*)::bigint as req_count,
      coalesce(sum(coalesce(n.party_size, 1)), 0)::bigint as party_total,
      min(n.req_date) as min_date,
      rp.period_bucket as dom_period,
      rp.period_count as dom_period_count
    from nearby_open n
    left join ranked_periods rp on rp.req_category = n.req_category and rp.rn = 1
    group by n.req_category, rp.period_bucket, rp.period_count
  ),
  unmet_intent as (
    select
      i.category as cat,
      count(*)::bigint as unmet_cnt
    from intent_submissions i
    where i.category is not null
      and i.had_any_result = false
      and i.wide_area = any(v_neighbor_buckets)
      and i.created_at > now() - interval '14 days'
    group by i.category
  ),
  -- Real, narrowly-defined "this partner genuinely serves this category"
  -- set -- see the migration's own header comment for why each half is
  -- required rather than any offer row at all.
  served_categories as (
    select ba.category as cat
    from business_availability ba
    where ba.partner_id = partner_id_param and ba.category is not null
    union
    select br.category as cat
    from business_request_offers bro
    join business_requests br on br.id = bro.request_id
    where bro.partner_id = partner_id_param
      and bro.status in ('accepted', 'completed')
      and br.category is not null
  )
  select
    coalesce(rd.cat, ui.cat) as category,
    coalesce(rd.req_count, 0)::bigint as request_count,
    coalesce(rd.party_total, 0)::bigint as total_party_size,
    rd.min_date as soonest_date,
    rd.dom_period as dominant_period,
    rd.dom_period_count as dominant_period_count,
    case when v_advanced then coalesce(ui.unmet_cnt, 0)::bigint else 0::bigint end as unmet_intent_count,
    case when v_advanced then not exists (
      select 1 from served_categories sc where sc.cat = coalesce(rd.cat, ui.cat)
    ) else false end as is_demand_gap
  from real_demand rd
  full outer join unmet_intent ui on ui.cat = rd.cat
  -- Real fix, found while wiring the dashboard's locked-preview UI, not
  -- caught by the original live-verify pass: without this filter, a
  -- category that ONLY exists via unmet_intent (real_demand has no row
  -- for it, so request_count is genuinely 0) still survives this full
  -- outer join for a non-advanced caller -- surfacing a confusing
  -- "0 recent searches" row that leaks the mere existence of hidden
  -- signal even though its real value is correctly redacted to 0. A
  -- non-advanced caller now simply never sees that category at all,
  -- matching the entitlement's real intent: any row whose only reason to
  -- exist is unmet-intent data is itself part of the gated signal.
  where v_advanced or coalesce(rd.req_count, 0) > 0
  order by coalesce(rd.req_count, 0) desc, coalesce(ui.unmet_cnt, 0) desc
  limit 10;
end;
$function$;

-- ---------- get_missed_match_summary(): real entitlement gate, not a silent empty ----------
-- Pulled the live body fresh -- unlike the ownership check (which stays
-- a silent `return;`, matching this function's own established
-- convention), an entitlement failure raises a real, client-recognizable
-- error so the caller can distinguish "you own this but haven't
-- upgraded" from "nothing missed yet."
create or replace function public.get_missed_match_summary(partner_id_param uuid, days_back_param integer default 30)
returns table(source text, reason text, exclusion_count bigint)
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not exists (
    select 1 from profiles where id = auth.uid() and managed_partner_id = partner_id_param
  ) then
    return;
  end if;

  if not coalesce((public.check_business_entitlement(partner_id_param, 'missed_match_reporting') ->> 'enabled')::boolean, false) then
    raise exception 'ENTITLEMENT_REQUIRED:missed_match_reporting';
  end if;

  return query
  select bme.source, bme.reason, count(*)
  from business_match_exclusions bme
  where bme.partner_id = partner_id_param
  and bme.created_at >= now() - make_interval(days => coalesce(days_back_param, 30))
  group by bme.source, bme.reason
  order by count(*) desc;
end;
$function$;

-- ---------- get_partner_category_outcomes(): same real entitlement gate ----------
create or replace function public.get_partner_category_outcomes(partner_id_param uuid)
returns table(category text, total_opportunities bigint, response_rate numeric, acceptance_rate numeric, completion_rate numeric, rated_count bigint, pct_satisfied numeric, pct_would_repeat numeric)
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not exists (
    select 1 from profiles where id = auth.uid() and managed_partner_id = partner_id_param
  ) then
    return;
  end if;

  if not coalesce((public.check_business_entitlement(partner_id_param, 'category_outcomes') ->> 'enabled')::boolean, false) then
    raise exception 'ENTITLEMENT_REQUIRED:category_outcomes';
  end if;

  return query
  select
    coalesce(br.category, 'Uncategorized') as category,
    count(*) as total_opportunities,
    round(100.0 * count(*) filter (where bro.responded_at is not null) / nullif(count(*), 0), 1) as response_rate,
    round(100.0 * count(*) filter (where bro.status in ('accepted', 'completed')) / nullif(count(*) filter (where bro.responded_at is not null), 0), 1) as acceptance_rate,
    round(100.0 * count(*) filter (where bro.status = 'completed') / nullif(count(*) filter (where bro.status in ('accepted', 'completed')), 0), 1) as completion_rate,
    count(distinct boo.id) as rated_count,
    round(100.0 * count(distinct boo.id) filter (where boo.satisfaction_rating in ('loved_it', 'good')) / nullif(count(distinct boo.id), 0), 1) as pct_satisfied,
    round(100.0 * count(distinct boo.id) filter (where boo.would_repeat in ('yes', 'maybe')) / nullif(count(distinct boo.id), 0), 1) as pct_would_repeat
  from business_request_offers bro
  join business_requests br on br.id = bro.request_id
  left join business_offer_outcomes boo on boo.offer_id = bro.id
  where bro.partner_id = partner_id_param
  group by coalesce(br.category, 'Uncategorized')
  having count(*) >= 5
  order by count(*) desc;
end;
$function$;

-- ---------- stories.partner_id INSERT: real server-side business_moments gate ----------
-- A BEFORE INSERT trigger, not a change to the existing RLS policy --
-- keeps the real "own business only" ownership check exactly where it
-- already lives (the policy), and adds the new entitlement check as a
-- clear, separately-raised business rule, matching this schema's own
-- established convention (e.g. prevent_self_premium_edit()) for a rule
-- that's about business logic, not row ownership.
create or replace function public.enforce_business_moment_entitlement()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_entitlement jsonb;
begin
  if new.partner_id is not null then
    select public.check_business_entitlement(new.partner_id, 'business_moments') into v_entitlement;
    if not coalesce((v_entitlement ->> 'enabled')::boolean, false) then
      raise exception 'ENTITLEMENT_REQUIRED:business_moments';
    end if;
  end if;
  return new;
end;
$function$;

drop trigger if exists enforce_business_moment_entitlement_trigger on public.stories;
create trigger enforce_business_moment_entitlement_trigger
  before insert on public.stories
  for each row execute function public.enforce_business_moment_entitlement();

-- ---------- admin_set_business_tier(): dev/admin-only tier switch, no Stripe ----------
-- Real admin-only RPC, same is_admin-gated convention every other admin
-- action in this schema already uses. Clearly not exposed to a real
-- business anywhere -- reachable only from a new admin screen.
create or replace function public.admin_set_business_tier(partner_id_param uuid, tier_param text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if not exists (select 1 from profiles where id = auth.uid() and is_admin = true) then
    raise exception 'Only admins can change a business tier.';
  end if;

  if tier_param not in ('basic', 'growth', 'brand') then
    raise exception 'Invalid tier';
  end if;

  update brand_partners set tier = tier_param where id = partner_id_param;

  if not found then
    raise exception 'Business not found';
  end if;

  return jsonb_build_object('success', true, 'tier', tier_param);
end;
$function$;

revoke all on function public.admin_set_business_tier(uuid, text) from public, anon;
grant execute on function public.admin_set_business_tier(uuid, text) to authenticated;

-- ---------- admin_list_businesses(): the real list the tier-switch screen reads ----------
-- brand_partners' own RLS ("Anyone can view active partners", active =
-- true only) would silently hide an inactive business from an admin
-- browsing this dev screen -- a real, separate SECURITY DEFINER read,
-- same is_admin-gated convention as admin_set_business_tier(), not a
-- second RLS policy opened on the base table.
create or replace function public.admin_list_businesses(search_param text default null)
returns table(id uuid, name text, tier text, active boolean)
language plpgsql
stable security definer
set search_path to 'public'
as $function$
begin
  -- Real bug caught live, not just theorized: RETURNS TABLE(...) creates
  -- implicit OUT-parameter variables (id/name/tier/active) in scope for
  -- the WHOLE function body, not just the final SELECT -- a bare `id`
  -- inside this check collides with that OUT parameter, not
  -- profiles.id, raising "column reference is ambiguous". Explicitly
  -- qualified below, matching the same class of bug this schema's own
  -- history has already hit once for a bare category/soonest_date/
  -- dominant_period identifier (see the Business Intelligence Phase A
  -- migration's own header comment).
  if not exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true) then
    raise exception 'Only admins can list businesses.';
  end if;

  return query
  select bp.id, bp.name, bp.tier, bp.active
  from brand_partners bp
  where search_param is null or bp.name ilike '%' || search_param || '%'
  order by bp.name asc
  limit 100;
end;
$function$;

revoke all on function public.admin_list_businesses(text) from public, anon;
grant execute on function public.admin_list_businesses(text) to authenticated;
