-- Broader consumer subcategories (owner request, 2026-09-21). The 19 majors already exist; this adds leaf tags to the
-- thin ones from the same vocabulary the whole system reads (category_tag_groups, item 56: FKs, category-aware routing,
-- business_served_tags, interests). Each tag belongs to exactly ONE group (the PK) and none duplicates an existing tag
-- case-insensitively. Cuisine stays a separate business field (brand_partners.cuisine), not a leaf tag. Mirrored in
-- src/constants/gatheringCategories.js; categoryMapping.test.js keeps the two identical. Idempotent.
insert into public.category_tag_groups (tag, group_key) values
  ('Restaurants', 'food_drink'),
  ('Dessert & Ice Cream', 'food_drink'),
  ('Fine Dining', 'food_drink'),
  ('Fast Casual', 'food_drink'),
  ('Takeout & Delivery', 'food_drink'),
  ('Wineries', 'food_drink'),
  ('Gyms', 'activities_recreation'),
  ('Pilates', 'activities_recreation'),
  ('Walking', 'activities_recreation'),
  ('Basketball', 'activities_recreation'),
  ('Soccer', 'activities_recreation'),
  ('Volleyball', 'activities_recreation'),
  ('Skating', 'activities_recreation'),
  ('Martial Arts', 'activities_recreation'),
  ('Water Sports', 'activities_recreation'),
  ('Boating', 'activities_recreation'),
  ('Adventure', 'activities_recreation'),
  ('Live Music', 'entertainment_nightlife'),
  ('DJs', 'entertainment_nightlife'),
  ('Nightclubs', 'entertainment_nightlife'),
  ('Theater', 'entertainment_nightlife'),
  ('Performing Arts', 'entertainment_nightlife'),
  ('Festivals', 'entertainment_nightlife'),
  ('Arcade', 'entertainment_nightlife'),
  ('Escape Rooms', 'entertainment_nightlife'),
  ('Casinos', 'entertainment_nightlife'),
  ('Special Events', 'entertainment_nightlife'),
  ('Street Events', 'entertainment_nightlife'),
  ('Date Night', 'dating_social'),
  ('First Date', 'dating_social'),
  ('Double Date', 'dating_social'),
  ('Make New Friends', 'dating_social'),
  ('Couples', 'dating_social'),
  ('Social Clubs', 'dating_social'),
  ('Art Galleries', 'arts_culture_learning'),
  ('Art Classes', 'arts_culture_learning'),
  ('Pottery', 'arts_culture_learning'),
  ('Cultural Events', 'arts_culture_learning'),
  ('History', 'arts_culture_learning'),
  ('Libraries', 'arts_culture_learning'),
  ('Music Lessons', 'arts_culture_learning'),
  ('Classes', 'education_classes'),
  ('Boutiques', 'shopping'),
  ('Clothing', 'shopping'),
  ('Jewelry', 'shopping'),
  ('Home & Furniture', 'shopping'),
  ('Electronics', 'shopping'),
  ('Markets', 'shopping'),
  ('Pop-Ups', 'shopping'),
  ('Local Shopping', 'shopping'),
  ('Massage', 'wellness_beauty'),
  ('Salons', 'wellness_beauty'),
  ('Barbers', 'wellness_beauty'),
  ('Nails', 'wellness_beauty'),
  ('Skin Care', 'wellness_beauty'),
  ('Wellness Centers', 'wellness_beauty'),
  ('Sauna', 'wellness_beauty'),
  ('Recovery', 'wellness_beauty'),
  ('Family Events', 'family_kids'),
  ('Playgrounds', 'family_kids'),
  ('Indoor Play', 'family_kids'),
  ('Kids Museums', 'family_kids'),
  ('Camps', 'family_kids'),
  ('Kids Sports', 'family_kids'),
  ('Birthday Activities', 'family_kids'),
  ('Family Dining', 'family_kids'),
  ('Parks', 'outdoors_nature'),
  ('Beaches', 'outdoors_nature'),
  ('Trails', 'outdoors_nature'),
  ('Paddleboarding', 'outdoors_nature'),
  ('Wildlife', 'outdoors_nature'),
  ('Gardens', 'outdoors_nature'),
  ('Scenic Views', 'outdoors_nature'),
  ('Picnics', 'outdoors_nature'),
  ('Dog Parks', 'pets'),
  ('Pet Friendly Places', 'pets'),
  ('Pet Events', 'pets'),
  ('Grooming', 'pets'),
  ('Pet Stores', 'pets'),
  ('Pet Boarding', 'pets'),
  ('Dog Walking', 'pets'),
  ('Pet Training', 'pets'),
  ('Veterinary', 'pets'),
  ('Cleaning', 'home_local_services'),
  ('Landscaping', 'home_local_services'),
  ('Plumbing', 'home_local_services'),
  ('Electrical', 'home_local_services'),
  ('HVAC', 'home_local_services'),
  ('Handyman', 'home_local_services'),
  ('Moving', 'home_local_services'),
  ('Pest Control', 'home_local_services'),
  ('Repairs', 'home_local_services'),
  ('Interior Design', 'home_local_services'),
  ('Car Wash', 'auto_transportation'),
  ('Detailing', 'auto_transportation'),
  ('Auto Repair', 'auto_transportation'),
  ('Tires', 'auto_transportation'),
  ('Oil Change', 'auto_transportation'),
  ('EV Charging', 'auto_transportation'),
  ('Car Rental', 'auto_transportation'),
  ('Parking', 'auto_transportation'),
  ('Towing', 'auto_transportation'),
  ('Conferences', 'business_networking'),
  ('Professional Events', 'business_networking'),
  ('Entrepreneurship', 'business_networking'),
  ('Career Events', 'business_networking'),
  ('Real Estate', 'business_networking'),
  ('Finance', 'business_networking'),
  ('Charity', 'community_volunteering'),
  ('Community Events', 'community_volunteering'),
  ('Neighborhood Events', 'community_volunteering'),
  ('Cleanups', 'community_volunteering'),
  ('Donation Drives', 'community_volunteering'),
  ('Tours', 'travel_experiences'),
  ('Excursions', 'travel_experiences'),
  ('Boat Tours', 'travel_experiences'),
  ('Adventure Experiences', 'travel_experiences'),
  ('Local Experiences', 'travel_experiences'),
  ('Resorts', 'stay_getaway'),
  ('Hotels', 'stay_getaway')
on conflict (tag) do nothing;
