-- Category synonyms (owner items 31/32, 2026-09-21): ONE deterministic phrase -> canonical tag table, so the many ways of
-- saying a thing ("cafe", "coffee shop", "gym", "fitness center", "happy hour") resolve to the canonical tag(s)
-- instead of becoming new categories. Seeded verbatim from src/constants/categorySynonyms.js (a Jest test fails if the two
-- drift). Client-closed (read only through functions). Used here by emerging-category flagging: a phrase that is a known
-- synonym is never proposed as a new category. Rule-based, no AI.
create table if not exists public.category_synonyms (
  phrase text not null check (phrase = lower(btrim(phrase)) and char_length(phrase) between 2 and 60),
  tag text not null references public.category_tag_groups(tag) on update cascade on delete cascade,
  primary key (phrase, tag)
);
alter table public.category_synonyms enable row level security;
revoke all on public.category_synonyms from public, anon, authenticated;

insert into public.category_synonyms (phrase, tag) values
  ('cafe', 'Coffee'),
  ('caf', 'Coffee'),
  ('coffee shop', 'Coffee'),
  ('coffeehouse', 'Coffee'),
  ('coffee house', 'Coffee'),
  ('coffee bar', 'Coffee'),
  ('coffee place', 'Coffee'),
  ('specialty coffee', 'Coffee'),
  ('espresso', 'Coffee'),
  ('espresso bar', 'Coffee'),
  ('coffee roaster', 'Coffee'),
  ('latte', 'Coffee'),
  ('gym', 'Gyms'),
  ('gym', 'Fitness'),
  ('fitness center', 'Gyms'),
  ('fitness center', 'Fitness'),
  ('fitness centre', 'Gyms'),
  ('fitness centre', 'Fitness'),
  ('health club', 'Gyms'),
  ('health club', 'Fitness'),
  ('workout', 'Gyms'),
  ('workout', 'Fitness'),
  ('weight room', 'Gyms'),
  ('weight room', 'Fitness'),
  ('exercise', 'Gyms'),
  ('exercise', 'Fitness'),
  ('happy hour', 'Happy Hour'),
  ('happy hour', 'Bars & Lounges'),
  ('drink special', 'Happy Hour'),
  ('drink special', 'Bars & Lounges'),
  ('bar', 'Bars & Lounges'),
  ('pub', 'Bars & Lounges'),
  ('cocktail bar', 'Bars & Lounges'),
  ('lounge', 'Bars & Lounges'),
  ('tavern', 'Bars & Lounges'),
  ('cocktail', 'Bars & Lounges'),
  ('brewery', 'Breweries'),
  ('brewpub', 'Breweries'),
  ('craft beer', 'Breweries'),
  ('taproom', 'Breweries'),
  ('tap room', 'Breweries'),
  ('beer', 'Breweries'),
  ('winery', 'Wine'),
  ('winery', 'Wineries'),
  ('wine bar', 'Wine'),
  ('wine bar', 'Wineries'),
  ('wine tasting', 'Wine'),
  ('wine tasting', 'Wineries'),
  ('vineyard', 'Wine'),
  ('vineyard', 'Wineries'),
  ('bakery', 'Bakeries'),
  ('bake shop', 'Bakeries'),
  ('patisserie', 'Bakeries'),
  ('pastry shop', 'Bakeries'),
  ('brunch spot', 'Brunch'),
  ('breakfast spot', 'Brunch'),
  ('restaurant', 'Restaurants'),
  ('eatery', 'Restaurants'),
  ('diner', 'Restaurants'),
  ('bistro', 'Restaurants'),
  ('dinner', 'Restaurants'),
  ('lunch', 'Restaurants'),
  ('upscale dining', 'Fine Dining'),
  ('tasting menu', 'Fine Dining'),
  ('fancy dinner', 'Fine Dining'),
  ('quick bite', 'Fast Casual'),
  ('counter service', 'Fast Casual'),
  ('food truck', 'Food Trucks'),
  ('street food', 'Food Trucks'),
  ('ice cream', 'Dessert & Ice Cream'),
  ('gelato', 'Dessert & Ice Cream'),
  ('froyo', 'Dessert & Ice Cream'),
  ('frozen yogurt', 'Dessert & Ice Cream'),
  ('dessert', 'Dessert & Ice Cream'),
  ('sweet', 'Dessert & Ice Cream'),
  ('creamery', 'Dessert & Ice Cream'),
  ('yoga studio', 'Yoga'),
  ('hot yoga', 'Yoga'),
  ('vinyasa', 'Yoga'),
  ('pilate studio', 'Pilates'),
  ('reformer', 'Pilates'),
  ('karate', 'Martial Arts'),
  ('judo', 'Martial Arts'),
  ('jiu jitsu', 'Martial Arts'),
  ('bjj', 'Martial Arts'),
  ('taekwondo', 'Martial Arts'),
  ('boxing', 'Martial Arts'),
  ('mma', 'Martial Arts'),
  ('dojo', 'Martial Arts'),
  ('rock climbing', 'Climbing'),
  ('bouldering', 'Climbing'),
  ('climbing gym', 'Climbing'),
  ('driving range', 'Golf'),
  ('mini golf', 'Golf'),
  ('golf course', 'Golf'),
  ('indoor golf', 'Golf'),
  ('golf simulator', 'Golf'),
  ('bowling alley', 'Bowling'),
  ('arcade bar', 'Arcade'),
  ('video game', 'Arcade'),
  ('game room', 'Arcade'),
  ('escape room', 'Escape Rooms'),
  ('puzzle room', 'Escape Rooms'),
  ('live band', 'Live Music'),
  ('gig', 'Live Music'),
  ('music venue', 'Live Music'),
  ('nightclub', 'Nightclubs'),
  ('night club', 'Nightclubs'),
  ('dance club', 'Nightclubs'),
  ('club night', 'Nightclubs'),
  ('massage therapy', 'Massage'),
  ('spa massage', 'Massage'),
  ('hair salon', 'Salons'),
  ('hairdresser', 'Salons'),
  ('hair stylist', 'Salons'),
  ('barber shop', 'Barbers'),
  ('barbershop', 'Barbers'),
  ('nail salon', 'Nails'),
  ('manicure', 'Nails'),
  ('pedicure', 'Nails'),
  ('day spa', 'Spa Day'),
  ('spa', 'Spa Day'),
  ('car wash', 'Car Wash'),
  ('auto wash', 'Car Wash'),
  ('mechanic', 'Auto Repair'),
  ('car repair', 'Auto Repair'),
  ('auto shop', 'Auto Repair'),
  ('garage', 'Auto Repair'),
  ('house cleaning', 'Cleaning'),
  ('maid service', 'Cleaning'),
  ('cleaner', 'Cleaning'),
  ('plumber', 'Plumbing'),
  ('electrician', 'Electrical'),
  ('hotel', 'Hotels'),
  ('inn', 'Hotels'),
  ('motel', 'Hotels'),
  ('lodging', 'Hotels'),
  ('boutique hotel', 'Hotels'),
  ('museum', 'Museums'),
  ('art museum', 'Museums'),
  ('dog park', 'Dogs'),
  ('dog park', 'Dog Parks'),
  ('off leash', 'Dogs'),
  ('off leash', 'Dog Parks'),
  ('photo walk', 'Photography'),
  ('photographer', 'Photography'),
  ('hike', 'Hiking'),
  ('trail walk', 'Hiking'),
  ('cooking lesson', 'Cooking Class'),
  ('culinary class', 'Cooking Class')
on conflict do nothing;

create or replace function public.admin_get_emerging_categories()
returns table (phrase_key text, sample_phrase text, applicants int, wordings text[], first_seen timestamptz, last_seen timestamptz)
language plpgsql stable security definer set search_path = public as $$
begin
  if not exists (select 1 from profiles where id = auth.uid() and is_admin = true) then
    raise exception 'Only admins can see category suggestions';
  end if;
  return query
  select c.cluster_key,
         mode() within group (order by lower(c.wording)),
         count(distinct c.business_id)::int,
         (array_agg(distinct lower(c.wording)))[1:6],
         min(c.created_at), max(c.created_at)
  from public._category_candidate_rows() c
  where not exists (select 1 from category_tag_groups g where public._category_phrase_key(g.tag) in (c.own_key, c.cluster_key))
    and not exists (select 1 from category_aliases a where public._category_phrase_key(a.phrase) in (c.own_key, c.cluster_key))
    and not exists (select 1 from category_synonyms s where public._category_phrase_key(s.phrase) in (c.own_key, c.cluster_key))
    and not exists (select 1 from category_suggestion_dismissals d where d.phrase_key = c.cluster_key)
  group by c.cluster_key
  having count(distinct c.business_id) >= public.category_suggestion_min_applicants()
  order by 3 desc, 6 desc;
end $$;
revoke all on function public.admin_get_emerging_categories() from public, anon;
grant execute on function public.admin_get_emerging_categories() to authenticated;

